import { existsSync } from "node:fs";
import { resolve } from "node:path";
import type { SupabaseClient } from "@supabase/supabase-js";
import { MASTRA_RESOURCE_ID_KEY } from "@mastra/core/request-context";
import { registerApiRoute } from "@mastra/core/server";
import { listFactsByKeys } from "../../db/taxFacts";
import { DRAFTS_DIR } from "../../fs/draftsDir";
import { buildCaseState } from "../../tools/caseState";
import { DEMO_TAX_YEAR } from "../demoSession";
import { REQUEST_CONTEXT_KEYS } from "../userSupabaseMiddleware";

// Live status for the right rail — open asks, progress, draft URL, money
// summary. Reads run through the per-request user-scoped Supabase client; the
// authenticated user's UUID drives both RLS-scoped queries and the per-user
// PDF filenames generated by generate-tax-documents.
export const appStateRoute = registerApiRoute("/app/state", {
  method: "GET",
  handler: async (c) => {
    const requestContext = c.get("requestContext");
    const supabase = requestContext?.get(REQUEST_CONTEXT_KEYS.userSupabase) as
      | SupabaseClient
      | undefined;
    const userId = requestContext?.get(MASTRA_RESOURCE_ID_KEY) as
      | string
      | undefined;
    if (!supabase || !userId) return c.json({ error: "unauthorized" }, 401);

    const result = await buildCaseState(supabase, DEMO_TAX_YEAR);

    // PDF URL existence checks. Returns the public path when the file exists
    // on disk, null otherwise — UI uses this to show/hide the document links.
    const draftFilename = `1040-${userId}-${DEMO_TAX_YEAR}.pdf`;
    const draftUrl = existsSync(resolve(DRAFTS_DIR, draftFilename))
      ? `/drafts/${draftFilename}`
      : null;

    const form8949Filename = `8949-${userId}-${DEMO_TAX_YEAR}.pdf`;
    const form8949Url = existsSync(resolve(DRAFTS_DIR, form8949Filename))
      ? `/drafts/${form8949Filename}`
      : null;

    const scheduleDFilename = `schedule-d-${userId}-${DEMO_TAX_YEAR}.pdf`;
    const scheduleDUrl = existsSync(resolve(DRAFTS_DIR, scheduleDFilename))
      ? `/drafts/${scheduleDFilename}`
      : null;

    const form540Filename = `540-${userId}-${DEMO_TAX_YEAR}.pdf`;
    const form540Url = existsSync(resolve(DRAFTS_DIR, form540Filename))
      ? `/drafts/${form540Filename}`
      : null;

    const sidecarFilename = `forms-${userId}-${DEMO_TAX_YEAR}.json`;
    const sidecarUrl = existsSync(resolve(DRAFTS_DIR, sidecarFilename))
      ? `/drafts/${sidecarFilename}`
      : null;

    // Pull the first-name fact for the header greeting.
    const nameRows = await listFactsByKeys(supabase, DEMO_TAX_YEAR, [
      "identity.name.first",
    ]);
    const taxpayerFirstName =
      nameRows.length > 0 && typeof nameRows[0].value === "string"
        ? (nameRows[0].value as string)
        : null;

    // Adapter: bridge new caseState shape back to the legacy fields the
    // current Layout/Activity UI consumes. When we update the UI to read
    // forms[] directly, this collapses.
    const openAsks = result.pendingDecisions.map((d) => ({
      factKey: d,
      prompt: `Need decision: ${d}`,
      origin: "form-engine",
      stage: "decisions",
    }));
    const totalForms = result.summaries.length;
    const computedForms = result.summaries.filter(
      (f) =>
        f.mustFile.ok &&
        (f.mustFile.value === false || f.blockedLineCount === 0),
    ).length;
    const overallPct =
      totalForms > 0 ? Math.round((computedForms / totalForms) * 100) : 0;
    const progress = {
      intakePct: overallPct,
      scopingPct: overallPct,
      docsPct: overallPct,
      overallPct,
    };
    const refundOrBalance =
      result.money.federalRefund > 0
        ? { direction: "refund", amount: result.money.federalRefund }
        : result.money.federalOwed > 0
          ? { direction: "balance_due", amount: result.money.federalOwed }
          : null;
    const moneyLegacy = {
      totalWages: result.money.totalWages,
      agi: result.money.federalAgi,
      taxableIncome: result.money.federalTaxableIncome,
      federalTaxOwed: result.money.federalTax,
      federalWithholding: result.money.federalWithholding,
      refundOrBalance,
    };

    return c.json({
      withinMvp: true,
      mvpViolations: [] as string[],
      openAsks,
      progress,
      money: moneyLegacy,
      factCount: result.factCount,
      decisionCount: result.decisionRows.length,
      draftUrl,
      form8949Url,
      scheduleDUrl,
      form540Url,
      sidecarUrl,
      taxpayerFirstName,
    });
  },
});
