// AI-generated by forms:bind. Hand edits are allowed; mark them with
// `// MANUAL EDIT:` so they're easy to find + re-apply after a regen.
// Source: forms-pipeline/generateBindingsWorkflow
// Form: Sales and Other Dispositions of Capital Assets (form-8949, tax year 2025)
// Generated at: 2026-05-18T17:27:34.185Z

import { defineForm, sum } from "../../engine.js";
import type { Form8949 } from "./types.js";
import type { Form8949FilingInfo } from "./filingInfo.js";

// Per-row gain/loss = proceeds − basis + adjustment, but only when the
// row actually has a trade. Returning undefined for empty rows keeps
// `Math.ceil`-style 0s from rendering as "0" in unused widgets — the
// renderer skips blocked fields entirely.
//
// `proceeds` is the row's anchor: if a row has no proceeds value, the
// row is empty (no trade assigned to it), regardless of what the other
// columns contain. Used by all 22 row gain_loss bindings below.
function rowGainLoss(
  proceeds: unknown,
  costBasis: unknown,
  adjustment: unknown,
): number | undefined {
  if (typeof proceeds !== "number") return undefined;
  return (
    proceeds -
    (typeof costBasis === "number" ? costBasis : 0) +
    (typeof adjustment === "number" ? adjustment : 0)
  );
}

// Wrapping defineForm inside a register() function lets callers
// import { register } and force the side-effectful registration once
// at startup. Idempotent — calling twice overwrites in place.
export function register(): void {
  defineForm<Form8949, Form8949FilingInfo>("form-8949", {
    // MANUAL EDIT: AI flagged this as TODO ("decisions.scope.has_reportable_sales
    // has no FilingInfo slot"). The decision flows through to
    // `info.mustFile8949` via resolveFilingInfo. Same per-form scope
    // pattern as 1040 / 540 / Schedule CA.
    mustFile: (info) => info.mustFile8949,

    bindings: {
      // MANUAL EDIT: AI flagged taxpayer_name as low-confidence todo (no
      // combined-name fact); concatenate first + last. Same pattern as
      // Schedule CA's header.name.
      "0.header.taxpayer_name": (_, info) =>
        info.taxpayerFirstName && info.taxpayerLastName
          ? `${info.taxpayerFirstName} ${info.taxpayerLastName}`
          : undefined,
      "1.header.taxpayer_name": (_, info) =>
        info.taxpayerFirstName && info.taxpayerLastName
          ? `${info.taxpayerFirstName} ${info.taxpayerLastName}`
          : undefined,
      // MANUAL EDIT: Box A checked when there's at least one short-term
      // trade reported on a 1099-B with basis reported to the IRS
      // (Alejandro's NVDA case). When no short-term trades exist (Alex),
      // the array is empty and this returns undefined → checkbox stays
      // blank.
      "0.part1.box_a_short_term_basis_reported": (_, info) =>
        (info.shortTermTrades?.length ?? 0) > 0 ? true : undefined,
      // MANUAL EDIT: Box D — long-term equivalent of Box A.
      "1.part2.box_d_long_term_basis_reported": (_, info) =>
        (info.longTermTrades?.length ?? 0) > 0 ? true : undefined,
      // MANUAL EDIT: Part I row 1 — first short-term trade. Format
      // description as "<quantity> sh <description>" matching the IRS
      // form example "100 sh. XYZ Co."
      "0.part1.row1_description": (_, info) => {
        const t = info.shortTermTrades?.[0];
        return t ? `${t.quantity} sh ${t.description}` : undefined;
      },
      "0.part1.row1_date_acquired": (_, info) =>
        info.shortTermTrades?.[0]?.dateAcquired,
      "0.part1.row1_date_sold": (_, info) =>
        info.shortTermTrades?.[0]?.dateSold,
      "0.part1.row1_proceeds": (_, info) =>
        info.shortTermTrades?.[0]?.proceeds,
      "0.part1.row1_cost_basis": (_, info) =>
        info.shortTermTrades?.[0]?.costBasis,
      // MANUAL EDIT: Part II row 1 — first long-term trade.
      "1.part2.row1_description": (_, info) => {
        const t = info.longTermTrades?.[0];
        return t ? `${t.quantity} sh ${t.description}` : undefined;
      },
      "1.part2.row1_date_acquired": (_, info) =>
        info.longTermTrades?.[0]?.dateAcquired,
      "1.part2.row1_date_sold": (_, info) =>
        info.longTermTrades?.[0]?.dateSold,
      "1.part2.row1_proceeds": (_, info) =>
        info.longTermTrades?.[0]?.proceeds,
      "1.part2.row1_cost_basis": (_, info) =>
        info.longTermTrades?.[0]?.costBasis,
      // MANUAL EDIT: AI emitted gain_loss formulas for Part II rows 2–11
      // but skipped row 1. Same `d − e + g` formula as the others.
      "1.part2.row1_gain_loss": (f) => rowGainLoss(f["1.part2.row1_proceeds"], f["1.part2.row1_cost_basis"], f["1.part2.row1_adjustment_amount"]),
      // Direct 1-to-1 read of taxpayer SSN from identity facts.
      "0.header.ssn": (_, info) => info.taxpayerSSN,
      // Column (h) = column (d) − column (e) + column (g) per IRS instructions.
      "0.part1.row1_gain_loss": (f) => rowGainLoss(f["0.part1.row1_proceeds"], f["0.part1.row1_cost_basis"], f["0.part1.row1_adjustment_amount"]),
      // Column (h) = column (d) − column (e) + column (g) per IRS Form 8949 instructions.
      "0.part1.row2_gain_loss": (f) => rowGainLoss(f["0.part1.row2_proceeds"], f["0.part1.row2_cost_basis"], f["0.part1.row2_adjustment_amount"]),
      // Column (h) = column (d) − column (e) + column (g) per IRS Form 8949 instructions.
      "0.part1.row3_gain_loss": (f) => rowGainLoss(f["0.part1.row3_proceeds"], f["0.part1.row3_cost_basis"], f["0.part1.row3_adjustment_amount"]),
      // Column (h) = column (d) − column (e) + column (g) per IRS Form 8949 instructions; all three source fields are in this form's inventory.
      "0.part1.row4_gain_loss": (f) => rowGainLoss(f["0.part1.row4_proceeds"], f["0.part1.row4_cost_basis"], f["0.part1.row4_adjustment_amount"]),
      // Computed as proceeds minus cost basis plus any adjustment amount for short-term trade row 5.
      "0.part1.row5_gain_loss": (f) => rowGainLoss(f["0.part1.row5_proceeds"], f["0.part1.row5_cost_basis"], f["0.part1.row5_adjustment_amount"]),
      // Computes row 6 gain/(loss) as proceeds minus cost basis plus any adjustment, per IRS Form 8949 column (h) formula.
      "0.part1.row6_gain_loss": (f) => rowGainLoss(f["0.part1.row6_proceeds"], f["0.part1.row6_cost_basis"], f["0.part1.row6_adjustment_amount"]),
      // Column h = column d minus column e plus column g, per IRS Form 8949 instructions.
      "0.part1.row7_gain_loss": (f) => rowGainLoss(f["0.part1.row7_proceeds"], f["0.part1.row7_cost_basis"], f["0.part1.row7_adjustment_amount"]),
      // Column h = column d minus column e plus column g per IRS instructions.
      "0.part1.row8_gain_loss": (f) => rowGainLoss(f["0.part1.row8_proceeds"], f["0.part1.row8_cost_basis"], f["0.part1.row8_adjustment_amount"]),
      // Column h = column d minus column e plus column g per IRS instructions.
      "0.part1.row9_gain_loss": (f) => rowGainLoss(f["0.part1.row9_proceeds"], f["0.part1.row9_cost_basis"], f["0.part1.row9_adjustment_amount"]),
      // Computes row 10 gain/(loss) as proceeds minus cost basis plus any adjustment amount.
      "0.part1.row10_gain_loss": (f) => rowGainLoss(f["0.part1.row10_proceeds"], f["0.part1.row10_cost_basis"], f["0.part1.row10_adjustment_amount"]),
      // Column (h) = column (d) − column (e) + column (g), the standard IRS Form 8949 gain/loss formula.
      "0.part1.row11_gain_loss": (f) => rowGainLoss(f["0.part1.row11_proceeds"], f["0.part1.row11_cost_basis"], f["0.part1.row11_adjustment_amount"]),
      // Sum of proceeds across all 11 Part I rows for the column (d) total.
      "0.part1.totals_proceeds": (f) => sum(f["0.part1.row1_proceeds"], f["0.part1.row2_proceeds"], f["0.part1.row3_proceeds"], f["0.part1.row4_proceeds"], f["0.part1.row5_proceeds"], f["0.part1.row6_proceeds"], f["0.part1.row7_proceeds"], f["0.part1.row8_proceeds"], f["0.part1.row9_proceeds"], f["0.part1.row10_proceeds"], f["0.part1.row11_proceeds"]),
      // Sum of cost bases across all 11 Part I rows for the column (e) total.
      "0.part1.totals_cost_basis": (f) => sum(f["0.part1.row1_cost_basis"], f["0.part1.row2_cost_basis"], f["0.part1.row3_cost_basis"], f["0.part1.row4_cost_basis"], f["0.part1.row5_cost_basis"], f["0.part1.row6_cost_basis"], f["0.part1.row7_cost_basis"], f["0.part1.row8_cost_basis"], f["0.part1.row9_cost_basis"], f["0.part1.row10_cost_basis"], f["0.part1.row11_cost_basis"]),
      // Sum of adjustment amounts across all 11 Part I rows for the column (g) total.
      "0.part1.totals_adjustment_amount": (f) => sum(f["0.part1.row1_adjustment_amount"], f["0.part1.row2_adjustment_amount"], f["0.part1.row3_adjustment_amount"], f["0.part1.row4_adjustment_amount"], f["0.part1.row5_adjustment_amount"], f["0.part1.row6_adjustment_amount"], f["0.part1.row7_adjustment_amount"], f["0.part1.row8_adjustment_amount"], f["0.part1.row9_adjustment_amount"], f["0.part1.row10_adjustment_amount"], f["0.part1.row11_adjustment_amount"]),
      // Sum of gain/loss across all 11 Part I rows for the column (h) total; feeds Schedule D line 1b/3/etc.
      "0.part1.totals_gain_loss": (f) => sum(f["0.part1.row1_gain_loss"], f["0.part1.row2_gain_loss"], f["0.part1.row3_gain_loss"], f["0.part1.row4_gain_loss"], f["0.part1.row5_gain_loss"], f["0.part1.row6_gain_loss"], f["0.part1.row7_gain_loss"], f["0.part1.row8_gain_loss"], f["0.part1.row9_gain_loss"], f["0.part1.row10_gain_loss"], f["0.part1.row11_gain_loss"]),
      // The IRS notes SSN is not required if shown on other side; binding as optional so it populates when available but doesn't block if omitted.
      "1.header.ssn": (_, info) => info.taxpayerSSN,
      // Column (h) = column (d) − column (e) + column (g) per IRS Form 8949 instructions.
      "1.part2.row2_gain_loss": (f) => rowGainLoss(f["1.part2.row2_proceeds"], f["1.part2.row2_cost_basis"], f["1.part2.row2_adjustment_amount"]),
      // IRS instructions: column (h) = column (d) − column (e) + column (g).
      "1.part2.row3_gain_loss": (f) => rowGainLoss(f["1.part2.row3_proceeds"], f["1.part2.row3_cost_basis"], f["1.part2.row3_adjustment_amount"]),
      // Column h = column d minus column e plus column g, per IRS Form 8949 instructions.
      "1.part2.row7_gain_loss": (f) => rowGainLoss(f["1.part2.row7_proceeds"], f["1.part2.row7_cost_basis"], f["1.part2.row7_adjustment_amount"]),
      // Column (h) gain or loss for Part II row 8: proceeds minus cost basis plus any adjustment, per IRS instructions.
      "1.part2.row8_gain_loss": (f) => rowGainLoss(f["1.part2.row8_proceeds"], f["1.part2.row8_cost_basis"], f["1.part2.row8_adjustment_amount"]),
      // Column (h) gain or loss for Part II row 9: proceeds minus cost basis plus any adjustment, per IRS instructions.
      "1.part2.row9_gain_loss": (f) => rowGainLoss(f["1.part2.row9_proceeds"], f["1.part2.row9_cost_basis"], f["1.part2.row9_adjustment_amount"]),
      // Computes gain/(loss) for long-term Part II row 10 as proceeds minus cost basis plus any adjustment.
      "1.part2.row10_gain_loss": (f) => rowGainLoss(f["1.part2.row10_proceeds"], f["1.part2.row10_cost_basis"], f["1.part2.row10_adjustment_amount"]),
      // Row 11 gain/loss computed as proceeds minus cost basis plus any adjustment, per IRS Form 8949 column (h) formula.
      "1.part2.row11_gain_loss": (f) => rowGainLoss(f["1.part2.row11_proceeds"], f["1.part2.row11_cost_basis"], f["1.part2.row11_adjustment_amount"]),
      // Part II totals column (d): sum of proceeds from all 11 long-term transaction rows.
      "1.part2.totals_proceeds": (f) => sum(f["1.part2.row1_proceeds"], f["1.part2.row2_proceeds"], f["1.part2.row3_proceeds"], f["1.part2.row4_proceeds"], f["1.part2.row5_proceeds"], f["1.part2.row6_proceeds"], f["1.part2.row7_proceeds"], f["1.part2.row8_proceeds"], f["1.part2.row9_proceeds"], f["1.part2.row10_proceeds"], f["1.part2.row11_proceeds"]),
      // Part II totals column (e): sum of cost basis from all 11 long-term transaction rows.
      "1.part2.totals_cost_basis": (f) => sum(f["1.part2.row1_cost_basis"], f["1.part2.row2_cost_basis"], f["1.part2.row3_cost_basis"], f["1.part2.row4_cost_basis"], f["1.part2.row5_cost_basis"], f["1.part2.row6_cost_basis"], f["1.part2.row7_cost_basis"], f["1.part2.row8_cost_basis"], f["1.part2.row9_cost_basis"], f["1.part2.row10_cost_basis"], f["1.part2.row11_cost_basis"]),
      // Part II totals column (g): sum of adjustment amounts from all 11 long-term transaction rows.
      "1.part2.totals_adjustment_amount": (f) => sum(f["1.part2.row1_adjustment_amount"], f["1.part2.row2_adjustment_amount"], f["1.part2.row3_adjustment_amount"], f["1.part2.row4_adjustment_amount"], f["1.part2.row5_adjustment_amount"], f["1.part2.row6_adjustment_amount"], f["1.part2.row7_adjustment_amount"], f["1.part2.row8_adjustment_amount"], f["1.part2.row9_adjustment_amount"], f["1.part2.row10_adjustment_amount"], f["1.part2.row11_adjustment_amount"]),
      // Part II totals column (h): net gain or loss from all 11 long-term rows; this total carries to Schedule D long-term lines.
      "1.part2.totals_gain_loss": (f) => sum(f["1.part2.row1_gain_loss"], f["1.part2.row2_gain_loss"], f["1.part2.row3_gain_loss"], f["1.part2.row4_gain_loss"], f["1.part2.row5_gain_loss"], f["1.part2.row6_gain_loss"], f["1.part2.row7_gain_loss"], f["1.part2.row8_gain_loss"], f["1.part2.row9_gain_loss"], f["1.part2.row10_gain_loss"], f["1.part2.row11_gain_loss"]),
    },

    unsupported: {
      "0.part1.box_b_short_term_basis_not_reported": "Box B is checked when this page contains short-term 1099-B transactions with basis NOT reported to IRS. Same page-level box aggregation gap as box A.",
      "0.part1.box_c_short_term_not_on_1099b": "Box C is checked when this page contains short-term non-digital transactions not on Form 1099-B or 1099-DA. Same page-level box aggregation gap as box A.",
      "0.part1.box_g_short_term_1099da_basis_reported": "Box G is checked when this page contains short-term 1099-DA digital asset transactions with basis reported to IRS. Same page-level box aggregation gap as box A; also no digital asset ingestion path exists yet.",
      "0.part1.box_h_short_term_1099da_basis_not_reported": "Box H is checked when this page contains short-term 1099-DA digital asset transactions with basis NOT reported to IRS. Same page-level aggregation and digital asset ingestion gaps.",
      "0.part1.box_i_short_term_digital_not_on_1099da": "Box I is checked when this page contains short-term digital asset transactions not on Form 1099-DA or 1099-B. Same page-level aggregation and digital asset ingestion gaps.",
      "0.part1.row1_adjustment_code": "Adjustment codes (column f) require per-trade logic (wash sales, related-party sales, QOF deferrals, etc.) — no adjustment-code fact or decision ingested yet.",
      "0.part1.row1_adjustment_amount": "Adjustment amounts (column g) depend on adjustment codes and special situations (wash sales, etc.) — no adjustment-amount fact ingested yet.",
      "0.part1.row2_adjustment_code": "Adjustment codes (column f) require per-trade logic comparing reported vs. actual basis, wash sales, and other IRS-defined adjustments — no ingestion path for these correction codes yet.",
      "0.part1.row2_adjustment_amount": "Adjustment amount (column g) is determined by the same per-trade correction logic as column (f) codes — no ingestion or computation path yet.",
      "0.part1.row3_adjustment_code": "Adjustment codes (column f) require per-trade logic comparing reported vs. actual basis, wash sales, and other IRS-defined adjustments — no ingestion path for these correction codes yet.",
      "0.part1.row3_adjustment_amount": "Per-trade adjustment amounts (e.g. wash sale disallowed loss, selling expense corrections) require adjustment fact ingestion we haven't built yet. No fact key exists for trade-level adjustments.",
      "0.part1.row4_description": "Row 4 maps to the 4th short-term trade slot. The trade fact schema (account.{slug}.trade.{tradeId}) does not include a pre-formatted 'description of property' string field; description rendering requires a template engine that combines ticker symbol, share count, etc. No ingestion path exists yet.",
      "0.part1.row4_date_acquired": "Row 4 is the 4th short-term trade slot. The engine currently lacks a mechanism to address the Nth trade by position across all short-term trades assigned to box A/B/C/G/H/I. Per-row slot assignment requires a trade-ordering/allocation engine not yet built.",
      "0.part1.row4_date_sold": "Same as row4_date_acquired — positional trade-slot assignment for the 4th short-term trade is not yet implemented.",
      "0.part1.row4_proceeds": "Positional trade-slot assignment for the 4th short-term trade row is not yet implemented; no mechanism to address the Nth trade by slot position.",
      "0.part1.row4_cost_basis": "Positional trade-slot assignment for the 4th short-term trade row is not yet implemented; no mechanism to address the Nth trade's costBasis by slot position.",
      "0.part1.row4_adjustment_code": "Adjustment code derivation (W for wash sale, B for basis correction, etc.) requires per-trade adjustment logic and ingestion not yet built. Additionally, row-4 slot assignment is not yet implemented.",
      "0.part1.row4_adjustment_amount": "Per-trade adjustment amounts require adjustment fact ingestion not yet built. Additionally, row-4 slot assignment is not yet implemented.",
      "0.part1.row5_adjustment_code": "Adjustment codes (column f) require rule-based logic to determine wash sale, exclusion, or other IRS codes — no adjustment-code ingestion or decision path exists yet for per-trade rows.",
      "0.part1.row5_adjustment_amount": "Adjustment amounts (column g) depend on wash sale disallowed loss or other per-trade adjustments — no ingestion path exists for these yet.",
      "0.part1.row6_adjustment_code": "Adjustment codes (column f) require per-trade wash-sale, QOF, or other adjustment logic not yet modeled in fact ingestion. No scenario built yet for per-row code determination.",
      "0.part1.row6_adjustment_amount": "Adjustment amounts (column g) require wash-sale disallowed loss, QOF deferral, or other adjustment ingestion not yet modeled. No scenario built yet for per-row adjustments.",
      "0.part1.row7_adjustment_code": "Adjustment codes (column f) are situational IRS codes (e.g. B, W, E, L, M, O) that depend on specific trade circumstances not yet modeled in our fact/decision schema. No ingestion path exists for per-trade adjustment codes.",
      "0.part1.row7_adjustment_amount": "Adjustment amounts (column g) depend on adjustment codes and specific trade circumstances (wash sales, selling expenses, etc.) not yet modeled in our fact/decision schema.",
      "0.part1.row8_adjustment_code": "Adjustment codes (column f) are situational IRS codes that depend on specific trade circumstances not yet modeled in our fact/decision schema. No ingestion path exists for per-trade adjustment codes.",
      "0.part1.row11_adjustment_code": "Adjustment codes (wash sale, exclusion, etc.) require logic we haven't modeled yet — no ingestion path for per-trade adjustment codes in the current fact schema.",
      "0.part1.row11_adjustment_amount": "Adjustment amounts (wash sale disallowed loss, etc.) require per-trade adjustment logic not yet modeled in the fact schema.",
      "1.part2.box_e_long_term_basis_not_reported": "Box E checked when this Part II page contains long-term 1099-B transactions where basis was NOT reported to IRS. Requires per-page/per-box transaction routing logic not yet modeled.",
      "1.part2.box_f_long_term_not_on_1099b": "Box F checked when this Part II page contains long-term non-digital transactions not reported on 1099-B or 1099-DA. Requires per-page/per-box transaction routing logic not yet modeled.",
      "1.part2.box_j_long_term_1099da_basis_reported": "Box J checked when this Part II page contains long-term 1099-DA digital asset transactions with basis reported to IRS. No 1099-DA ingestion scenario built yet.",
      "1.part2.box_k_long_term_1099da_basis_not_reported": "Box K checked when this Part II page contains long-term 1099-DA digital asset transactions where basis was NOT reported to IRS. No 1099-DA ingestion scenario built yet.",
      "1.part2.box_l_long_term_digital_not_on_1099da": "Box L checked when this Part II page contains long-term digital asset transactions not reported on 1099-DA or 1099-B. No digital asset transaction ingestion scenario built yet.",
      "1.part2.row1_adjustment_code": "Per-row adjustment code requires a dynamic trade-to-row assignment engine. The adjustment code (e.g. 'W', 'B') is trade-specific and derived from basis-reporting flags on the 1099-B, but no rule maps a specific trade's code to a fixed row slot.",
      "1.part2.row1_adjustment_amount": "Per-row adjustment amount requires a dynamic trade-to-row assignment engine. The adjustment amount is trade-specific and no rule maps a specific trade's adjustment to a fixed row slot in Part II.",
      "1.part2.row2_description": "Per-row trade description requires a dynamic trade-to-row assignment engine. No static fact key maps 'description of property for Part II row 2' — the engine must assign long-term trades to rows based on decisions.trade.{tradeId}.form_8949_box.",
      "1.part2.row2_date_acquired": "Per-row date acquired requires a dynamic trade-to-row assignment engine. No static fact key maps 'date acquired for Part II row 2' — the engine must assign long-term trades to rows based on decisions.trade.{tradeId}.form_8949_box.",
      "1.part2.row2_date_sold": "Per-row date sold requires a dynamic trade-to-row assignment engine. No static fact key maps 'date sold for Part II row 2' — the engine must assign long-term trades to rows based on decisions.trade.{tradeId}.form_8949_box.",
      "1.part2.row2_proceeds": "Per-row proceeds requires a dynamic trade-to-row assignment engine. No static fact key maps 'proceeds for Part II row 2' — the engine must assign long-term trades to rows based on decisions.trade.{tradeId}.form_8949_box.",
      "1.part2.row2_cost_basis": "Per-row trade slot assignment not modeled — trades are keyed by tradeId in facts but form rows are positional; no mechanism to assign trade N to row 2 of Part II yet.",
      "1.part2.row2_adjustment_code": "Adjustment codes (wash sale, etc.) require per-trade adjustment modeling not yet ingested; also depends on row→trade slot assignment which is not yet built.",
      "1.part2.row2_adjustment_amount": "Column (g) adjustment amounts (wash sale disallowed loss, etc.) require per-trade adjustment ingestion not yet built; also depends on row→trade slot assignment.",
      "1.part2.row3_description": "Per-row trade slot assignment not modeled — trades are keyed by tradeId in facts but form rows are positional; no mechanism to assign trade N to row 3 of Part II yet.",
      "1.part2.row3_date_acquired": "Per-row trade slot assignment not modeled — no mechanism to assign trade N to row 3 of Part II yet.",
      "1.part2.row3_date_sold": "Per-row trade slot assignment not modeled — no mechanism to assign trade N to row 3 of Part II yet.",
      "1.part2.row3_proceeds": "Per-row trade slot assignment not modeled — no mechanism to assign trade N to row 3 of Part II yet.",
      "1.part2.row3_cost_basis": "Per-row trade slot assignment not modeled — no mechanism to assign trade N to row 3 of Part II yet.",
      "1.part2.row3_adjustment_code": "Adjustment codes require per-trade adjustment modeling not yet ingested; also depends on row→trade slot assignment which is not yet built.",
      "1.part2.row3_adjustment_amount": "Adjustment amounts require per-trade adjustment logic (wash sales, exclusions, etc.) not yet modeled in the engine — no adjustment-amount fact path exists.",
      "1.part2.row4_description": "Row 4 is an overflow row; no 4th long-term trade fact slot is modeled yet — engine supports trades mapped to rows 1–3 via the current scenario.",
      "1.part2.row4_date_acquired": "Row 4 overflow — no 4th long-term trade fact slot modeled yet.",
      "1.part2.row4_date_sold": "Row 4 overflow — no 4th long-term trade fact slot modeled yet.",
      "1.part2.row4_proceeds": "Row 4 overflow — no 4th long-term trade fact slot modeled yet.",
      "1.part2.row4_cost_basis": "Row 4 overflow — no 4th long-term trade fact slot modeled yet.",
      "1.part2.row4_adjustment_code": "Row 4 overflow — no 4th long-term trade fact slot modeled yet; adjustment codes also require per-trade adjustment scenario.",
      "1.part2.row4_adjustment_amount": "Row 4 overflow — no 4th long-term trade fact slot modeled yet; adjustment amounts also require per-trade adjustment scenario.",
      "1.part2.row4_gain_loss": "Row 4 overflow — no 4th long-term trade fact slot modeled yet; gain/loss cannot be computed without upstream proceeds and cost basis fields.",
      "1.part2.row5_description": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_date_acquired": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_date_sold": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_proceeds": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_cost_basis": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_adjustment_code": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_adjustment_amount": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row5_gain_loss": "Per-trade row assignment (which trade maps to Part II row 5) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row6_description": "Per-trade row assignment (which trade maps to Part II row 6) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row6_date_acquired": "Per-trade row assignment (which trade maps to Part II row 6) requires a row-allocation engine that slots trades into numbered rows by box type and index. No row-slotting mechanism exists yet.",
      "1.part2.row7_adjustment_code": "Adjustment codes (column f) require per-trade adjustment logic (wash sale, QOF deferral, etc.) that we have no ingestion path or worked scenario for yet.",
      "1.part2.row7_adjustment_amount": "Adjustment amounts (column g) depend on per-trade adjustment codes and scenarios (wash sale, QOF, etc.) not yet modeled in fact ingestion.",
      "1.part2.row8_adjustment_code": "Adjustment codes (column f) require per-trade adjustment logic (wash sale, QOF deferral, etc.) that we have no ingestion path or worked scenario for yet.",
    },

    todos: {
      "0.part1.row2_description": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row2_date_acquired": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row2_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row2_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row2_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row3_description": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row3_date_acquired": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row3_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row3_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row3_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row5_description": "confidence=medium: Description of property for short-term trade row 5, sourced from the 5th trade fact's description field.",
      "0.part1.row5_date_acquired": "confidence=medium: Date acquired for short-term trade row 5, sourced from the 5th trade fact's dateAcquired field.",
      "0.part1.row5_date_sold": "confidence=medium: Date sold for short-term trade row 5, sourced from the 5th trade fact's dateSold field.",
      "0.part1.row5_proceeds": "confidence=medium: Proceeds (sales price) for short-term trade row 5, sourced from the 5th trade fact's proceeds field.",
      "0.part1.row5_cost_basis": "confidence=medium: Cost or other basis for short-term trade row 5, sourced from the 5th trade fact's costBasis field.",
      "0.part1.row6_description": "confidence=medium: Description of property for short-term trade row 6, sourced from the 6th trade fact's description field.",
      "0.part1.row6_date_acquired": "confidence=medium: Date acquired for short-term trade row 6, sourced from the 6th trade fact's dateAcquired field.",
      "0.part1.row6_date_sold": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row6_proceeds": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row6_cost_basis": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row7_description": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row7_date_acquired": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row7_date_sold": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row7_proceeds": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row7_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row8_description": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row8_date_acquired": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row8_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row8_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row8_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row8_adjustment_amount": "confidence=medium: Per-trade adjustment amount (column g) sourced from the trade fact; optional because most trades have no adjustment.",
      "0.part1.row9_description": "confidence=medium: Per-trade description of property (column a) sourced from the trade fact.",
      "0.part1.row9_date_acquired": "confidence=medium: Per-trade date acquired (column b) sourced from the trade fact.",
      "0.part1.row9_date_sold": "confidence=medium: Per-trade date sold (column c) sourced from the trade fact.",
      "0.part1.row9_proceeds": "confidence=medium: Per-trade proceeds / sales price (column d) sourced from the trade fact.",
      "0.part1.row9_cost_basis": "confidence=medium: Per-trade cost or other basis (column e) sourced from the trade fact.",
      "0.part1.row9_adjustment_code": "confidence=medium: Per-trade adjustment code (column f) driven by the AI decision for the trade's box assignment / adjustment code.",
      "0.part1.row9_adjustment_amount": "confidence=medium: Per-trade adjustment amount (column g) sourced from the trade fact; optional because most trades have no adjustment.",
      "0.part1.row10_description": "confidence=medium: Per-trade description of property (e.g. ticker + share count) from the 10th short-term trade fact.",
      "0.part1.row10_date_acquired": "confidence=medium: Acquisition date for the 10th short-term trade from the trade fact.",
      "0.part1.row10_date_sold": "confidence=medium: Sale/disposition date for the 10th short-term trade from the trade fact.",
      "0.part1.row10_proceeds": "confidence=medium: Sale proceeds for the 10th short-term trade from the trade fact.",
      "0.part1.row10_cost_basis": "confidence=medium: Cost or other basis for the 10th short-term trade from the trade fact.",
      "0.part1.row10_adjustment_code": "confidence=medium: Adjustment code(s) for the 10th short-term trade row, determined by the AI decision engine based on trade characteristics.",
      "0.part1.row10_adjustment_amount": "confidence=medium: Adjustment amount for the 10th short-term trade row; blank when no adjustment applies.",
      "0.part1.row11_description": "confidence=medium: Per-trade description of property for the 11th short-term trade fact.",
      "0.part1.row11_date_acquired": "confidence=medium: Acquisition date for the 11th short-term trade from the trade fact.",
      "0.part1.row11_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row11_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "0.part1.row11_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row6_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row6_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row6_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row6_adjustment_code": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.adjustmentCode\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row6_adjustment_amount": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.adjustmentAmount\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row6_gain_loss": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.gainLoss\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row7_description": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row7_date_acquired": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row7_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row7_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row7_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row8_description": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row8_date_acquired": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row8_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row8_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row8_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row8_adjustment_amount": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.adjustmentAmount\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row9_description": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row9_date_acquired": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row9_date_sold": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row9_proceeds": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row9_cost_basis": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row9_adjustment_code": "confidence=medium: Adjustment code(s) (column f) for long-term Part II row 9; driven by the per-trade form_8949_box decision which encodes required adjustment codes.",
      "1.part2.row9_adjustment_amount": "lookupFact: no FilingInfo slot for fact \"account.{slug}.trade.{tradeId}.adjustmentAmount\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row10_description": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row10_date_acquired": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row10_date_sold": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.dateSold\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row10_proceeds": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.proceeds\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row10_cost_basis": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.costBasis\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row10_adjustment_code": "confidence=medium: Adjustment code(s) for long-term Part II row 10 driven by per-trade form_8949_box decision (e.g. wash sale code W, etc.).",
      "1.part2.row10_adjustment_amount": "confidence=medium: Adjustment amount for long-term Part II row 10, sourced from per-trade fact (e.g. wash sale disallowed loss).",
      "1.part2.row11_description": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.description\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row11_date_acquired": "lookupFact: no FilingInfo slot for fact \"investment_income.account.{slug}.trade.{tradeId}.dateAcquired\". Add the slot to BaseFilingInfo / <Form>FilingInfo and map it in renderBindings.FACT_TO_SLOT.",
      "1.part2.row11_date_sold": "confidence=medium: Date sold for the 11th long-term trade (0-indexed as trade_long_10) from investment income facts.",
      "1.part2.row11_proceeds": "confidence=medium: Sale proceeds for the 11th long-term trade from investment income facts.",
      "1.part2.row11_cost_basis": "confidence=medium: Cost basis for the 11th long-term trade from investment income facts.",
      "1.part2.row11_adjustment_code": "confidence=medium: Adjustment code(s) for the 11th long-term trade; optional as most trades have no adjustment.",
      "1.part2.row11_adjustment_amount": "confidence=medium: Adjustment amount for the 11th long-term trade; optional as most trades have no adjustment.",
    },

  });
}

// Summary: 28 binding(s), 94 todo(s), 78 unsupported, 0 unbound.
// Confidence: 165 high, 32 medium, 3 low.
