// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/federal/8949/catalog.json
// Form: Sales and Other Dispositions of Capital Assets (form-8949, tax year 2025)
// Fields: 200
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface Form8949 {
  /**  Name(s) shown on return */
  "0.header.taxpayer_name": string | undefined;
  /**  Social security number or taxpayer identification number */
  "0.header.ssn": string | undefined;
  /**  (A) Short-term transactions reported on Form(s) 1099-B showing basis was reported to the IRS */
  "0.part1.box_a_short_term_basis_reported": boolean | undefined;
  /**  (B) Short-term transactions reported on Form(s) 1099-B showing basis was not reported to the IRS */
  "0.part1.box_b_short_term_basis_not_reported": boolean | undefined;
  /**  (C) Short-term transactions, other than digital asset transactions, not reported to you on Form 1099-B or Form 1099-DA */
  "0.part1.box_c_short_term_not_on_1099b": boolean | undefined;
  /**  (G) Short-term transactions reported on Form(s) 1099-DA showing basis was reported to the IRS */
  "0.part1.box_g_short_term_1099da_basis_reported": boolean | undefined;
  /**  (H) Short-term transactions reported on Form(s) 1099-DA showing basis was not reported to the IRS */
  "0.part1.box_h_short_term_1099da_basis_not_reported": boolean | undefined;
  /**  (I) Short-term digital asset transactions not reported to you on Form 1099-DA or Form 1099-B */
  "0.part1.box_i_short_term_digital_not_on_1099da": boolean | undefined;
  /**  Row 1 — (a) Description of property */
  "0.part1.row1_description": string | undefined;
  /**  Row 1 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row1_date_acquired": string | undefined;
  /**  Row 1 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row1_date_sold": string | undefined;
  /**  Row 1 — (d) Proceeds (sales price) */
  "0.part1.row1_proceeds": number | undefined;
  /**  Row 1 — (e) Cost or other basis */
  "0.part1.row1_cost_basis": number | undefined;
  /**  Row 1 — (f) Code(s) from instructions */
  "0.part1.row1_adjustment_code": string | undefined;
  /**  Row 1 — (g) Amount of adjustment */
  "0.part1.row1_adjustment_amount": number | undefined;
  /**  Row 1 — (h) Gain or (loss) */
  "0.part1.row1_gain_loss": number | undefined;
  /**  Row 2 — (a) Description of property */
  "0.part1.row2_description": string | undefined;
  /**  Row 2 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row2_date_acquired": string | undefined;
  /**  Row 2 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row2_date_sold": string | undefined;
  /**  Row 2 — (d) Proceeds (sales price) */
  "0.part1.row2_proceeds": number | undefined;
  /**  Row 2 — (e) Cost or other basis */
  "0.part1.row2_cost_basis": number | undefined;
  /**  Row 2 — (f) Code(s) from instructions */
  "0.part1.row2_adjustment_code": string | undefined;
  /**  Row 2 — (g) Amount of adjustment */
  "0.part1.row2_adjustment_amount": number | undefined;
  /**  Row 2 — (h) Gain or (loss) */
  "0.part1.row2_gain_loss": number | undefined;
  /**  Row 3 — (a) Description of property */
  "0.part1.row3_description": string | undefined;
  /**  Row 3 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row3_date_acquired": string | undefined;
  /**  Row 3 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row3_date_sold": string | undefined;
  /**  Row 3 — (d) Proceeds (sales price) */
  "0.part1.row3_proceeds": number | undefined;
  /**  Row 3 — (e) Cost or other basis */
  "0.part1.row3_cost_basis": number | undefined;
  /**  Row 3 — (f) Code(s) from instructions */
  "0.part1.row3_adjustment_code": string | undefined;
  /**  Row 3 — (g) Amount of adjustment */
  "0.part1.row3_adjustment_amount": number | undefined;
  /**  Row 3 — (h) Gain or (loss) */
  "0.part1.row3_gain_loss": number | undefined;
  /**  Row 4 — (a) Description of property */
  "0.part1.row4_description": string | undefined;
  /**  Row 4 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row4_date_acquired": string | undefined;
  /**  Row 4 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row4_date_sold": string | undefined;
  /**  Row 4 — (d) Proceeds (sales price) */
  "0.part1.row4_proceeds": number | undefined;
  /**  Row 4 — (e) Cost or other basis */
  "0.part1.row4_cost_basis": number | undefined;
  /**  Row 4 — (f) Code(s) from instructions */
  "0.part1.row4_adjustment_code": string | undefined;
  /**  Row 4 — (g) Amount of adjustment */
  "0.part1.row4_adjustment_amount": number | undefined;
  /**  Row 4 — (h) Gain or (loss) */
  "0.part1.row4_gain_loss": number | undefined;
  /**  Row 5 — (a) Description of property */
  "0.part1.row5_description": string | undefined;
  /**  Row 5 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row5_date_acquired": string | undefined;
  /**  Row 5 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row5_date_sold": string | undefined;
  /**  Row 5 — (d) Proceeds (sales price) */
  "0.part1.row5_proceeds": number | undefined;
  /**  Row 5 — (e) Cost or other basis */
  "0.part1.row5_cost_basis": number | undefined;
  /**  Row 5 — (f) Code(s) from instructions */
  "0.part1.row5_adjustment_code": string | undefined;
  /**  Row 5 — (g) Amount of adjustment */
  "0.part1.row5_adjustment_amount": number | undefined;
  /**  Row 5 — (h) Gain or (loss) */
  "0.part1.row5_gain_loss": number | undefined;
  /**  Row 6 — (a) Description of property */
  "0.part1.row6_description": string | undefined;
  /**  Row 6 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row6_date_acquired": string | undefined;
  /**  Row 6 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row6_date_sold": string | undefined;
  /**  Row 6 — (d) Proceeds (sales price) */
  "0.part1.row6_proceeds": number | undefined;
  /**  Row 6 — (e) Cost or other basis */
  "0.part1.row6_cost_basis": number | undefined;
  /**  Row 6 — (f) Code(s) from instructions */
  "0.part1.row6_adjustment_code": string | undefined;
  /**  Row 6 — (g) Amount of adjustment */
  "0.part1.row6_adjustment_amount": number | undefined;
  /**  Row 6 — (h) Gain or (loss) */
  "0.part1.row6_gain_loss": number | undefined;
  /**  Row 7 — (a) Description of property */
  "0.part1.row7_description": string | undefined;
  /**  Row 7 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row7_date_acquired": string | undefined;
  /**  Row 7 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row7_date_sold": string | undefined;
  /**  Row 7 — (d) Proceeds (sales price) */
  "0.part1.row7_proceeds": number | undefined;
  /**  Row 7 — (e) Cost or other basis */
  "0.part1.row7_cost_basis": number | undefined;
  /**  Row 7 — (f) Code(s) from instructions */
  "0.part1.row7_adjustment_code": string | undefined;
  /**  Row 7 — (g) Amount of adjustment */
  "0.part1.row7_adjustment_amount": number | undefined;
  /**  Row 7 — (h) Gain or (loss) */
  "0.part1.row7_gain_loss": number | undefined;
  /**  Row 8 — (a) Description of property */
  "0.part1.row8_description": string | undefined;
  /**  Row 8 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row8_date_acquired": string | undefined;
  /**  Row 8 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row8_date_sold": string | undefined;
  /**  Row 8 — (d) Proceeds (sales price) */
  "0.part1.row8_proceeds": number | undefined;
  /**  Row 8 — (e) Cost or other basis */
  "0.part1.row8_cost_basis": number | undefined;
  /**  Row 8 — (f) Code(s) from instructions */
  "0.part1.row8_adjustment_code": string | undefined;
  /**  Row 8 — (g) Amount of adjustment */
  "0.part1.row8_adjustment_amount": number | undefined;
  /**  Row 8 — (h) Gain or (loss) */
  "0.part1.row8_gain_loss": number | undefined;
  /**  Row 9 — (a) Description of property */
  "0.part1.row9_description": string | undefined;
  /**  Row 9 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row9_date_acquired": string | undefined;
  /**  Row 9 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row9_date_sold": string | undefined;
  /**  Row 9 — (d) Proceeds (sales price) */
  "0.part1.row9_proceeds": number | undefined;
  /**  Row 9 — (e) Cost or other basis */
  "0.part1.row9_cost_basis": number | undefined;
  /**  Row 9 — (f) Code(s) from instructions */
  "0.part1.row9_adjustment_code": string | undefined;
  /**  Row 9 — (g) Amount of adjustment */
  "0.part1.row9_adjustment_amount": number | undefined;
  /**  Row 9 — (h) Gain or (loss) */
  "0.part1.row9_gain_loss": number | undefined;
  /**  Row 10 — (a) Description of property */
  "0.part1.row10_description": string | undefined;
  /**  Row 10 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row10_date_acquired": string | undefined;
  /**  Row 10 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row10_date_sold": string | undefined;
  /**  Row 10 — (d) Proceeds (sales price) */
  "0.part1.row10_proceeds": number | undefined;
  /**  Row 10 — (e) Cost or other basis */
  "0.part1.row10_cost_basis": number | undefined;
  /**  Row 10 — (f) Code(s) from instructions */
  "0.part1.row10_adjustment_code": string | undefined;
  /**  Row 10 — (g) Amount of adjustment */
  "0.part1.row10_adjustment_amount": number | undefined;
  /**  Row 10 — (h) Gain or (loss) */
  "0.part1.row10_gain_loss": number | undefined;
  /**  Row 11 — (a) Description of property */
  "0.part1.row11_description": string | undefined;
  /**  Row 11 — (b) Date acquired (Mo., day, yr.) */
  "0.part1.row11_date_acquired": string | undefined;
  /**  Row 11 — (c) Date sold or disposed of (Mo., day, yr.) */
  "0.part1.row11_date_sold": string | undefined;
  /**  Row 11 — (d) Proceeds (sales price) */
  "0.part1.row11_proceeds": number | undefined;
  /**  Row 11 — (e) Cost or other basis */
  "0.part1.row11_cost_basis": number | undefined;
  /**  Row 11 — (f) Code(s) from instructions */
  "0.part1.row11_adjustment_code": string | undefined;
  /**  Row 11 — (g) Amount of adjustment */
  "0.part1.row11_adjustment_amount": number | undefined;
  /**  Row 11 — (h) Gain or (loss) */
  "0.part1.row11_gain_loss": number | undefined;
  /**  Line 2 Totals — (d) Proceeds (sales price) */
  "0.part1.totals_proceeds": number | undefined;
  /**  Line 2 Totals — (e) Cost or other basis */
  "0.part1.totals_cost_basis": number | undefined;
  /**  Line 2 Totals — (g) Amount of adjustment */
  "0.part1.totals_adjustment_amount": number | undefined;
  /**  Line 2 Totals — (h) Gain or (loss) */
  "0.part1.totals_gain_loss": number | undefined;
  /**  Name(s) shown on return. Name and SSN or taxpayer identification no. not required if shown on other side */
  "1.header.taxpayer_name": string | undefined;
  /**  Social security number or taxpayer identification number */
  "1.header.ssn": string | undefined;
  /**  (D) Long-term transactions reported on Form(s) 1099-B showing basis was reported to the IRS */
  "1.part2.box_d_long_term_basis_reported": boolean | undefined;
  /**  (E) Long-term transactions reported on Form(s) 1099-B showing basis was not reported to the IRS */
  "1.part2.box_e_long_term_basis_not_reported": boolean | undefined;
  /**  (F) Long-term transactions, other than digital asset transactions, not reported to you on Form 1099-B or Form 1099-DA */
  "1.part2.box_f_long_term_not_on_1099b": boolean | undefined;
  /**  (J) Long-term transactions reported on Form(s) 1099-DA showing basis was reported to the IRS */
  "1.part2.box_j_long_term_1099da_basis_reported": boolean | undefined;
  /**  (K) Long-term transactions reported on Form(s) 1099-DA showing basis was not reported to the IRS */
  "1.part2.box_k_long_term_1099da_basis_not_reported": boolean | undefined;
  /**  (L) Long-term digital asset transactions not reported to you on Form 1099-DA or Form 1099-B */
  "1.part2.box_l_long_term_digital_not_on_1099da": boolean | undefined;
  /**  Row 1 — (a) Description of property */
  "1.part2.row1_description": string | undefined;
  /**  Row 1 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row1_date_acquired": string | undefined;
  /**  Row 1 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row1_date_sold": string | undefined;
  /**  Row 1 — (d) Proceeds (sales price) */
  "1.part2.row1_proceeds": number | undefined;
  /**  Row 1 — (e) Cost or other basis */
  "1.part2.row1_cost_basis": number | undefined;
  /**  Row 1 — (f) Code(s) from instructions */
  "1.part2.row1_adjustment_code": string | undefined;
  /**  Row 1 — (g) Amount of adjustment */
  "1.part2.row1_adjustment_amount": number | undefined;
  /**  Row 1 — (h) Gain or (loss) */
  "1.part2.row1_gain_loss": number | undefined;
  /**  Row 2 — (a) Description of property */
  "1.part2.row2_description": string | undefined;
  /**  Row 2 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row2_date_acquired": string | undefined;
  /**  Row 2 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row2_date_sold": string | undefined;
  /**  Row 2 — (d) Proceeds (sales price) */
  "1.part2.row2_proceeds": number | undefined;
  /**  Row 2 — (e) Cost or other basis */
  "1.part2.row2_cost_basis": number | undefined;
  /**  Row 2 — (f) Code(s) from instructions */
  "1.part2.row2_adjustment_code": string | undefined;
  /**  Row 2 — (g) Amount of adjustment */
  "1.part2.row2_adjustment_amount": number | undefined;
  /**  Row 2 — (h) Gain or (loss) */
  "1.part2.row2_gain_loss": number | undefined;
  /**  Row 3 — (a) Description of property */
  "1.part2.row3_description": string | undefined;
  /**  Row 3 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row3_date_acquired": string | undefined;
  /**  Row 3 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row3_date_sold": string | undefined;
  /**  Row 3 — (d) Proceeds (sales price) */
  "1.part2.row3_proceeds": number | undefined;
  /**  Row 3 — (e) Cost or other basis */
  "1.part2.row3_cost_basis": number | undefined;
  /**  Row 3 — (f) Code(s) from instructions */
  "1.part2.row3_adjustment_code": string | undefined;
  /**  Row 3 — (g) Amount of adjustment */
  "1.part2.row3_adjustment_amount": number | undefined;
  /**  Row 3 — (h) Gain or (loss) */
  "1.part2.row3_gain_loss": number | undefined;
  /**  Row 4 — (a) Description of property */
  "1.part2.row4_description": string | undefined;
  /**  Row 4 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row4_date_acquired": string | undefined;
  /**  Row 4 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row4_date_sold": string | undefined;
  /**  Row 4 — (d) Proceeds (sales price) */
  "1.part2.row4_proceeds": number | undefined;
  /**  Row 4 — (e) Cost or other basis */
  "1.part2.row4_cost_basis": number | undefined;
  /**  Row 4 — (f) Code(s) from instructions */
  "1.part2.row4_adjustment_code": string | undefined;
  /**  Row 4 — (g) Amount of adjustment */
  "1.part2.row4_adjustment_amount": number | undefined;
  /**  Row 4 — (h) Gain or (loss) */
  "1.part2.row4_gain_loss": number | undefined;
  /**  Row 5 — (a) Description of property */
  "1.part2.row5_description": string | undefined;
  /**  Row 5 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row5_date_acquired": string | undefined;
  /**  Row 5 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row5_date_sold": string | undefined;
  /**  Row 5 — (d) Proceeds (sales price) */
  "1.part2.row5_proceeds": number | undefined;
  /**  Row 5 — (e) Cost or other basis */
  "1.part2.row5_cost_basis": number | undefined;
  /**  Row 5 — (f) Code(s) from instructions */
  "1.part2.row5_adjustment_code": string | undefined;
  /**  Row 5 — (g) Amount of adjustment */
  "1.part2.row5_adjustment_amount": number | undefined;
  /**  Row 5 — (h) Gain or (loss) */
  "1.part2.row5_gain_loss": number | undefined;
  /**  Row 6 — (a) Description of property */
  "1.part2.row6_description": string | undefined;
  /**  Row 6 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row6_date_acquired": string | undefined;
  /**  Row 6 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row6_date_sold": string | undefined;
  /**  Row 6 — (d) Proceeds (sales price) */
  "1.part2.row6_proceeds": number | undefined;
  /**  Row 6 — (e) Cost or other basis */
  "1.part2.row6_cost_basis": number | undefined;
  /**  Row 6 — (f) Code(s) from instructions */
  "1.part2.row6_adjustment_code": string | undefined;
  /**  Row 6 — (g) Amount of adjustment */
  "1.part2.row6_adjustment_amount": number | undefined;
  /**  Row 6 — (h) Gain or (loss) */
  "1.part2.row6_gain_loss": number | undefined;
  /**  Row 7 — (a) Description of property */
  "1.part2.row7_description": string | undefined;
  /**  Row 7 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row7_date_acquired": string | undefined;
  /**  Row 7 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row7_date_sold": string | undefined;
  /**  Row 7 — (d) Proceeds (sales price) */
  "1.part2.row7_proceeds": number | undefined;
  /**  Row 7 — (e) Cost or other basis */
  "1.part2.row7_cost_basis": number | undefined;
  /**  Row 7 — (f) Code(s) from instructions */
  "1.part2.row7_adjustment_code": string | undefined;
  /**  Row 7 — (g) Amount of adjustment */
  "1.part2.row7_adjustment_amount": number | undefined;
  /**  Row 7 — (h) Gain or (loss) */
  "1.part2.row7_gain_loss": number | undefined;
  /**  Row 8 — (a) Description of property */
  "1.part2.row8_description": string | undefined;
  /**  Row 8 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row8_date_acquired": string | undefined;
  /**  Row 8 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row8_date_sold": string | undefined;
  /**  Row 8 — (d) Proceeds (sales price) */
  "1.part2.row8_proceeds": number | undefined;
  /**  Row 8 — (e) Cost or other basis */
  "1.part2.row8_cost_basis": number | undefined;
  /**  Row 8 — (f) Code(s) from instructions */
  "1.part2.row8_adjustment_code": string | undefined;
  /**  Row 8 — (g) Amount of adjustment */
  "1.part2.row8_adjustment_amount": number | undefined;
  /**  Row 8 — (h) Gain or (loss) */
  "1.part2.row8_gain_loss": number | undefined;
  /**  Row 9 — (a) Description of property */
  "1.part2.row9_description": string | undefined;
  /**  Row 9 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row9_date_acquired": string | undefined;
  /**  Row 9 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row9_date_sold": string | undefined;
  /**  Row 9 — (d) Proceeds (sales price) */
  "1.part2.row9_proceeds": number | undefined;
  /**  Row 9 — (e) Cost or other basis */
  "1.part2.row9_cost_basis": number | undefined;
  /**  Row 9 — (f) Code(s) from instructions */
  "1.part2.row9_adjustment_code": string | undefined;
  /**  Row 9 — (g) Amount of adjustment */
  "1.part2.row9_adjustment_amount": number | undefined;
  /**  Row 9 — (h) Gain or (loss) */
  "1.part2.row9_gain_loss": number | undefined;
  /**  Row 10 — (a) Description of property */
  "1.part2.row10_description": string | undefined;
  /**  Row 10 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row10_date_acquired": string | undefined;
  /**  Row 10 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row10_date_sold": string | undefined;
  /**  Row 10 — (d) Proceeds (sales price) */
  "1.part2.row10_proceeds": number | undefined;
  /**  Row 10 — (e) Cost or other basis */
  "1.part2.row10_cost_basis": number | undefined;
  /**  Row 10 — (f) Code(s) from instructions */
  "1.part2.row10_adjustment_code": string | undefined;
  /**  Row 10 — (g) Amount of adjustment */
  "1.part2.row10_adjustment_amount": number | undefined;
  /**  Row 10 — (h) Gain or (loss) */
  "1.part2.row10_gain_loss": number | undefined;
  /**  Row 11 — (a) Description of property */
  "1.part2.row11_description": string | undefined;
  /**  Row 11 — (b) Date acquired (Mo., day, yr.) */
  "1.part2.row11_date_acquired": string | undefined;
  /**  Row 11 — (c) Date sold or disposed of (Mo., day, yr.) */
  "1.part2.row11_date_sold": string | undefined;
  /**  Row 11 — (d) Proceeds (sales price) */
  "1.part2.row11_proceeds": number | undefined;
  /**  Row 11 — (e) Cost or other basis */
  "1.part2.row11_cost_basis": number | undefined;
  /**  Row 11 — (f) Code(s) from instructions */
  "1.part2.row11_adjustment_code": string | undefined;
  /**  Row 11 — (g) Amount of adjustment */
  "1.part2.row11_adjustment_amount": number | undefined;
  /**  Row 11 — (h) Gain or (loss) */
  "1.part2.row11_gain_loss": number | undefined;
  /**  Line 2 Totals — (d) Proceeds (sales price) */
  "1.part2.totals_proceeds": number | undefined;
  /**  Line 2 Totals — (e) Cost or other basis */
  "1.part2.totals_cost_basis": number | undefined;
  /**  Line 2 Totals — (g) Amount of adjustment */
  "1.part2.totals_adjustment_amount": number | undefined;
  /**  Line 2 Totals — (h) Gain or (loss) */
  "1.part2.totals_gain_loss": number | undefined;
}
