// AI-generated by forms:bind, then hand-edited. Manual edits marked
// `// MANUAL EDIT:` so they survive the next regeneration.
// Source: forms-pipeline/generateBindingsWorkflow
// Form: Schedule A (Form 1040) — Itemized Deductions (schedule-a, tax year 2025)
// Generated at: 2026-05-27T16:08:48.440Z

import { defineForm, sum, floor } from "../../engine.js";
import { SSN } from "../../values.js";
import type { ScheduleA } from "./types.js";
import type { ScheduleAFilingInfo } from "./filingInfo.js";

// Wrapping defineForm inside a register() function lets callers
// import { register } and force the side-effectful registration once
// at startup. Idempotent — calling twice overwrites in place.
export function register(): void {
  defineForm<ScheduleA, ScheduleAFilingInfo>("schedule-a", {
    // MANUAL EDIT: AI defaulted to info.mustFileFederal. Schedule A is
    // only filed when the taxpayer itemizes — routed to the form-scoped
    // flag (driven by decisions.itemize_vs_standard via resolveFilingInfo).
    mustFile: (info) => info.mustFileScheduleA,

    bindings: {
      // MANUAL EDIT: no combined-name fact; concatenate first + last
      // (same pattern as Schedule D / 8949 / Schedule CA).
      "0.header.taxpayer_name": (_, info) =>
        info.taxpayerFirstName && info.taxpayerLastName
          ? `${info.taxpayerFirstName} ${info.taxpayerLastName}`
          : undefined,
      // SSN header field maps directly to the identity.ssn fact.
      "0.header.ssn": (_, info) => info.taxpayerSSN,
      // MANUAL EDIT: routed to FilingInfo slot. resolveFilingInfo reads
      // a single fact key (medical.expenses_total) today; richer aggregation
      // when we add a medical fact kind.
      "0.line.1_medical_dental_expenses": (_, info) => info.medicalDentalExpenses,
      // MANUAL EDIT: IRS Schedule A instructions say "if line 1 is blank,
      // skip lines 2 through 4." Guarding all three lines on line 1 being
      // set keeps the worksheet inert for taxpayers with no medical
      // expenses (the common case) — matches the CPA convention of
      // leaving those widgets blank.
      // Cross-form reference: Schedule A line 2 = Form 1040 line 11b (AGI).
      "0.line.2_agi_from_1040": (f) => {
        if (f["0.line.1_medical_dental_expenses"] === undefined) return undefined;
        const agi = f["form-1040.line.11b"];
        return typeof agi === "number" ? agi : undefined;
      },
      // Line 3 = line 2 × 7.5%, rounded UP to whole dollars per the
      // project's Math.ceil convention (see CLAUDE.md "Whole-dollar
      // rounding").
      "0.line.3_agi_multiplied": (f) => {
        if (f["0.line.1_medical_dental_expenses"] === undefined) return undefined;
        const line2 = f["0.line.2_agi_from_1040"];
        if (typeof line2 !== "number") return undefined;
        return Math.ceil(line2 * 0.075);
      },
      // Line 4 = Line 1 minus Line 3, floored at 0 per instructions
      // ("if line 3 is more than line 1, enter -0-").
      "0.line.4_net_medical_dental": (f) => {
        if (f["0.line.1_medical_dental_expenses"] === undefined) return undefined;
        return floor(
          0,
          sum(
            f["0.line.1_medical_dental_expenses"],
            f["0.line.3_agi_multiplied"] === undefined
              ? 0
              : -f["0.line.3_agi_multiplied"],
          ),
        );
      },
      // MANUAL EDIT: routed to FilingInfo. Election checkbox is rare for
      // CA filers (always blank — state income tax > sales tax), but slot
      // exists for no-income-tax-state scenarios (TX, FL, etc.).
      "0.line.5a_general_sales_tax_election": (_, info) =>
        info.generalSalesTaxElection,
      // MANUAL EDIT: routed to FilingInfo slot. Composes W-2 box 17 +
      // CA SDI (box 14) + state estimated payments inside resolveFilingInfo.
      // When the sales-tax election is set, this slot must be sales-tax
      // amount instead — not yet modeled (no scenario forces it).
      "0.line.5a_state_local_income_or_sales_tax": (_, info) =>
        info.stateLocalIncomeTaxPaid,
      // MANUAL EDIT: routed to FilingInfo slot.
      "0.line.5b_real_estate_taxes": (_, info) => info.realEstateTaxes,
      // MANUAL EDIT: routed to FilingInfo slot.
      "0.line.5c_personal_property_taxes": (_, info) =>
        info.personalPropertyTaxes,
      // MANUAL EDIT: subtotal lines on Schedule A suppress when every
      // addend is undefined — matches the CPA convention of leaving a
      // section blank when none of its inputs apply (e.g. no mortgage
      // means line 8e is blank, not "0"). sum() alone returns 0 in that
      // case, which renders as the wrong character.
      "0.line.5d_total_state_local_taxes": (f) => {
        const a = f["0.line.5a_state_local_income_or_sales_tax"];
        const b = f["0.line.5b_real_estate_taxes"];
        const c = f["0.line.5c_personal_property_taxes"];
        if (a === undefined && b === undefined && c === undefined) return undefined;
        return sum(a, b, c);
      },
      // MANUAL EDIT: OBBBA 2025 SALT cap. Base cap is $40,000 ($20,000
      // MFS) for 2025–2029, phasing out by 30% of MAGI excess over
      // $500,000 ($250,000 MFS), with a floor of $10,000 ($5,000 MFS).
      // MAGI ≈ AGI for the simple cases we model (no FEIE / territory
      // exclusions); using form-1040.line.11b as MAGI. Line 5e is the
      // smaller of line 5d and the (phase-out-adjusted) cap.
      "0.line.5e_salt_cap": (f, info) => {
        const line5d = f["0.line.5d_total_state_local_taxes"];
        if (typeof line5d !== "number") return undefined;
        const mfs = info.filingStatus === "married_filing_separately";
        const baseCap = mfs ? 20000 : 40000;
        const threshold = mfs ? 250000 : 500000;
        const capFloor = mfs ? 5000 : 10000;
        const magi = f["form-1040.line.11b"];
        let cap = baseCap;
        if (typeof magi === "number" && magi > threshold) {
          cap = Math.max(capFloor, baseCap - 0.3 * (magi - threshold));
        }
        return Math.min(line5d, cap);
      },
      // Line 7 = 5e + 6 (SALT cap + other taxes).
      "0.line.7_total_taxes": (f) => {
        const e = f["0.line.5e_salt_cap"];
        const six = f["0.line.6_other_taxes_amount"];
        if (e === undefined && six === undefined) return undefined;
        return sum(e, six);
      },
      // MANUAL EDIT: routed to FilingInfo slot (single 1098 for now;
      // multi-1098 sum lands when fact-kind plumbing exists).
      "0.line.8a_mortgage_interest_form1098": (_, info) =>
        info.mortgageInterestForm1098,
      // MANUAL EDIT: routed to FilingInfo slot (seller-financed loans).
      "0.line.8b_mortgage_interest_not_form1098": (_, info) =>
        info.mortgageInterestNotForm1098,
      // MANUAL EDIT: routed to FilingInfo slot.
      "0.line.8c_points_not_form1098": (_, info) => info.pointsNotForm1098,
      // Line 8e = 8a + 8b + 8c (total mortgage interest and points).
      "0.line.8e_total_mortgage_interest_points": (f) => {
        const a = f["0.line.8a_mortgage_interest_form1098"];
        const b = f["0.line.8b_mortgage_interest_not_form1098"];
        const c = f["0.line.8c_points_not_form1098"];
        if (a === undefined && b === undefined && c === undefined) return undefined;
        return sum(a, b, c);
      },
      // MANUAL EDIT: routed to FilingInfo slot. Form 4952 attachment is
      // out of scope; the slot is left undefined for scenarios without
      // it.
      "0.line.9_investment_interest": (_, info) => info.investmentInterest,
      // Line 10 = 8e + 9 (total interest deduction).
      "0.line.10_total_interest": (f) => {
        const e = f["0.line.8e_total_mortgage_interest_points"];
        const nine = f["0.line.9_investment_interest"];
        if (e === undefined && nine === undefined) return undefined;
        return sum(e, nine);
      },
      // MANUAL EDIT: routed to FilingInfo slot.
      "0.line.11_gifts_cash_check": (_, info) => info.giftsCashCheck,
      // MANUAL EDIT: routed to FilingInfo slot.
      "0.line.12_gifts_other_than_cash": (_, info) => info.giftsOtherThanCash,
      // MANUAL EDIT: routed to FilingInfo slot.
      "0.line.13_gifts_carryover": (_, info) => info.giftsCarryover,
      // Line 14 = 11 + 12 + 13 (total gifts to charity).
      "0.line.14_total_gifts": (f) => {
        const eleven = f["0.line.11_gifts_cash_check"];
        const twelve = f["0.line.12_gifts_other_than_cash"];
        const thirteen = f["0.line.13_gifts_carryover"];
        if (
          eleven === undefined &&
          twelve === undefined &&
          thirteen === undefined
        ) {
          return undefined;
        }
        return sum(eleven, twelve, thirteen);
      },
      // Sum of all itemized deduction subtotals from lines 4 through 16.
      "0.line.17_total_itemized_deductions": (f) =>
        sum(
          f["0.line.4_net_medical_dental"],
          f["0.line.7_total_taxes"],
          f["0.line.10_total_interest"],
          f["0.line.14_total_gifts"],
          f["0.line.15_casualty_theft_loss"],
          f["0.line.16_other_itemized_deductions_amount"],
        ),
    },

    // Schedule A SSN widget keeps the dashes ("345-67-8901") rather than
    // stripping them like 1040's comb widget. Same per-form override
    // pattern CA 540 uses on its page-2 SSN — federal forms aren't
    // homogeneous on this; treat it as form-specific.
    formatters: {
      "0.header.ssn": (value) =>
        SSN.format(value as Parameters<typeof SSN.format>[0]),
    },

    unsupported: {
      "0.line.6_other_taxes_description":
        "Free-text description of other taxes (e.g. foreign income taxes). No fact or decision key exists for this; requires a scenario with other taxes to model.",
      "0.line.6_other_taxes_amount":
        "Other taxes (e.g. foreign income taxes, generation-skipping taxes) — no fact category or decision key exists for these; requires a dedicated ingestion scenario.",
      "0.line.8_home_mortgage_partial_use_checkbox":
        "Checkbox indicating mixed personal/business use of home mortgage — no fact or decision key exists for this. Requires a scenario where taxpayer has a home loan used partly for non-home purposes.",
      "0.line.8b_seller_name_address":
        "Name/address of seller for non-1098 mortgage interest — text field with no corresponding fact key. Only populated in seller-financed loan scenarios not yet modeled.",
      "0.line.15_casualty_theft_loss":
        "Casualty and theft losses require Form 4684 data; no Form 4684 ingestion path exists yet",
      "0.line.16_other_itemized_deductions_description":
        "Other itemized deductions are freeform (gambling losses, etc.); no ingestion path or scenario built yet",
      "0.line.16_other_itemized_deductions_amount":
        "Other itemized deductions amount is freeform (gambling losses, etc.); no ingestion path or scenario built yet",
      "0.line.18_elect_itemize_below_standard":
        "No decision or fact models the taxpayer's explicit election to itemize even when deductions are below the standard deduction. This is an uncommon voluntary election with no ingestion path yet — requires a dedicated ai_decision when a real scenario forces it.",
    },

    todos: {},
  });
}

// Summary: 22 binding(s), 0 todo(s), 8 unsupported, 0 unbound.
// Confidence: hand-edited.
