// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/federal/schedule-a/catalog.json
// Form: Schedule A (Form 1040) — Itemized Deductions (schedule-a, tax year 2025)
// Fields: 32
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface ScheduleA {
  /**  Name(s) shown on Form 1040 or 1040-SR */
  "0.header.taxpayer_name": string | undefined;
  /**  Your social security number */
  "0.header.ssn": string | undefined;
  /**  Line 1 — Medical and dental expenses (see instructions) */
  "0.line.1_medical_dental_expenses": number | undefined;
  /**  Line 2 — Enter amount from Form 1040 or 1040-SR, line 11b */
  "0.line.2_agi_from_1040": number | undefined;
  /**  Line 3 — Multiply line 2 by 7.5% (0.075) */
  "0.line.3_agi_multiplied": number | undefined;
  /**  Line 4 — Subtract line 3 from line 1. If line 3 is more than line 1, enter -0- */
  "0.line.4_net_medical_dental": number | undefined;
  /**  Line 5a — If you elect to include general sales taxes instead of income taxes, check this box */
  "0.line.5a_general_sales_tax_election": boolean | undefined;
  /**  Line 5a — State and local income taxes or general sales taxes */
  "0.line.5a_state_local_income_or_sales_tax": number | undefined;
  /**  Line 5b — State and local real estate taxes (see instructions) */
  "0.line.5b_real_estate_taxes": number | undefined;
  /**  Line 5c — State and local personal property taxes */
  "0.line.5c_personal_property_taxes": number | undefined;
  /**  Line 5d — Add lines 5a through 5c */
  "0.line.5d_total_state_local_taxes": number | undefined;
  /**  Line 5e — Enter the smaller of line 5d or $40,000 ($20,000 if married filing separately) */
  "0.line.5e_salt_cap": number | undefined;
  /**  Line 6 — Other taxes. List type and amount (description field) */
  "0.line.6_other_taxes_description": string | undefined;
  /**  Line 6 — Other taxes. List type and amount (amount field) */
  "0.line.6_other_taxes_amount": number | undefined;
  /**  Line 7 — Add lines 5e and 6 */
  "0.line.7_total_taxes": number | undefined;
  /**  Line 8 — Home mortgage interest and points. If you didn't use all of your home mortgage loan(s) to buy, build, or improve your home, see instructions and check this box */
  "0.line.8_home_mortgage_partial_use_checkbox": boolean | undefined;
  /**  Line 8a — Home mortgage interest and points reported to you on Form 1098 */
  "0.line.8a_mortgage_interest_form1098": number | undefined;
  /**  Line 8b — Home mortgage interest not reported to you on Form 1098 */
  "0.line.8b_mortgage_interest_not_form1098": number | undefined;
  /**  Line 8b — Name, identifying no., and address of person from whom you bought the home */
  "0.line.8b_seller_name_address": string | undefined;
  /**  Line 8c — Points not reported to you on Form 1098 */
  "0.line.8c_points_not_form1098": number | undefined;
  /**  Line 8e — Add lines 8a through 8c */
  "0.line.8e_total_mortgage_interest_points": number | undefined;
  /**  Line 9 — Investment interest. Attach Form 4952 if required. */
  "0.line.9_investment_interest": number | undefined;
  /**  Line 10 — Add lines 8e and 9 */
  "0.line.10_total_interest": number | undefined;
  /**  Line 11 — Gifts by cash or check */
  "0.line.11_gifts_cash_check": number | undefined;
  /**  Line 12 — Other than by cash or check */
  "0.line.12_gifts_other_than_cash": number | undefined;
  /**  Line 13 — Carryover from prior year */
  "0.line.13_gifts_carryover": number | undefined;
  /**  Line 14 — Add lines 11 through 13 */
  "0.line.14_total_gifts": number | undefined;
  /**  Line 15 — Casualty and theft loss(es) from a federally declared disaster. Attach Form 4684. */
  "0.line.15_casualty_theft_loss": number | undefined;
  /**  Line 16 — Other itemized deductions. List type and amount (description field) */
  "0.line.16_other_itemized_deductions_description": string | undefined;
  /**  Line 16 — Other itemized deductions. List type and amount (amount field) */
  "0.line.16_other_itemized_deductions_amount": number | undefined;
  /**  Line 17 — Total Itemized Deductions. Add the amounts in the far right column for lines 4 through 16. */
  "0.line.17_total_itemized_deductions": number | undefined;
  /**  Line 18 — If you elect to itemize deductions even though they are less than your standard deduction, check this box */
  "0.line.18_elect_itemize_below_standard": boolean | undefined;
}
