// Emit a typed `Form<Id>` interface from a catalog JSON file.
//
// Each catalog field has a `fieldId`, `valueType` (numeric/text/boolean/date/
// single_select/multi_select), and a `label`. We strip the formId prefix
// off each fieldId to get short keys (the convention used by defineForm),
// map valueType → TS primitive, and emit one interface declaration the
// bindings file can import.
//
// Re-running overwrites.

import { promises as fs } from "node:fs";
import { resolve } from "node:path";
import { projectRoot } from "../../src/paths.js";
import type { Command } from "../lib/cli";

interface CatalogField {
  fieldId: string;
  label?: string;
  valueType: "numeric" | "text" | "boolean" | "date" | "single_select" | "multi_select";
}

interface CatalogFile {
  form: { formId: string; taxYear: number; title?: string };
  fields: CatalogField[];
}

interface Args {
  catalogPath: string;
  outputPath: string;
  interfaceName: string;
}

function parseCmdArgs(argv: string[]): Args {
  const get = (flag: string): string | undefined => {
    const arg = argv.find((a) => a.startsWith(`${flag}=`));
    return arg ? arg.slice(flag.length + 1) : undefined;
  };
  const catalog = get("--catalog");
  const output = get("--output");
  const iface = get("--interface");
  if (!catalog || !output || !iface) {
    throw new Error("Required: --catalog=path --output=path --interface=Name");
  }
  return {
    catalogPath: resolve(projectRoot, catalog),
    outputPath: resolve(projectRoot, output),
    interfaceName: iface,
  };
}

// Map catalog valueType → TS primitive. Branded subtypes (Money for
// numeric, SSN/Phone for specific text fields) are a future refinement;
// for now we use plain primitives so the generated file is dependency-free.
function tsType(field: CatalogField): string {
  switch (field.valueType) {
    case "numeric":
      return "number";
    case "text":
      return "string";
    case "boolean":
      return "boolean";
    case "date":
      return "string";
    case "single_select":
      return "string";
    case "multi_select":
      return "string[]";
    default:
      return "unknown";
  }
}

// Field IDs in the catalog are full ("form-540.header.first_name"); the
// defineForm convention uses short keys ("header.first_name"). Strip the
// formId prefix once at emit time.
function shortKey(fieldId: string, formId: string): string {
  const prefix = `${formId}.`;
  if (!fieldId.startsWith(prefix)) {
    throw new Error(
      `fieldId "${fieldId}" doesn't start with formId prefix "${prefix}".`,
    );
  }
  return fieldId.slice(prefix.length);
}

function buildSource(args: Args, catalog: CatalogFile): string {
  const { form, fields } = catalog;
  const lines: string[] = [];
  lines.push(`// AUTO-GENERATED by \`npm run form-engine -- generate-types\`.`);
  lines.push(`// Source: ${args.catalogPath.replace(projectRoot + "/", "")}`);
  lines.push(
    `// Form: ${form.title ?? form.formId} (${form.formId}, tax year ${form.taxYear})`,
  );
  lines.push(`// Fields: ${fields.length}`);
  lines.push(`//`);
  lines.push(
    `// Hand edits are overwritten on the next regeneration. To change a`,
  );
  lines.push(`// field shape, edit the catalog and re-run generate-types.`);
  lines.push(``);
  lines.push(`export interface ${args.interfaceName} {`);
  for (const f of fields) {
    const key = shortKey(f.fieldId, form.formId);
    const ty = tsType(f);
    const label = f.label ? `  ${f.label.replace(/\*\//g, "*\\/")}` : "";
    if (label) {
      lines.push(`  /**${label} */`);
    }
    lines.push(`  ${JSON.stringify(key)}: ${ty} | undefined;`);
  }
  lines.push(`}`);
  lines.push(``);
  return lines.join("\n");
}

async function run(argv: string[]): Promise<void> {
  const args = parseCmdArgs(argv);
  console.log(`Reading catalog: ${args.catalogPath}`);
  const raw = await fs.readFile(args.catalogPath, "utf8");
  const catalog = JSON.parse(raw) as CatalogFile;

  const src = buildSource(args, catalog);
  await fs.writeFile(args.outputPath, src);
  console.log(
    `Wrote ${args.interfaceName} (${catalog.fields.length} fields) → ${args.outputPath}`,
  );
}

export const generateTypesCommand: Command = {
  name: "generate-types",
  summary: "Emit a typed Form<Id> interface from a form's catalog.json",
  options: [
    { flag: "--catalog=<path>", desc: "catalog.json, relative to apps/agent (required), e.g. forms/state/ca/540/catalog.json" },
    { flag: "--output=<path>", desc: "output .ts path, relative to apps/agent (required)" },
    { flag: "--interface=<Name>", desc: "interface name to emit, e.g. Form540 (required)" },
  ],
  run,
};
