"use client";

import { useEffect, useState } from "react";
import { useAppShell } from "@/components/AppShell";
import { cn } from "@/lib/cn";
import { createClient } from "@/lib/supabase/client";

interface DocCardProps {
  name: string;
  description: string;
  status?: string;
  statusTone?: "neutral" | "draft" | "ready";
  /** Same-origin URL — Next.js Route Handler reads the cookie + 302s. */
  href: string;
}

const STATUS_TONE: Record<NonNullable<DocCardProps["statusTone"]>, string> = {
  neutral: "text-ink-muted bg-bg-elevated",
  draft: "text-amber-400 bg-amber-400/10",
  ready: "text-emerald-400 bg-emerald-400/10",
};

function DocCard({ name, description, status, statusTone = "neutral", href }: DocCardProps) {
  // ?download=1 flips Content-Disposition: attachment in the Route Handler.
  // No more bearer-header workaround — cookie auth means navigations work.
  const downloadHref = href.includes("?")
    ? `${href}&download=1`
    : `${href}?download=1`;

  return (
    <div className="card px-5 py-4 flex items-center gap-4 hover:border-border-strong transition-colors">
      <div className="w-10 h-12 shrink-0 border border-border-subtle rounded-md flex items-center justify-center text-ink-muted text-[10px] font-medium tracking-wide">
        PDF
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-ink-primary text-sm font-medium">{name}</span>
          {status && (
            <span
              className={cn(
                "px-2 py-0.5 rounded text-[10px] font-medium uppercase tracking-wide",
                STATUS_TONE[statusTone],
              )}
            >
              {status}
            </span>
          )}
        </div>
        <div className="mt-0.5 text-ink-secondary text-xs truncate">
          {description}
        </div>
      </div>
      <div className="shrink-0 flex items-center gap-2">
        <a
          href={href}
          target="_blank"
          rel="noopener noreferrer"
          className="text-xs text-ink-secondary hover:text-ink-primary border border-border-subtle hover:border-border-strong rounded-md px-3 py-1.5 transition-colors"
        >
          View
        </a>
        <a
          href={downloadHref}
          className="text-xs text-ink-secondary hover:text-ink-primary border border-border-subtle hover:border-border-strong rounded-md px-3 py-1.5 transition-colors"
        >
          Download
        </a>
      </div>
    </div>
  );
}

interface UploadRow {
  id: string;
  filename: string;
  created_at: string;
  mime_type: string | null;
  size_bytes: number | null;
}

function formatBytes(bytes: number | null): string {
  if (!bytes) return "";
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function formatUploadedAt(iso: string): string {
  const d = new Date(iso);
  const opts: Intl.DateTimeFormatOptions = { month: "short", day: "numeric" };
  if (d.getFullYear() !== new Date().getFullYear()) opts.year = "numeric";
  return d.toLocaleDateString(undefined, opts);
}

export default function DocumentsPage() {
  const { state, resetTick } = useAppShell();
  const [uploads, setUploads] = useState<UploadRow[]>([]);

  // Direct supabase-js read scoped by RLS to the current user. Refetches on
  // resetTick (bumped by the Reset button) so the uploads list clears in
  // the same gesture as the chat.
  useEffect(() => {
    let cancelled = false;
    const supabase = createClient();
    supabase
      .from("user_documents")
      .select("id, filename, created_at, mime_type, size_bytes")
      .eq("category", "uploads")
      .order("created_at", { ascending: false })
      .then(({ data, error }) => {
        if (cancelled) return;
        if (error) {
          console.warn("[documents] failed to load uploads:", error.message);
          setUploads([]);
          return;
        }
        setUploads((data ?? []) as UploadRow[]);
      });
    return () => {
      cancelled = true;
    };
  }, [resetTick]);

  // Drafts: most-recent-per-form, surfaced by /app/state. Each generate-tax-
  // documents run inserts new rows; the route returns the latest URL per
  // formId. Forms the engine doesn't compute yet (8949, Schedule D) simply
  // don't appear — no dead null branches.
  const drafts: DocCardProps[] = [];
  if (state?.documents.form1040Url) {
    drafts.push({
      name: "Draft 1040 — 2025",
      description:
        "Federal individual income tax return. Generated by Thom from your facts; not yet filed.",
      status: "Draft",
      statusTone: "draft",
      href: state.documents.form1040Url,
    });
  }
  if (state?.documents.form540Url) {
    drafts.push({
      name: "CA Form 540 — 2025",
      description:
        "California Resident Income Tax Return. State counterpart to the federal 1040.",
      status: "Draft",
      statusTone: "draft",
      href: state.documents.form540Url,
    });
  }
  if (state?.documents.sidecarUrl) {
    drafts.push({
      name: "Forms data (JSON)",
      description:
        "Line values for every form the engine computed — useful for CPA review and debugging.",
      status: "Data",
      statusTone: "neutral",
      href: state.documents.sidecarUrl,
    });
  }

  return (
    <div className="flex-1 min-w-0 min-h-0 overflow-y-auto px-4 lg:px-10 py-8 lg:py-12">
      <div className="max-w-3xl mx-auto">
        <div className="text-ink-muted text-[10px] uppercase tracking-[0.24em]">
          Tax Documents
        </div>
        <h1 className="mt-2 font-serif text-3xl text-ink-primary">
          Your filing cabinet
        </h1>
        <p className="mt-3 text-ink-secondary text-sm leading-relaxed max-w-xl">
          Forms Thom generates for your 2025 return live here, alongside the
          source documents you've uploaded.
        </p>

        <section className="mt-10">
          <h2 className="text-ink-muted text-[10px] uppercase tracking-[0.24em] mb-3">
            Drafts
          </h2>
          <div className="space-y-3">
            {drafts.length > 0 ? (
              drafts.map((d) => <DocCard key={d.href} {...d} />)
            ) : (
              <div className="card px-6 py-8 text-center">
                <div className="text-ink-muted text-sm">No drafts yet.</div>
                <div className="mt-1 text-ink-faint text-xs">
                  Once Thom generates your forms, they'll appear here.
                </div>
              </div>
            )}
          </div>
        </section>

        <section className="mt-10">
          <h2 className="text-ink-muted text-[10px] uppercase tracking-[0.24em] mb-3">
            Uploads
          </h2>
          <div className="space-y-3">
            {uploads.length > 0 ? (
              uploads.map((u) => {
                const sizeText = formatBytes(u.size_bytes);
                const dateText = formatUploadedAt(u.created_at);
                const description = sizeText
                  ? `${dateText} · ${sizeText}`
                  : dateText;
                return (
                  <DocCard
                    key={u.id}
                    name={u.filename}
                    description={description}
                    status="Uploaded"
                    statusTone="neutral"
                    href={`/documents/${u.id}`}
                  />
                );
              })
            ) : (
              <div className="card px-6 py-8 text-center">
                <div className="text-ink-muted text-sm">No uploads yet.</div>
                <div className="mt-1 text-ink-faint text-xs">
                  Drop a W-2, 1099, or receipt into chat — Thom will read it
                  and the file will be saved here.
                </div>
              </div>
            )}
          </div>
        </section>
      </div>
    </div>
  );
}
