import { useOutletContext } from "react-router-dom";
import type { LayoutOutletContext } from "@/components/Layout";
import { cn } from "@/lib/cn";

interface DocCardProps {
  name: string;
  description: string;
  status?: string;
  statusTone?: "neutral" | "draft" | "ready";
  href: string;
}

const STATUS_TONE: Record<NonNullable<DocCardProps["statusTone"]>, string> = {
  neutral: "text-ink-muted bg-bg-elevated",
  draft: "text-amber-400 bg-amber-400/10",
  ready: "text-emerald-400 bg-emerald-400/10",
};

function DocCard({ name, description, status, statusTone = "neutral", href }: DocCardProps) {
  return (
    <a
      href={href}
      target="_blank"
      rel="noopener noreferrer"
      className="card px-5 py-4 flex items-center gap-4 hover:border-border-strong transition-colors group"
    >
      <div className="w-10 h-12 shrink-0 border border-border-subtle rounded-md flex items-center justify-center text-ink-muted text-[10px] font-medium tracking-wide">
        PDF
      </div>
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 flex-wrap">
          <span className="text-ink-primary text-sm font-medium">{name}</span>
          {status && (
            <span
              className={cn(
                "px-2 py-0.5 rounded text-[10px] font-medium uppercase tracking-wide",
                STATUS_TONE[statusTone],
              )}
            >
              {status}
            </span>
          )}
        </div>
        <div className="mt-0.5 text-ink-secondary text-xs truncate">
          {description}
        </div>
      </div>
      <span className="shrink-0 text-ink-muted text-sm group-hover:text-ink-primary transition-colors">
        Open ↗
      </span>
    </a>
  );
}

export function Documents() {
  const { state } = useOutletContext<LayoutOutletContext>();

  // Collect everything Thom has produced for this session, in form-order.
  const docs: DocCardProps[] = [];
  if (state?.draftUrl) {
    docs.push({
      name: "Draft 1040 — 2025",
      description: "Federal individual income tax return. Generated by Thom from your facts; not yet filed.",
      status: "Draft",
      statusTone: "draft",
      href: state.draftUrl,
    });
  }
  if (state?.scheduleDUrl) {
    docs.push({
      name: "Schedule D — 2025",
      description: "Capital Gains and Losses. Summarizes Form 8949 trade totals; feeds Form 1040 line 7.",
      status: "Draft",
      statusTone: "draft",
      href: state.scheduleDUrl,
    });
  }
  if (state?.form8949Url) {
    docs.push({
      name: "Form 8949 — 2025",
      description: "Sales and Other Dispositions of Capital Assets. Itemizes every sale; rolls up to Schedule D.",
      status: "Draft",
      statusTone: "draft",
      href: state.form8949Url,
    });
  }
  if (state?.form540Url) {
    docs.push({
      name: "CA Form 540 — 2025",
      description: "California Resident Income Tax Return. State counterpart to the federal 1040.",
      status: "Draft",
      statusTone: "draft",
      href: state.form540Url,
    });
  }
  if (state?.sidecarUrl) {
    docs.push({
      name: "Forms data (JSON)",
      description: "Line values for every form the engine computed — useful for CPA review and debugging.",
      status: "Data",
      statusTone: "neutral",
      href: state.sidecarUrl,
    });
  }

  return (
    <div className="flex-1 min-w-0 min-h-0 overflow-y-auto px-4 lg:px-10 py-8 lg:py-12">
      <div className="max-w-3xl mx-auto">
        <div className="text-ink-muted text-[10px] uppercase tracking-[0.24em]">
          Tax Documents
        </div>
        <h1 className="mt-2 font-serif text-3xl text-ink-primary">
          Your filing cabinet
        </h1>
        <p className="mt-3 text-ink-secondary text-sm leading-relaxed max-w-xl">
          Documents generated for your 2025 return live here. Uploads from chat
          and source documents will land here too.
        </p>

        <div className="mt-10 space-y-3">
          {docs.length > 0 ? (
            docs.map((d) => <DocCard key={d.href} {...d} />)
          ) : (
            <div className="card px-6 py-10 text-center">
              <div className="text-ink-muted text-sm">No documents yet.</div>
              <div className="mt-1 text-ink-faint text-xs">
                Once Thom generates your forms, they will appear here.
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
