// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/federal/8959/catalog.json
// Form: Form 8959 — Additional Medicare Tax (form-8959, tax year 2025)
// Fields: 26
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface Form8959 {
  /**  Name(s) shown on return */
  "0.header.taxpayer_name": string | undefined;
  /**  Your social security number */
  "0.header.ssn": string | undefined;
  /**  Line 1 — Medicare wages and tips from Form W-2, box 5 */
  "0.line.1_medicare_wages_tips": number | undefined;
  /**  Line 2 — Unreported tips from Form 4137, line 6 */
  "0.line.2_unreported_tips": number | undefined;
  /**  Line 3 — Wages from Form 8919, line 6 */
  "0.line.3_wages_form_8919": number | undefined;
  /**  Line 4 — Add lines 1 through 3 */
  "0.line.4_total_medicare_wages": number | undefined;
  /**  Line 5 — Enter the following amount for your filing status */
  "0.line.5_filing_status_threshold_wages": number | undefined;
  /**  Line 6 — Subtract line 5 from line 4. If zero or less, enter -0- */
  "0.line.6_excess_medicare_wages": number | undefined;
  /**  Line 7 — Additional Medicare Tax on Medicare wages. Multiply line 6 by 0.9% (0.009) */
  "0.line.7_additional_medicare_tax_wages": number | undefined;
  /**  Line 8 — Self-employment income from Schedule SE (Form 1040), Part I, line 6 */
  "0.line.8_self_employment_income": number | undefined;
  /**  Line 9 — Enter the following amount for your filing status */
  "0.line.9_filing_status_threshold_se": number | undefined;
  /**  Line 10 — Enter the amount from line 4 */
  "0.line.10_medicare_wages_from_line4": number | undefined;
  /**  Line 11 — Subtract line 10 from line 9. If zero or less, enter -0- */
  "0.line.11_threshold_reduced_by_wages": number | undefined;
  /**  Line 12 — Subtract line 11 from line 8. If zero or less, enter -0- */
  "0.line.12_excess_se_income": number | undefined;
  /**  Line 13 — Additional Medicare Tax on self-employment income. Multiply line 12 by 0.9% (0.009) */
  "0.line.13_additional_medicare_tax_se": number | undefined;
  /**  Line 14 — Railroad retirement (RRTA) compensation and tips from Form(s) W-2, box 14 */
  "0.line.14_rrta_compensation_tips": number | undefined;
  /**  Line 15 — Enter the following amount for your filing status */
  "0.line.15_filing_status_threshold_rrta": number | undefined;
  /**  Line 16 — Subtract line 15 from line 14. If zero or less, enter -0- */
  "0.line.16_excess_rrta_compensation": number | undefined;
  /**  Line 17 — Additional Medicare Tax on railroad retirement (RRTA) compensation. Multiply line 16 by 0.9% (0.009) */
  "0.line.17_additional_medicare_tax_rrta": number | undefined;
  /**  Line 18 — Total Additional Medicare Tax. Add lines 7, 13, and 17 */
  "0.line.18_total_additional_medicare_tax": number | undefined;
  /**  Line 19 — Medicare tax withheld from Form W-2, box 6 */
  "0.line.19_medicare_tax_withheld": number | undefined;
  /**  Line 20 — Enter the amount from line 1 */
  "0.line.20_medicare_wages_from_line1": number | undefined;
  /**  Line 21 — Multiply line 20 by 1.45% (0.0145). Regular Medicare tax withholding on Medicare wages */
  "0.line.21_regular_medicare_tax_on_wages": number | undefined;
  /**  Line 22 — Subtract line 21 from line 19. If zero or less, enter -0-. Additional Medicare Tax withholding on Medicare wages */
  "0.line.22_additional_medicare_tax_withholding_wages": number | undefined;
  /**  Line 23 — Additional Medicare Tax withholding on railroad retirement (RRTA) compensation from Form W-2, box 14 */
  "0.line.23_additional_medicare_tax_withholding_rrta": number | undefined;
  /**  Line 24 — Total Additional Medicare Tax withholding. Add lines 22 and 23 */
  "0.line.24_total_additional_medicare_tax_withholding": number | undefined;
}
