// Phase D — render bindings into TypeScript source for
// forms/generated/<formId>.ts. The renderer is dumb: it takes structured
// bindings from the classifier and emits the same shape we hand-wrote
// during Phase A.
//
// Layout:
//   import { bindMustFile, bindField } from "../engine.js";
//   import * as r from "../rules/index.js";
//
//   bindMustFile("form-1040", r.lookupDecision, { ... });
//
//   // line 1a — Total amount from Form(s) W-2, box 1
//   //   why: <rationale from classifier>
//   bindField("form-1040", "form-1040.line.1a", r.sumFacts, { ... });
//
//   // … one block per field, in inventory ordinal order …

import type { ClassifiedBinding, RuleName } from "./classifyBindings.js";
import type { FieldInventory } from "../mastra/forms/catalog.js";

export interface RenderBindingsOpts {
  formId: string;
  taxYear: number;
  jurisdiction: string;
  formTitle: string;
  fields: FieldInventory[]; // catalog ordinal order
  bindings: ClassifiedBinding[];
  mustFile: { decisionKey: string; rationale: string };
}

const RULE_IMPORTS: Record<RuleName, string> = {
  lookupFact: "r.lookupFact",
  sumFacts: "r.sumFacts",
  tableLookupByDecision: "r.tableLookupByDecision",
  lookupDecision: "r.lookupDecision",
  decisionIfEquals: "r.decisionIfEquals",
  fromFields: "r.fromFields",
  constant: "r.constant",
  bracketLookup: "r.bracketLookup",
  taxTable: "r.taxTable",
  unsupported: "r.unsupported",
};

export function renderBindings(opts: RenderBindingsOpts): string {
  const bindingsByFieldId = new Map<string, ClassifiedBinding>();
  for (const b of opts.bindings) {
    if (!bindingsByFieldId.has(b.fieldId)) {
      bindingsByFieldId.set(b.fieldId, b);
    }
  }

  const out: string[] = [];

  out.push(`// AI-generated by Phase D — DO NOT hand-edit.`);
  out.push(`// Source: forms-pipeline/generateBindingsWorkflow`);
  out.push(`// Form: ${opts.formTitle} (${opts.formId}, tax year ${opts.taxYear})`);
  out.push(`// Generated at: ${new Date().toISOString()}`);
  out.push("");
  out.push(`import { bindMustFile, bindField } from "../engine.js";`);
  out.push(`import * as r from "../rules/index.js";`);
  out.push("");
  out.push(`// Wrapping all bind* calls inside an exported \`register\``);
  out.push(`// function gives consumers a tangible reference to import so the`);
  out.push(`// dev server / bundler can't tree-shake the side-effect away.`);
  out.push(`// Idempotent: bindings overwrite themselves when called twice.`);
  out.push(`export function register(): void {`);
  out.push(`  // must-file — ${opts.mustFile.rationale}`);
  out.push(
    `  bindMustFile(${quote(opts.formId)}, r.lookupDecision, ${indent(formatParams({ decisionKey: opts.mustFile.decisionKey }), 2)});`,
  );
  out.push("");

  let bound = 0;
  let missing = 0;
  for (const field of opts.fields) {
    const binding = bindingsByFieldId.get(field.fieldId);
    if (!binding) {
      // Field exists in the catalog but the classifier didn't emit a binding
      // — log a TODO so a human can fix it instead of silently dropping.
      out.push(`  // TODO: no binding emitted for ${field.fieldId} — "${field.label}"`);
      out.push("");
      missing++;
      continue;
    }
    const ruleSymbol = RULE_IMPORTS[binding.ruleName];
    if (!ruleSymbol) {
      out.push(
        `  // SKIP: unknown rule "${binding.ruleName}" for ${field.fieldId} — "${field.label}"`,
      );
      out.push("");
      missing++;
      continue;
    }
    out.push(`  // ${shortLabel(field.label)} (${field.category})`);
    out.push(`  //   why: ${binding.rationale}`);
    out.push(
      `  bindField(${quote(opts.formId)}, ${quote(field.fieldId)}, ${ruleSymbol}, ${indent(formatParams(binding.params), 2)});`,
    );
    out.push("");
    bound++;
  }

  out.push(`}`);
  out.push("");
  out.push(`// Summary: ${bound} field(s) bound, ${missing} unmapped.`);
  out.push("");
  return out.join("\n");
}

function indent(s: string, spaces: number): string {
  const pad = " ".repeat(spaces);
  return s
    .split("\n")
    .map((line, i) => (i === 0 ? line : pad + line))
    .join("\n");
}

function quote(s: string): string {
  return JSON.stringify(s);
}

// Stringify rule params with the formatting the generated file should use.
// JSON.stringify with indent=2 is good enough — we re-import this file as
// TypeScript and the engine validates params via Zod at registration time.
function formatParams(params: unknown): string {
  const json = JSON.stringify(params, null, 2);
  // Re-indent every line after the first by 0 — JSON.stringify aligns the
  // object's children to column 0 of each line; we want them indented under
  // the bindField call. Cheap: prefix all lines except the first with 2
  // spaces so the closing brace lines up at column 2.
  return json
    .split("\n")
    .map((line, i) => (i === 0 ? line : `  ${line}`))
    .join("\n");
}

function shortLabel(label: string, max = 80): string {
  const oneLine = label.replace(/\s+/g, " ").trim();
  return oneLine.length > max ? oneLine.slice(0, max) + "…" : oneLine;
}
