// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/state/ca/540/catalog.json
// Form: California Resident Income Tax Return (form-540, tax year 2025)
// Fields: 169
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface Form540 {
  /**  Check here if this is an AMENDED return. */
  "header.is_amended_return": boolean | undefined;
  /**  Fiscal year filers only. Enter month of year end. Enter month as two digits for year 2026. */
  "header.fiscal_year_end_month": string | undefined;
  /**  Your first name. */
  "header.first_name": string | undefined;
  /**  Middle Initial. */
  "header.middle_initial": string | undefined;
  /**  Last name. */
  "header.last_name": string | undefined;
  /**  Suffix. */
  "header.suffix": string | undefined;
  /**  Your Social Security Number (S S N) or Individual Taxpayer Identification Number (I T I N). */
  "header.ssn": string | undefined;
  /**  If joint tax return, spouse’s or Registered Domestic Partner's (R D P 's) first name. */
  "header.spouse_first_name": string | undefined;
  /**  Spouse's or R D P 's Middle Initial. */
  "header.spouse_middle_initial": string | undefined;
  /**  Spouse's or R D P 's Last name. */
  "header.spouse_last_name": string | undefined;
  /**  Spouse's or R D P 's Suffix. */
  "header.spouse_suffix": string | undefined;
  /**  Spouse's or R D P's S S N or I T I N. */
  "header.spouse_ssn": string | undefined;
  /**  Additional information (see instructions). */
  "header.additional_information": string | undefined;
  /**  Principal Business Activity code. */
  "header.principal_business_activity_code": string | undefined;
  /**  Street address (number and street) or Post Office Box. */
  "header.home_address": string | undefined;
  /**  Apartment number or suite number. */
  "header.apartment": string | undefined;
  /**  Private Mailbox. */
  "header.private_mailbox": string | undefined;
  /**  City (If you have a foreign address, see instructions). */
  "header.city": string | undefined;
  /**  State. Enter two letter State abbreviation. */
  "header.state": string | undefined;
  /**  Zip code. */
  "header.zip": string | undefined;
  /**  Foreign country name. */
  "header.foreign_country_name": string | undefined;
  /**  Foreign province/state/county. */
  "header.foreign_province_state_county": string | undefined;
  /**  Foreign postal code. */
  "header.foreign_postal_code": string | undefined;
  /**  Date of Birth. Your Date of Birth. Enter date as m m / d d / y y y y . */
  "header.date_of_birth": string | undefined;
  /**  Spouse's or R D P's Date of Birth. Enter date as m m / d d / y y y y . */
  "header.spouse_date_of_birth": string | undefined;
  /**  Prior Name. Your Prior Name (see instructions). */
  "header.prior_name": string | undefined;
  /**  Spouse's or R D P’s prior name (see instructions). */
  "header.spouse_prior_name": string | undefined;
  /**  Principal Residence. Enter your county at time of filing (see instructions). */
  "header.county_at_filing": string | undefined;
  /**  If your address above is the same as your principal/physical residence address at the time of filing, check this box. If not, enter below your principal/physical residence address at the time of filing. */
  "header.mailing_same_as_residence": boolean | undefined;
  /**  Street address (number and street) (If foreign address, see instructions.) */
  "header.residence_street_address": string | undefined;
  /**  Apartment number or suite number. */
  "header.residence_apartment": string | undefined;
  /**  City. */
  "header.residence_city": string | undefined;
  /**  State. Enter two letter State abbreviation. */
  "header.residence_state": string | undefined;
  /**  Zip code. */
  "header.residence_zip": string | undefined;
  /**  Filing status. If your California filing status is different from your federal filing status, check the box here. */
  "header.ca_filing_status_differs_from_federal": boolean | undefined;
  /**  1 . Single. */
  "header.filing_status": string | undefined;
  /**  Line 5. Enter year spouse or R D P died. */
  "header.spouse_rdp_year_of_death": string | undefined;
  /**  Line 5. See instructions. */
  "header.qualifying_surviving_spouse_instructions_ref": string | undefined;
  /**  Line 3. Enter spouse’s or R D P 's S S N or I T I N above and full name here. */
  "header.mfs_spouse_rdp_name_and_ssn": string | undefined;
  /**  Line 6. If someone can claim you (or your spouse or R D P) as a dependent, check the box here. See instructions. */
  "header.claimed_as_dependent": boolean | undefined;
  /**  Exemptions. For line 7, line 8, line 9, and line 10: Multiply the number you enter in the box by the pre-printed dollar amount for that line. Whole dollars only. Line 7. Personal: If you checked box 1, 3, or 4 above, enter 1 in the box. If you checked box 2 or 5, enter 2, in the box. If you checked the box on line 6, see instructions. */
  "line.7_personal_exemption_count": number | undefined;
  /**  Multiply the number you put in the line 7 box by $153. Enter this number into this field. Whole dollars only. */
  "line.7_personal_exemption_amount": number | undefined;
  /**  Line 8. Blind: If you (or your spouse / R D P ) are visually impaired, enter 1; if both are visually impaired, enter 2. See instructions. */
  "line.8_blind_exemption_count": number | undefined;
  /**  Multiply the number you put in the line 8 box by $153. Enter this number into this field. Whole dollars only. */
  "line.8_blind_exemption_amount": number | undefined;
  /**  Line 9. Senior: If you (or your spouse / R D P) are 65 or older, enter 1; if both are 65 or older, enter 2. See instructions. */
  "line.9_senior_exemption_count": number | undefined;
  /**  Multiply the number you put in the line 9 box by $153. Enter this number into this field. Whole dollars only. */
  "line.9_senior_exemption_amount": number | undefined;
  /**  Your name: */
  "page2.taxpayer_name": string | undefined;
  /**  Your S S N or I T I N . */
  "page2.taxpayer_ssn": string | undefined;
  /**  Line 10. Dependents. Do not include yourself or your spouse / R D P . Dependent One, first name */
  "dependents.dep1_first_name": string | undefined;
  /**  Dependent Two, first name */
  "dependents.dep2_first_name": string | undefined;
  /**  Dependent Three, first name */
  "dependents.dep3_first_name": string | undefined;
  /**  Dependent One, Last name */
  "dependents.dep1_last_name": string | undefined;
  /**  Dependent Two, Last name */
  "dependents.dep2_last_name": string | undefined;
  /**  Dependent Three, Last name */
  "dependents.dep3_last_name": string | undefined;
  /**  Dependent One, S S N. See instructions. */
  "dependents.dep1_ssn": string | undefined;
  /**  Dependent Two, S S N . See instructions. */
  "dependents.dep2_ssn": string | undefined;
  /**  Dependent Three, S S N . See instructions. */
  "dependents.dep3_ssn": string | undefined;
  /**  Dependent One. Dependent's relationship to you */
  "dependents.dep1_relationship": string | undefined;
  /**  Dependent Two, Dependent's relationship to you */
  "dependents.dep2_relationship": string | undefined;
  /**  Dependent Three, Dependent's relationship to you */
  "dependents.dep3_relationship": string | undefined;
  /**  Line 10. Total dependent exemptions */
  "line.10_dependent_exemption_count": number | undefined;
  /**  Multiply the number of total dependent exemptions you put in the line 10 box by $475. Enter this number into this field. Whole dollars only. */
  "line.10_dependent_exemption_amount": number | undefined;
  /**  Line 11. Exemption amount: Add line 7 through line 10. Transfer this amount to line 32. Whole dollars only. */
  "line.11_total_exemption_amount": number | undefined;
  /**  Taxable Income. Line 12. State wages from your federal Form or Forms W-2, box 16 . */
  "line.12_state_wages": number | undefined;
  /**  Line 13. Enter federal adjusted gross income (A G I) from federal Form 1040 or 1040-SR, line 11b. */
  "line.13_federal_agi": number | undefined;
  /**  Line 14. California adjustments – subtractions. Enter the amount from Schedule CA (540), Part 1, line 27, column B */
  "line.14_ca_adjustments_subtractions": number | undefined;
  /**  Line 15. Subtract line 14 from line 13. If less than zero, enter the result in parentheses. See instructions */
  "line.15_ca_agi_before_additions": number | undefined;
  /**  Line 16. California adjustments – additions. Enter the amount from Schedule CA (540), Part 1, line 27, column C */
  "line.16_ca_adjustments_additions": number | undefined;
  /**  Line 17.  California adjusted gross income. Combine line 15 and line 16. */
  "line.17_ca_agi": number | undefined;
  /**  Line 18. Enter the larger of your California itemized deductions from Schedule CA (540), Part Two, line 30, or Your California standard deduction shown for your filing status. California standard deduction is $5,706 for filing single, or for married or R D P filing separately. California standard deduction is $11,412 for filing married or R D P filing jointly, or for Head of household, or for Qualifying surviving spouse or R D P. If married or R D P filing separately or the box on line 6 is checked, STOP. See instructions. */
  "line.18_deductions": number | undefined;
  /**  Line 19. Subtract line 18 from line 17. This is your taxable income. If less than zero, enter 0. */
  "line.19_taxable_income": number | undefined;
  /**  Tax. Line 31. Tax.  Check the box if tax is from tax table. */
  "line.31_tax_from_tax_table": boolean | undefined;
  /**  Line 31. Tax.  Check the box if tax is from Tax Rate Schedule. */
  "line.31_tax_from_rate_schedule": boolean | undefined;
  /**  Line 31. Tax. Check the box if tax is from FTB 3800. */
  "line.31_tax_from_ftb_3800": boolean | undefined;
  /**  Line 31. Tax.  Check the box if tax is from FTB 3803. */
  "line.31_tax_from_ftb_3803": boolean | undefined;
  /**  Line 31. Tax amount. */
  "line.31_tax_amount": number | undefined;
  /**  Line 32. Exemption credits. Enter the amount from line 11. If your federal adjusted gross income is more than $252,203, see instructions. */
  "line.32_exemption_credits": number | undefined;
  /**  Line 33. Subtract line 32 from line 31. If less than zero, enter 0. */
  "line.33_tax_after_exemption_credits": number | undefined;
  /**  Line 34. Tax. See instructions.  Check the box if tax is from Schedule G-1. */
  "line.34_tax_from_schedule_g1": boolean | undefined;
  /**  Line 34.  Check the box if tax is from FTB 5870A. */
  "line.34_tax_from_ftb_5870a": boolean | undefined;
  /**  Line 34. Tax. See instructions. */
  "line.34_tax_amount": number | undefined;
  /**  Line 35. Add line 33 and line 34. */
  "line.35_total_tax_after_credits": number | undefined;
  /**  Special Credits. Line 40. Nonrefundable Child and Dependent Care Expenses Credit. See instructions. */
  "line.40_child_dependent_care_credit": number | undefined;
  /**  Line 43. Enter credit name */
  "line.43_credit_name": string | undefined;
  /**  Line 43. Enter credit code */
  "line.43_credit_code": string | undefined;
  /**  Line 43. Enter credit amount */
  "line.43_credit_amount": number | undefined;
  /**  Line 44. Enter credit name */
  "line.44_credit_name": string | undefined;
  /**  Line 44. Enter credit code */
  "line.44_credit_code": string | undefined;
  /**  Line 44. Enter credit amount */
  "line.44_credit_amount": number | undefined;
  /**  Line 45. To claim more than two credits, see instructions. Attach Schedule P (540). */
  "line.45_schedule_p_credits": number | undefined;
  /**  Line 46. Nonrefundable Renter’s Credit. See instructions. */
  "line.46_renters_credit": number | undefined;
  /**  Line 47. Add line 40 through line 46. These are your total credits. */
  "line.47_total_credits": number | undefined;
  /**  Line 48. Subtract line 47 from line 35. If less than zero, enter 0. */
  "line.48_tax_after_credits": number | undefined;
  /**  Other Taxes. Line 61. Alternative Minimum Tax. Attach Schedule P (540). */
  "line.61_alternative_minimum_tax": number | undefined;
  /**  Line 62. Behavioral Health Services Tax. See instructions. */
  "line.62_behavioral_health_services_tax": number | undefined;
  /**  Line 63. Other taxes and credit recapture. See instructions. */
  "line.63_other_taxes_credit_recapture": number | undefined;
  /**  Line 64. Add line 48, line 61, line 62, and line 63. This is your total tax. */
  "line.64_total_tax": number | undefined;
  /**  Payments. Line 71. California income tax withheld. See instructions. */
  "line.71_ca_income_tax_withheld": number | undefined;
  /**  Line 72. 2025 California estimated tax and other payments. See instructions. */
  "line.72_ca_estimated_tax_payments": number | undefined;
  /**  Line 73. Withholding (Form 592-B and/or Form 593). See instructions */
  "line.73_withholding_592b_593": number | undefined;
  /**  Line 74. Refundable Program 4.0 California Motion Picture and Television Production Credit. See instructions. */
  "line.74_motion_picture_production_credit": number | undefined;
  /**  Line 75. Earned Income Tax Credit (E I T C). See instructions. */
  "line.75_eitc": number | undefined;
  /**  Line 76. Young Child Tax Credit (YCTC). See instructions */
  "line.76_young_child_tax_credit": number | undefined;
  /**  Line 77. Foster Youth Tax Credit (FYTC). See instructions. */
  "line.77_foster_youth_tax_credit": number | undefined;
  /**  Line 78. Add line 71 through line 77. These are your total payments. See instructions. */
  "line.78_total_payments": number | undefined;
  /**  Use Tax. Line 91. Use Tax. Do not leave blank. See instructions. */
  "line.91_use_tax": number | undefined;
  /**  No use tax is owed. */
  "line.91_no_use_tax_owed": string | undefined;
  /**  Individual Shared Responsibility Penalty. Line 92. If you and your household had full-year health care coverage, check the box. See instructions. Medicare Part A or C coverage is qualifying health care coverage. If you did not check the box, see instructions. */
  "line.92_full_year_health_coverage": boolean | undefined;
  /**  Line 92. Individual Shared Responsibility (I S R) Penalty. See instructions. */
  "line.92_isr_penalty": number | undefined;
  /**  Overpaid Tax or Tax Due. Line 93 Payments balance. If line 78 is more than line 91, subtract line 91 from line 78 */
  "line.93_payments_balance": number | undefined;
  /**  Line 94. Use Tax balance. If line 91 is more than line 78, subtract line 78 from line 91 */
  "line.94_use_tax_balance": number | undefined;
  /**  Line 95. Payments after Individual Shared Responsibility penalty. If line 93 is more than line 92, subtract line 92 from line 93. */
  "line.95_payments_after_isr_penalty": number | undefined;
  /**  Line 96. Individual Shared Responsibility Penalty Balance. If line 92 is more than line 93, subtract line 93 from line 92. */
  "line.96_isr_penalty_balance": number | undefined;
  /**  Line 97. Overpaid tax. If line 95 is more than line 64, subtract line 64 from line 95. */
  "line.97_overpaid_tax": number | undefined;
  /**  Line 98. Amount of line 97 you want applied to your 2026 estimated tax. */
  "line.98_applied_to_2026_estimated_tax": number | undefined;
  /**  Line 99. Overpaid tax available this year. Subtract line 98 from line 97. */
  "line.99_overpaid_tax_available": number | undefined;
  /**  Line 100. Tax due. If line 95 is less than line 64, subtract line 95 from line 64. */
  "line.100_tax_due": number | undefined;
  /**  Contributions. Code 400. California Seniors Special Fund. See instructions. */
  "line.contrib_400_ca_seniors_special_fund": number | undefined;
  /**  Code 401. Alzheimer’s Disease and Related Dementia Voluntary Tax Contribution Fund. */
  "line.contrib_401_alzheimers_fund": number | undefined;
  /**  Code 403. Rare and Endangered Species Preservation Voluntary Tax Contribution Program. */
  "line.contrib_403_rare_endangered_species_fund": number | undefined;
  /**  Code 405. California Breast Cancer Research Voluntary Tax Contribution Fund */
  "line.contrib_405_breast_cancer_research_fund": number | undefined;
  /**  Code 406. California Firefighters’ Memorial Voluntary Tax Contribution Fund */
  "line.contrib_406_firefighters_memorial_fund": number | undefined;
  /**  Code 407. Emergency Food for Families Voluntary Tax Contribution Fund */
  "line.contrib_407_emergency_food_for_families_fund": number | undefined;
  /**  Code 408. California Peace Officer Memorial Foundation Voluntary Tax Contribution Fund */
  "line.contrib_408_peace_officer_memorial_fund": number | undefined;
  /**  Code 413. California Cancer Research Voluntary Tax Contribution Fund */
  "line.contrib_413_ca_cancer_research_fund": number | undefined;
  /**  Code 422. School Supplies for Homeless Children Voluntary Tax Contribution Fund. */
  "line.contrib_422_school_supplies_homeless_children_fund": number | undefined;
  /**  Code 423. State Parks Protection Fund and Parks Pass Purchase */
  "line.contrib_423_state_parks_protection_fund": number | undefined;
  /**  Code 424. Protect Our Coast and Oceans Voluntary Tax Contribution Fund */
  "line.contrib_424_protect_our_coast_and_oceans_fund": number | undefined;
  /**  Code 431. Prevention of Animal Homelessness and Cruelty Voluntary Tax Contribution Fund */
  "line.contrib_431_prevention_animal_homelessness_fund": number | undefined;
  /**  Code 438. California Senior Citizen Advocacy Voluntary Tax Contribution Fund */
  "line.contrib_438_senior_citizen_advocacy_fund": number | undefined;
  /**  Code 439. Native California Wildlife Rehabilitation Voluntary Tax Contribution Fund */
  "line.contrib_439_native_ca_wildlife_rehabilitation_fund": number | undefined;
  /**  Code 445. Mental Health Crisis Prevention Voluntary Tax Contribution Fund. */
  "line.contrib_445_mental_health_crisis_prevention_fund": number | undefined;
  /**  Code 447. California A L S Research Network Voluntary Tax Contribution Fund. */
  "line.contrib_447_ca_als_research_network_fund": number | undefined;
  /**  Code 448. California Pediatric Cancer Research Voluntary Tax Contribution Fund */
  "line.contrib_448_ca_pediatric_cancer_research_fund": number | undefined;
  /**  Code 449. Parkinson's Disease Research Voluntary Tax Contribution Fund */
  "line.contrib_449_parkinsons_disease_research_fund": number | undefined;
  /**  Line 110. Add amounts in code 400 through code 449. This is your total contribution */
  "line.110_total_contributions": number | undefined;
  /**  Amount You Owe. Line 111. Amount You Owe. If you do not have an amount on line 99, add line 94, line 96, line 100, and line 110. See instructions. Do not send cash.  You can mail payments to: Franchise Tax Board, Post Office Box, 942867, Sacramento, California, 94267-0001. To pay online, go to ftb.ca.gov/pay for more information. */
  "line.111_amount_you_owe": number | undefined;
  /**  Interest and Penalties. Line 112. Interest, late return penalties, and late payment penalties. */
  "line.112_interest_and_late_penalties": number | undefined;
  /**  FTB 5805 attached */
  "line.112_ftb_5805_attached": boolean | undefined;
  /**  FTB 5805F attached */
  "line.112_ftb_5805f_attached": boolean | undefined;
  /**  Line 113. Underpayment of estimated tax. */
  "line.113_underpayment_estimated_tax": number | undefined;
  /**  Line 114. Total amount due. See instructions. Enclose, but do not staple, any payment. */
  "line.114_total_amount_due": number | undefined;
  /**  Refund and Direct Deposit. Line 115. Refund or no amount due. Subtract the sum of line 110, line 112, and line 113 from line 99. See instructions. You can mail to: Franchise Tax Board, Post Office Box 942840, Sacramento, California, 94240-0001 */
  "line.115_refund_or_no_amount_due": number | undefined;
  /**  Line 116. Account type. Check only one box. Checking. */
  "line.116_account_type_checking": boolean | undefined;
  /**  Line 116. Enter the account’s routing number. */
  "line.116_routing_number": string | undefined;
  /**  Line 116. Account number. */
  "line.116_account_number": string | undefined;
  /**  Fill in the information to authorize direct deposit of your refund into one or two accounts. Do not attach a voided check or a deposit slip. See instructions. Have you verified the routing and account numbers? Use whole dollars only. All or the following amount of my refund (line 115) is authorized for direct deposit into the account shown below. Line 116. Direct deposit amount. */
  "line.116_direct_deposit_amount": number | undefined;
  /**  Line 116. Account type. Savings. */
  "line.116_account_type_savings": boolean | undefined;
  /**  Line 117. Secondary Account type. Check only one box. Checking. */
  "line.117_secondary_account_type_checking": boolean | undefined;
  /**  Line 117. Routing Number for secondary account. */
  "line.117_secondary_routing_number": string | undefined;
  /**  Line 117. Secondary Account number. */
  "line.117_secondary_account_number": string | undefined;
  /**  The remaining amount of my refund (line 115) is authorized for direct deposit into the account shown below. Line 117. Secondary Direct deposit amount. */
  "line.117_secondary_direct_deposit_amount": number | undefined;
  /**  Line 117. Secondary Account type.  Savings. */
  "line.117_secondary_account_type_savings": boolean | undefined;
  /**  Voter information. For voter registration information, check the box and go to sos.ca.gov/elections. See instructions. */
  "signing.voter_registration_info_request": boolean | undefined;
  /**  Yes — Do you want information on no-cost or low-cost health care coverage? */
  "signing.wants_health_care_coverage_info": string | undefined;
  /**  Organ Donor Election. By checking the applicable box you authorize written consent for Donate Life California to enroll you in the Donate Life California Organ and Tissue Donor Registry, and for the Franchise Tax Board to share limited information from your tax return with Donate Life California. If your individual information has changed since the last time you filed a tax return, and are already registered with Donate Life California, re-checking the box will send your most updated individual information to Donate Life California. If you do not check the box, Donate Life California will not enroll you in the registry at this time. To remove your name from the registry contact Donate Life California directly. For more information, see the Consent Language in the instructions. Primary taxpayer. */
  "signing.organ_donor_primary_taxpayer": boolean | undefined;
  /**  Spouse / R D P (if joint tax return). */
  "signing.organ_donor_spouse_rdp": boolean | undefined;
  /**  Date. Enter date signed. Enter date as m m / d d/ y y y y . */
  "signing.date_signed": string | undefined;
  /**  Your email address. Enter only one email address. */
  "signing.taxpayer_email": string | undefined;
  /**  Preferred phone number. */
  "signing.taxpayer_phone": string | undefined;
  /**  Print paid preparer’s name. */
  "signing.preparer_name": string | undefined;
  /**  Paid preparer’s phone number. */
  "signing.preparer_phone": string | undefined;
  /**  Firm’s name (or yours, if self-employed) */
  "signing.preparer_firm_name": string | undefined;
  /**  Preparer Tax Identification Number. */
  "signing.preparer_ptin": string | undefined;
  /**  Firm's address. */
  "signing.preparer_firm_address": string | undefined;
  /**  Firm's Federal Employer Identification Number. */
  "signing.preparer_firm_ein": string | undefined;
  /**  Yes */
  "signing.third_party_designee_authorized": string | undefined;
  /**  Print Third Party Designee’s Name */
  "signing.third_party_designee_name": string | undefined;
  /**  Third party designee's telephone number. */
  "signing.third_party_designee_phone": string | undefined;
}
