// AI-generated by forms:bind. Hand edits are allowed; mark them with
// `// MANUAL EDIT:` so they're easy to find + re-apply after a regen.
// Source: forms-pipeline/generateBindingsWorkflow
// Form: California Resident Income Tax Return (form-540, tax year 2025)
// Generated at: 2026-05-14T20:21:25.969Z

import { defineForm, stubZero, sum, floor } from "../../../engine.js";
import { SSN } from "../../../values.js";
import { lookupStandardDeduction } from "../../../data/standardDeduction.js";
import { lookupTax } from "../../../data/taxTable.js";
import type { Form540 } from "./types.js";
import type { Form540FilingInfo } from "./filingInfo.js";

// Wrapping defineForm inside a register() function lets callers
// import { register } and force the side-effectful registration once
// at startup. Idempotent — calling twice overwrites in place.
export function register(): void {
  defineForm<Form540, Form540FilingInfo>("form-540", {
    // The CA 540 must-file flag is driven by the decisions.scope.must_file_ca_540 AI decision, mirroring the federal must-file pattern for the state form.
    mustFile: (info) => info.mustFileCA540,

    bindings: {
      // Taxpayer first name maps directly to the identity.name.first fact.
      "header.first_name": (_, info) => info.taxpayerFirstName,
      // Taxpayer last name maps directly to the identity.name.last fact.
      "header.last_name": (_, info) => info.taxpayerLastName,
      // Taxpayer SSN/ITIN maps directly to the identity.ssn fact.
      "header.ssn": (_, info) => info.taxpayerSSN,
      // Direct 1-to-1 mapping from the taxpayer's street address fact to the mailing address field on Form 540.
      "header.home_address": (_, info) => info.homeAddressLine1,
      // Optional apartment/suite number from identity address fact; marked optional because most filers don't have one.
      "header.apartment": (_, info) => info.homeAddressApt,
      // Direct 1-to-1 mapping from the taxpayer's city fact to the city field on Form 540.
      "header.city": (_, info) => info.homeAddressCity,
      // Direct 1-to-1 mapping from the taxpayer's state abbreviation fact to the state field on Form 540.
      "header.state": (_, info) => info.homeAddressState,
      // Direct 1-to-1 mapping from the taxpayer's ZIP code fact to the ZIP field on Form 540.
      "header.zip": (_, info) => info.homeAddressZip,
      // Taxpayer's date of birth maps directly to identity.dob fact.
      "header.date_of_birth": (_, info) => info.taxpayerDateOfBirth,
      // CA 540 asks for the taxpayer's county at time of filing, which maps directly to identity.address.county (e.g. 'Alameda').
      "header.county_at_filing": (_, info) => info.homeAddressCounty,
      // Boolean checkbox checked when mailing address equals principal residence; driven by the mailing_same_as_principal_residence decision with matchValue=true.
      // MANUAL EDIT: original AI emit had `=== "true"` (string), should be `=== true` (boolean). Renderer fix landed; next regeneration will produce the correct shape natively.
      "header.mailing_same_as_residence": (_, info) => info.mailingSameAsResidence === true,
      // MANUAL EDIT: leave residence address fields blank when the
      // taxpayer ticked "mailing address is the same as principal
      // residence" — FTB convention is to fill the residence block only
      // when it differs from the mailing block. Repeating the mailing
      // address would just create visual noise.
      "header.residence_apartment": (_, info) =>
        info.mailingSameAsResidence ? undefined : info.homeAddressApt,
      "header.residence_city": (_, info) =>
        info.mailingSameAsResidence ? undefined : info.homeAddressCity,
      "header.residence_state": (_, info) =>
        info.mailingSameAsResidence ? undefined : info.homeAddressState,
      "header.residence_zip": (_, info) =>
        info.mailingSameAsResidence ? undefined : info.homeAddressZip,
      // Single_select radio group for CA filing status driven by the canonical filing_status decision; decisionIfEquals mode 1 maps the decision value to the matching catalog option.
      "header.filing_status": (_, info) => info.filingStatus,
      // MANUAL EDIT: AI originally returned the DOLLAR AMOUNT here to dodge
      // a multiply rule. With typed bindings we can do the multiply
      // cleanly — count widget gets the actual count (1 / 2), amount
      // widget gets count × $153.
      "line.7_personal_exemption_count": (_, info) =>
        info.filingStatus === "married_filing_jointly" ||
        info.filingStatus === "qualifying_surviving_spouse"
          ? 2
          : info.filingStatus
            ? 1
            : undefined,
      "line.7_personal_exemption_amount": (f) => {
        const count = f["line.7_personal_exemption_count"];
        return typeof count === "number" ? count * 153 : undefined;
      },
      // Direct read of taxpayer SSN/ITIN from identity facts — repeat of header SSN for page 2 carry-over.
      "page2.taxpayer_ssn": (_, info) => info.taxpayerSSN,
      // MANUAL EDIT: page 2 reprints the taxpayer's full name above the SSN.
      "page2.taxpayer_name": (_, info) =>
        info.taxpayerFirstName && info.taxpayerLastName
          ? `${info.taxpayerFirstName} ${info.taxpayerLastName}`
          : undefined,
      // MANUAL EDIT: source-of-tax checkbox for line 31. CA 540 instructs
      // the filer to mark which method computed line 31 (Tax Table, Tax
      // Rate Schedule, FTB 3800, FTB 3803). For sub-$100k income we use
      // the Tax Table; bind that source checkbox to true.
      "line.31_tax_from_tax_table": () => true,
      // MANUAL EDIT: Read CA subtractions/additions from Schedule CA Part
      // I line 27 (col B / col C). Cross-form ref returns undefined when
      // Schedule CA isn't filed for this scenario (e.g. Alex declined it
      // via the `must_file_schedule_ca: false` decision) — fall back to
      // 0, which matches the stubZero behavior that was here previously.
      "line.14_ca_adjustments_subtractions": (f) => {
        const v = f["schedule-ca.3.line.c27_subtractions"];
        return typeof v === "number" ? v : 0;
      },
      "line.16_ca_adjustments_additions": (f) => {
        const v = f["schedule-ca.3.line.c27_additions"];
        return typeof v === "number" ? v : 0;
      },
      // Line 11 = lines 7 + 8 + 9 + 10 exemption amounts; blind/senior/dependent lines are unsupported and treated as 0.
      "line.11_total_exemption_amount": (f) => sum(f["line.7_personal_exemption_amount"], f["line.8_blind_exemption_amount"], f["line.9_senior_exemption_amount"], f["line.10_dependent_exemption_amount"]),
      // Sum of W-2 box 16 (state wages) across all employers.
      "line.12_state_wages": (_, info) => info.w2StateWages,
      // Cross-form reference: CA 540 line 13 = federal Form 1040 line 11b (AGI).
      "line.13_federal_agi": (f) => sum(f["form-1040.line.11b"]),
      // Line 15 = line 13 − line 14 per form instructions; unsupported line 14 contributes 0.
      "line.15_ca_agi_before_additions": (f) => sum(f["line.13_federal_agi"], f["line.14_ca_adjustments_subtractions"] === undefined ? 0 : -f["line.14_ca_adjustments_subtractions"]),
      // California AGI = line 15 (pre-additions subtotal) + line 16 (CA additions); line 16 is unsupported and treated as 0.
      "line.17_ca_agi": (f) => sum(f["line.15_ca_agi_before_additions"], f["line.16_ca_adjustments_additions"]),
      // MANUAL EDIT: Read CA deduction from Schedule CA Part II line 30
      // (the larger-of std-vs-itemized selector) when Schedule CA is
      // filed. Falls back to the direct standard deduction lookup when
      // it isn't (Alex-class W-2-only filer who declined Schedule CA).
      // Both paths produce the same value for non-itemizing filers.
      "line.18_deductions": (f, info) => {
        const fromScheduleCA =
          f["schedule-ca.5.page2.total_itemized_30_standard_or_itemized"];
        if (typeof fromScheduleCA === "number") return fromScheduleCA;
        return info.filingStatus
          ? lookupStandardDeduction("state-ca", 2025, info.filingStatus)
          : undefined;
      },
      // CA taxable income is CA AGI (line 17) minus deductions (line 18), floored at zero.
      "line.19_taxable_income": (f) => floor(0, sum(f["line.17_ca_agi"], f["line.18_deductions"] === undefined ? 0 : -f["line.18_deductions"])),
      // CA line 31 tax is computed from the California Tax Table using line 19 taxable income and filing status; tableId=ca-2025 to use the CA table (not the federal one).
      "line.31_tax_amount": (f, info) => {
        if (!info.filingStatus) return undefined;
        const income = f["line.19_taxable_income"];
        if (typeof income !== "number") return undefined;
        const r = lookupTax("ca-2025", income, info.filingStatus);
        return r.ok ? r.tax : undefined;
      },
      // Exemption credits on line 32 equal the total exemption amount from line 11 per instructions.
      "line.32_exemption_credits": (f) => sum(f["line.11_total_exemption_amount"]),
      // Tax after exemption credits = line 31 tax minus line 32 exemption credits, floor at zero.
      "line.33_tax_after_exemption_credits": (f) => floor(0, sum(f["line.31_tax_amount"], f["line.32_exemption_credits"] === undefined ? 0 : -f["line.32_exemption_credits"])),
      // Sum of line 33 (tax after exemption credits) and line 34 (Schedule G-1 / FTB 5870A tax); line 34 is unsupported so engine treats it as 0.
      "line.35_total_tax_after_credits": (f) => sum(f["line.33_tax_after_exemption_credits"], f["line.34_tax_amount"]),
      // Sum of lines 40 through 46 per form instructions (lines 41 and 42 do not appear in the inventory, so treated as 0 by the engine's partial-input contract).
      "line.47_total_credits": (f) => sum(f["line.40_child_dependent_care_credit"], f["line.43_credit_amount"], f["line.44_credit_amount"], f["line.45_schedule_p_credits"], f["line.46_renters_credit"]),
      // Line 35 minus line 47; floor of 0 per instructions ('if less than zero, enter 0').
      "line.48_tax_after_credits": (f) => floor(0, sum(f["line.35_total_tax_after_credits"], f["line.47_total_credits"] === undefined ? 0 : -f["line.47_total_credits"])),
      // Sum of lines 48, 61, 62, and 63 per form instructions; unsupported lines treated as 0 by the engine's partial-input contract.
      "line.64_total_tax": (f) => sum(f["line.48_tax_after_credits"], f["line.61_alternative_minimum_tax"], f["line.62_behavioral_health_services_tax"], f["line.63_other_taxes_credit_recapture"]),
      // Sum of W-2 box 17 (state income tax withheld) across all employers — this is California income tax withheld at source.
      "line.71_ca_income_tax_withheld": (_, info) => info.w2StateWithholding,
      // Line 78 = sum of lines 71–77 (CA withholding + estimated payments + 592-B/593 withholding + refundable credits); unsupported terms treated as 0 by engine.
      "line.78_total_payments": (f) => sum(f["line.71_ca_income_tax_withheld"], f["line.72_ca_estimated_tax_payments"], f["line.73_withholding_592b_593"], f["line.74_motion_picture_production_credit"], f["line.75_eitc"], f["line.76_young_child_tax_credit"], f["line.77_foster_youth_tax_credit"]),
      // Line 91 is the taxpayer's self-reported use tax owed amount, read directly from the use_tax fact.
      "line.91_use_tax": (_, info) => info.useTaxOwed,
      // MANUAL EDIT: was a TODO in the generated output because the
      // useTaxZeroReason slot didn't exist yet on Form540FilingInfo. Slot
      // added; binding passes the decision value through to the line 91
      // radio group ("no_use_tax_owed" or "paid_directly_to_cdtfa").
      "line.91_no_use_tax_owed": (_, info) => info.useTaxZeroReason,
      // Boolean checkbox checked when taxpayer and household had minimum essential coverage all year; maps directly to health_coverage.full_year_mec fact.
      "line.92_full_year_health_coverage": (_, info) => info.fullYearMEC,
      // Line 93 = line 78 (total payments) minus line 91 (use tax), floored at 0 per instructions.
      "line.93_payments_balance": (f) => floor(0, sum(f["line.78_total_payments"], f["line.91_use_tax"] === undefined ? 0 : -f["line.91_use_tax"])),
      // Use tax balance: line 91 minus line 78, floor 0 per instructions (only when line 91 > line 78).
      "line.94_use_tax_balance": (f) => floor(0, sum(f["line.91_use_tax"], f["line.78_total_payments"] === undefined ? 0 : -f["line.78_total_payments"])),
      // Payments after ISR penalty: line 93 minus line 92, floor 0 per instructions.
      "line.95_payments_after_isr_penalty": (f) => floor(0, sum(f["line.93_payments_balance"], f["line.92_isr_penalty"] === undefined ? 0 : -f["line.92_isr_penalty"])),
      // ISR penalty balance: line 92 minus line 93, floor 0 per instructions (only when line 92 > line 93).
      "line.96_isr_penalty_balance": (f) => floor(0, sum(f["line.92_isr_penalty"], f["line.93_payments_balance"] === undefined ? 0 : -f["line.93_payments_balance"])),
      // Overpaid tax: line 95 minus line 64, floor 0 per instructions.
      "line.97_overpaid_tax": (f) => floor(0, sum(f["line.95_payments_after_isr_penalty"], f["line.64_total_tax"] === undefined ? 0 : -f["line.64_total_tax"])),
      // Overpaid tax available this year: line 97 minus line 98 (amount applied to 2026 estimated tax), floor 0.
      "line.99_overpaid_tax_available": (f) => floor(0, sum(f["line.97_overpaid_tax"], f["line.98_applied_to_2026_estimated_tax"] === undefined ? 0 : -f["line.98_applied_to_2026_estimated_tax"])),
      // Tax due: line 64 minus line 95, floor 0 per instructions.
      "line.100_tax_due": (f) => floor(0, sum(f["line.64_total_tax"], f["line.95_payments_after_isr_penalty"] === undefined ? 0 : -f["line.95_payments_after_isr_penalty"])),
      // Line 110 = sum of all contribution lines (codes 400 through 449); all contribution terms are in the inventory so fromFields partial-sum contract applies (unsupported terms treated as 0).
      "line.110_total_contributions": (f) => sum(f["line.contrib_400_ca_seniors_special_fund"], f["line.contrib_401_alzheimers_fund"], f["line.contrib_403_rare_endangered_species_fund"], f["line.contrib_405_breast_cancer_research_fund"], f["line.contrib_406_firefighters_memorial_fund"], f["line.contrib_407_emergency_food_for_families_fund"], f["line.contrib_408_peace_officer_memorial_fund"], f["line.contrib_413_ca_cancer_research_fund"], f["line.contrib_422_school_supplies_homeless_children_fund"], f["line.contrib_423_state_parks_protection_fund"], f["line.contrib_424_protect_our_coast_and_oceans_fund"], f["line.contrib_431_prevention_animal_homelessness_fund"], f["line.contrib_438_senior_citizen_advocacy_fund"], f["line.contrib_439_native_ca_wildlife_rehabilitation_fund"], f["line.contrib_445_mental_health_crisis_prevention_fund"], f["line.contrib_447_ca_als_research_network_fund"], f["line.contrib_448_ca_pediatric_cancer_research_fund"], f["line.contrib_449_parkinsons_disease_research_fund"]),
      // Per instructions: if no amount on line 99, amount owed = line 94 + line 96 + line 100 + line 110.
      "line.111_amount_you_owe": (f) => sum(f["line.94_use_tax_balance"], f["line.96_isr_penalty_balance"], f["line.100_tax_due"], f["line.110_total_contributions"]),
      // Total amount due is line 100 (tax due) plus contributions (110), interest/penalties (112), and underpayment penalty (113).
      "line.114_total_amount_due": (f) => floor(0, sum(f["line.100_tax_due"], f["line.110_total_contributions"], f["line.112_interest_and_late_penalties"], f["line.113_underpayment_estimated_tax"])),
      // Refund or no amount due: line 99 minus contributions (110), interest/penalties (112), and underpayment penalty (113).
      "line.115_refund_or_no_amount_due": (f) => floor(0, sum(f["line.99_overpaid_tax_available"], f["line.110_total_contributions"] === undefined ? 0 : -f["line.110_total_contributions"], f["line.112_interest_and_late_penalties"] === undefined ? 0 : -f["line.112_interest_and_late_penalties"], f["line.113_underpayment_estimated_tax"] === undefined ? 0 : -f["line.113_underpayment_estimated_tax"])),
      // Taxpayer email address from identity facts; marked optional since Thom auto-populates it from Supabase auth.
      "signing.taxpayer_email": (_, info) => info.taxpayerEmail,
      // Taxpayer preferred phone number from identity facts collected during intake.
      "signing.taxpayer_phone": (_, info) => info.taxpayerPhone,
    },

    // MANUAL EDIT: page-2 SSN widget has maxLength 11 and FTB convention
    // is the dashed presentation ("123-45-6789"). Page-1 widget keeps the
    // default digits-only render. Cast at the call site because the
    // typed binding declares this slot as `string` (matching the catalog's
    // valueType=text) — SSN.format is the right runtime call regardless.
    formatters: {
      "page2.taxpayer_ssn": (value) =>
        SSN.format(value as Parameters<typeof SSN.format>[0]),
    },

    unsupported: {
      "header.is_amended_return": "No amended-return scenario yet — we don't model Schedule X / amended filing triggers.",
      "header.fiscal_year_end_month": "Fiscal year filers only — MVP only supports calendar-year (Jan–Dec) filers; no fiscal-year scenario ingested.",
      "header.middle_initial": "No identity.name.middle_initial fact exists; identity.name.first holds the full first name which would corrupt a single-character field.",
      "header.suffix": "No identity.name.suffix fact exists in the available fact catalog.",
      "header.spouse_first_name": "No MFJ/RDP scenario yet — spouse identity facts are not ingested.",
      "header.spouse_middle_initial": "No MFJ/RDP scenario yet — spouse identity facts are not ingested.",
      "header.spouse_last_name": "No MFJ/RDP scenario yet — spouse identity facts are not ingested.",
      "header.spouse_suffix": "No MFJ/RDP scenario yet — spouse suffix field unsupported until we ingest spouse identity facts.",
      "header.spouse_ssn": "No MFJ/RDP scenario yet — spouse SSN/ITIN field unsupported until we ingest spouse identity facts.",
      "header.additional_information": "Free-text supplemental field with no defined fact or decision mapping; rarely populated and scenario-dependent.",
      "header.principal_business_activity_code": "No self-employment / business-activity fact ingested yet; this field is only relevant for business-income filers.",
      "header.private_mailbox": "No private mailbox fact key exists in the identity schema; this is an edge-case address field not yet modeled.",
      "header.foreign_country_name": "No foreign address facts are ingested; MVP supports domestic US addresses only. This field is only relevant for taxpayers with a foreign mailing address.",
      "header.foreign_province_state_county": "No foreign address facts are ingested; MVP supports domestic US addresses only.",
      "header.foreign_postal_code": "No foreign address facts are ingested; MVP supports domestic US addresses only.",
      "header.spouse_date_of_birth": "No MFJ/spouse scenario ingested; spouse date of birth has no corresponding fact key.",
      "header.prior_name": "No prior-name fact key exists in the identity category; taxpayer name-change scenario not modeled.",
      "header.spouse_prior_name": "No MFJ scenario ingested, and no prior-name fact key exists for the spouse.",
      "header.residence_street_address": "No separate principal-residence street address fact exists; the identity address facts represent the mailing address. A distinct principal-residence address scenario has no ingestion path yet.",
      "header.ca_filing_status_differs_from_federal": "No scenario yet where CA filing status differs from federal (e.g. RDP adjustments, community property MFS). MVP only handles matching statuses; this checkbox would require a dedicated ca_filing_status_differs decision.",
      "header.spouse_rdp_year_of_death": "No scenario yet for qualifying surviving spouse/RDP with a deceased spouse — year-of-death fact not ingested.",
      "header.qualifying_surviving_spouse_instructions_ref": "Static instructions reference label on the form; no computable value — no scenario for QSS filing status with deceased spouse data ingested.",
      "header.mfs_spouse_rdp_name_and_ssn": "No MFS scenario yet — spouse/RDP name and SSN for married filing separately not ingested.",
      "header.claimed_as_dependent": "No scenario yet where the taxpayer themselves is claimed as a dependent by another person — no fact or decision models this.",
      "line.8_blind_exemption_count": "No blind/visual-impairment fact ingested yet. Need a 'disability.blind' or similar fact category before this can be computed.",
      "line.8_blind_exemption_amount": "Depends on line 8 blind exemption count which has no ingested fact path yet.",
      "line.9_senior_exemption_count": "While identity.dob exists for the primary taxpayer, computing the senior count (1 or 2) also requires spouse DOB for MFJ scenarios, and no MFJ/spouse-DOB ingestion path exists yet. Deferring until a senior-taxpayer scenario is built.",
      "line.9_senior_exemption_amount": "Depends on line 9 senior exemption count which is unsupported until a senior/MFJ scenario is ingested.",
      "dependents.dep1_first_name": "No dependent data ingestion path exists yet. Need a dependents fact category before any dependent fields can be populated.",
      "dependents.dep2_first_name": "No dependent data ingestion path exists yet. Need a dependents fact category before any dependent fields can be populated.",
      "dependents.dep3_first_name": "No dependent data ingestion path yet — dependent name/SSN/relationship fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep1_last_name": "No dependent data ingestion path yet — dependent name/SSN/relationship fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep2_last_name": "No dependent data ingestion path yet — dependent name/SSN/relationship fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep3_last_name": "No dependent data ingestion path yet — dependent name/SSN/relationship fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep1_ssn": "No dependent data ingestion path yet — dependent SSN fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep2_ssn": "No dependent data ingestion path yet — dependent SSN fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep3_ssn": "No dependent data ingestion path yet — dependent SSN fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep1_relationship": "No dependent data ingestion path yet — dependent relationship fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep2_relationship": "No dependent data ingestion path yet — dependent relationship fields require a dependent-with-exemption scenario to be built.",
      "dependents.dep3_relationship": "No dependent data ingestion path yet — dependent relationship fields require a dependent-with-exemption scenario to be built.",
      "line.10_dependent_exemption_count": "No dependent-data ingestion path yet — dependent count requires building dependent fact ingestion. Downstream sum (line 11) treats this as 0.",
      "line.10_dependent_exemption_amount": "No dependent-data ingestion path yet — dependent exemption amount ($475 × count) requires building dependent fact ingestion. Downstream sum (line 11) treats this as 0.",
      "line.31_tax_from_rate_schedule": "Checkbox indicating tax was computed from the Tax Rate Schedule (income > $100k). No engine decision tracks which computation method was used; unsupported until a method-selector decision is built.",
      "line.31_tax_from_ftb_3800": "Checkbox indicating tax includes FTB 3800 (tax on child's unearned income). No FTB 3800 scenario or fact-ingestion path exists yet.",
      "line.31_tax_from_ftb_3803": "Checkbox indicating tax includes FTB 3803 (parent's election to report child's interest/dividend income). No FTB 3803 scenario or fact-ingestion path exists yet.",
      "line.34_tax_from_schedule_g1": "Checkbox indicating line 34 tax is from Schedule G-1 (lump-sum distributions). No Schedule G-1 scenario or fact-ingestion path exists yet.",
      "line.34_tax_from_ftb_5870a": "Checkbox indicating line 34 tax is from FTB 5870A (tax on accumulation distribution of trusts). No FTB 5870A scenario or fact-ingestion path exists yet.",
      "line.34_tax_amount": "Line 34 is tax from Schedule G-1 (lump-sum distributions) or FTB 5870A (tax on accumulation distribution of trusts). No ingestion path exists for these scenarios yet — requires Schedule G-1 or FTB 5870A data.",
      "line.40_child_dependent_care_credit": "CA nonrefundable Child and Dependent Care Expenses Credit (Code 232) requires FTB 3506 data and dependent/care-expense ingestion. No dependent or child-care-expense scenario built yet.",
      "line.43_credit_name": "Free-text credit name for an additional special credit on line 43. No ingestion path for user-supplied special credits (e.g., CA Competes, PTE, etc.) exists yet.",
      "line.43_credit_code": "Credit code for additional special credit on line 43. No ingestion path for user-supplied special credits exists yet.",
      "line.43_credit_amount": "Credit amount for additional special credit on line 43. No ingestion path for user-supplied special credits (requires supporting schedules/FTB forms) exists yet.",
      "line.44_credit_name": "Free-text credit name for an additional special credit on line 44. No ingestion path for user-supplied special credits exists yet.",
      "line.44_credit_code": "Credit code for additional special credit on line 44. No ingestion path for user-supplied special credits exists yet.",
      "line.44_credit_amount": "Credit amount for additional special credit on line 44. No ingestion path for user-supplied special credits (requires supporting schedules/FTB forms) exists yet.",
      "line.45_schedule_p_credits": "Line 45 is for additional credits claimed via Schedule P (540). No ingestion path for Schedule P credits exists yet — would require a separate Schedule P catalog and credit data.",
      "line.46_renters_credit": "Nonrefundable Renter's Credit eligibility requires income limits, rent paid, landlord details, and rental address data — no fact ingestion path or scenario built for this yet.",
      "line.61_alternative_minimum_tax": "CA Alternative Minimum Tax requires Schedule P (540) computation — no Schedule P ingestion or AMT scenario built yet.",
      "line.62_behavioral_health_services_tax": "Behavioral Health Services Tax requires separate computation based on high-income thresholds and specific instructions — no ingestion path or scenario built yet.",
      "line.63_other_taxes_credit_recapture": "Other taxes and credit recapture (e.g. lump-sum distributions, credit recapture from FTB forms) require special form attachments — no ingestion path or scenario built yet.",
      "line.72_ca_estimated_tax_payments": "California estimated tax payments and other prepayments are not captured in any current fact ingestion category — no scenario built for this yet.",
      "line.73_withholding_592b_593": "Form 592-B and 593 withholding (partnership/LLC/real estate withholding) requires separate fact ingestion — no ingestion path or scenario built yet.",
      "line.74_motion_picture_production_credit": "CA Motion Picture and Television Production Credit (FTB 3541) requires allocation/certification data from the California Film Commission — no ingestion path or scenario built yet.",
      "line.75_eitc": "CA EITC requires earned income, qualifying children counts and SSNs, and a separate FTB 3514 computation — no EITC-specific ingestion or decision built yet.",
      "line.76_young_child_tax_credit": "CA Young Child Tax Credit requires a qualifying child under age 6 and EITC eligibility — no dependent or YCTC ingestion/scenario built yet.",
      "line.77_foster_youth_tax_credit": "CA Foster Youth Tax Credit requires foster care history facts (aged out of foster care, etc.) — no foster-youth ingestion or scenario built yet.",
      "line.92_isr_penalty": "ISR penalty amount requires FTB 3853 computation (months without coverage × penalty rate per household member) — no FTB 3853 ingestion or partial-coverage scenario built yet.",
      "line.98_applied_to_2026_estimated_tax": "Taxpayer-elected amount applied to 2026 estimated tax — this is a discretionary user input with no fact or decision key; we'd need an estimated-tax-election intake flow to support it.",
      "line.contrib_400_ca_seniors_special_fund": "Voluntary charitable contribution — taxpayer-elected dollar amount with no fact or decision key. Would require a voluntary-contributions intake flow and senior-status verification to support.",
      "line.contrib_401_alzheimers_fund": "Voluntary charitable contribution — taxpayer-elected dollar amount with no fact or decision key. Would require a voluntary-contributions intake flow to support.",
      "line.contrib_403_rare_endangered_species_fund": "Voluntary charitable contribution — taxpayer-elected dollar amount with no fact or decision key. Would require a voluntary-contributions intake flow to support.",
      "line.contrib_405_breast_cancer_research_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_406_firefighters_memorial_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_407_emergency_food_for_families_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_408_peace_officer_memorial_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_413_ca_cancer_research_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_422_school_supplies_homeless_children_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_423_state_parks_protection_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_424_protect_our_coast_and_oceans_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_431_prevention_animal_homelessness_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_438_senior_citizen_advocacy_fund": "Voluntary contribution amount elected by the taxpayer — no fact ingestion path exists for charitable donation elections on CA 540 contribution lines.",
      "line.contrib_439_native_ca_wildlife_rehabilitation_fund": "Voluntary charitable contribution — no fact ingestion path for taxpayer donation amounts; unsupported until a voluntary-contributions scenario is built.",
      "line.contrib_445_mental_health_crisis_prevention_fund": "Voluntary charitable contribution — no fact ingestion path for taxpayer donation amounts; unsupported until a voluntary-contributions scenario is built.",
      "line.contrib_447_ca_als_research_network_fund": "Voluntary charitable contribution — no fact ingestion path for taxpayer donation amounts; unsupported until a voluntary-contributions scenario is built.",
      "line.contrib_448_ca_pediatric_cancer_research_fund": "Voluntary charitable contribution — no fact ingestion path for taxpayer donation amounts; unsupported until a voluntary-contributions scenario is built.",
      "line.contrib_449_parkinsons_disease_research_fund": "Voluntary charitable contribution — no fact ingestion path for taxpayer donation amounts; unsupported until a voluntary-contributions scenario is built.",
      "line.112_interest_and_late_penalties": "Interest and penalty calculations require FTB-computed penalty amounts based on filing date, payment history, and underpayment rules — no fact ingestion path or scenario for this yet.",
      "line.112_ftb_5805_attached": "FTB 5805 attachment flag depends on underpayment of estimated tax — no scenario or decision models whether this form is attached.",
      "line.112_ftb_5805f_attached": "FTB 5805F attachment flag depends on underpayment of estimated tax for farmers/fishermen — no scenario or decision models whether this form is attached.",
      "line.113_underpayment_estimated_tax": "Underpayment of estimated tax penalty requires FTB 5805/5805F worksheet calculations comparing prior-year liability, withholding, and estimated payments — no scenario or fact ingestion path exists for this yet.",
      "line.116_account_type_checking": "Bank account type (checking) is taxpayer-provided direct-deposit preference — no fact ingestion path built for banking details.",
      "line.116_routing_number": "Bank routing number is taxpayer-provided direct-deposit preference — no fact ingestion path built for banking details.",
      "line.116_account_number": "Bank account number is taxpayer-provided direct-deposit preference — no fact ingestion path built for banking details.",
      "line.116_direct_deposit_amount": "Direct deposit split amount is a taxpayer allocation choice (all or partial of line 115) — no fact or decision models this preference yet.",
      "line.116_account_type_savings": "Bank account type (savings) is taxpayer-provided direct-deposit preference — no fact ingestion path built for banking details.",
      "line.117_secondary_account_type_checking": "Secondary bank account type (checking) is a taxpayer-provided direct-deposit split preference — no fact ingestion path built for banking details.",
      "line.117_secondary_routing_number": "Secondary bank routing number is a taxpayer-provided direct-deposit split detail — no fact ingestion path built for banking details.",
      "line.117_secondary_account_number": "No fact key exists for a secondary bank account number; bank account data is not ingested.",
      "line.117_secondary_direct_deposit_amount": "No fact or decision captures the taxpayer's chosen split amount for a secondary direct deposit account.",
      "line.117_secondary_account_type_savings": "No fact key exists for secondary bank account type (checking vs. savings); bank account data is not ingested.",
      "signing.voter_registration_info_request": "Voluntary voter registration opt-in checkbox — no fact or decision models this taxpayer preference.",
      "signing.wants_health_care_coverage_info": "Voluntary single_select asking if taxpayer wants health care coverage info — no decision models this preference.",
      "signing.organ_donor_primary_taxpayer": "Voluntary organ donor registry opt-in for primary taxpayer — no fact or decision models this election.",
      "signing.organ_donor_spouse_rdp": "Voluntary organ donor registry opt-in for spouse/RDP — no MFJ scenario built and no fact models this election.",
      "signing.date_signed": "Signing date is set at the moment the taxpayer executes the return — no static fact captures it and it is not a fixed value.",
      "signing.preparer_name": "Paid preparer block — no paid-preparer ingestion scenario built yet. Self-filed returns leave this blank.",
      "signing.preparer_phone": "Paid preparer block — no paid-preparer ingestion scenario built yet. Self-filed returns leave this blank.",
      "signing.preparer_firm_name": "Paid preparer block — no paid-preparer ingestion scenario built yet. Self-filed returns leave this blank.",
      "signing.preparer_ptin": "Paid preparer block — no paid-preparer ingestion scenario built yet. Self-filed returns leave this blank.",
      "signing.preparer_firm_address": "Paid preparer block — no paid-preparer ingestion scenario built yet. Self-filed returns leave this blank.",
      "signing.preparer_firm_ein": "Paid preparer block — no paid-preparer ingestion scenario built yet. Self-filed returns leave this blank.",
      "signing.third_party_designee_authorized": "Third-party designee authorization — no designee ingestion scenario built yet. Most self-filed returns do not authorize a third-party designee.",
      "signing.third_party_designee_name": "Third-party designee block — no designee ingestion scenario built yet.",
      "signing.third_party_designee_phone": "Third-party designee block — no designee ingestion scenario built yet.",
    },

    todos: {
    },

  });
}

// Summary: 49 binding(s), 2 todo(s), 118 unsupported, 0 unbound.
// Confidence: 168 high, 1 medium, 0 low.
