// AI-generated by forms:bind, then hand-edited. Manual edits marked
// `// MANUAL EDIT:` so they survive the next regeneration.
// Source: forms-pipeline/generateBindingsWorkflow
// Form: Form 8959 — Additional Medicare Tax (form-8959, tax year 2025)
// Generated at: 2026-05-27T16:41:25.598Z

import { defineForm, sum, floor } from "../../engine.js";
import { SSN } from "../../values.js";
import type { Form8959 } from "./types.js";
import type { Form8959FilingInfo } from "./filingInfo.js";

// Per-status thresholds reused across Parts I, II, and III. Same table,
// different cells on the form (lines 5, 9, 15). The IRS reuses the same
// numbers; only Part II adjusts via line 11 (threshold reduced by wages).
const ADDITIONAL_MEDICARE_THRESHOLDS: Record<string, number> = {
  single: 200000,
  married_filing_jointly: 250000,
  married_filing_separately: 125000,
  head_of_household: 200000,
  qualifying_surviving_spouse: 200000,
};

export function register(): void {
  defineForm<Form8959, Form8959FilingInfo>("form-8959", {
    // MANUAL EDIT: form-scoped must-file (AI defaulted to mustFileFederal).
    mustFile: (info) => info.mustFile8959,

    bindings: {
      // MANUAL EDIT: no combined-name fact; concatenate first + last
      // (same pattern as Schedule A / Schedule D / 8949).
      "0.header.taxpayer_name": (_, info) =>
        info.taxpayerFirstName && info.taxpayerLastName
          ? `${info.taxpayerFirstName} ${info.taxpayerLastName}`
          : undefined,
      "0.header.ssn": (_, info) => info.taxpayerSSN,
      // MANUAL EDIT: routed to FilingInfo slot (sum of W-2 box 5).
      "0.line.1_medicare_wages_tips": (_, info) => info.w2MedicareWagesTotal,
      // Line 4 = 1 + 2 + 3. Lines 2/3 unsupported; engine treats undefined
      // as 0 in sum(), so line 4 = line 1 for Marcus.
      "0.line.4_total_medicare_wages": (f) =>
        sum(
          f["0.line.1_medicare_wages_tips"],
          f["0.line.2_unreported_tips"],
          f["0.line.3_wages_form_8919"],
        ),
      // Filing-status threshold table. Lines 5, 9, 15 all use the same
      // table — three reads, one source of truth (top of file).
      "0.line.5_filing_status_threshold_wages": (_, info) =>
        info.filingStatus
          ? ADDITIONAL_MEDICARE_THRESHOLDS[info.filingStatus]
          : undefined,
      // Line 6 = max(0, line 4 − line 5).
      "0.line.6_excess_medicare_wages": (f) =>
        floor(
          0,
          sum(
            f["0.line.4_total_medicare_wages"],
            f["0.line.5_filing_status_threshold_wages"] === undefined
              ? 0
              : -f["0.line.5_filing_status_threshold_wages"],
          ),
        ),
      // MANUAL EDIT: line 7 = line 6 × 0.9%, rounded UP to whole dollars
      // per the project's Math.ceil convention (CLAUDE.md). Engine has no
      // multiply rule, so inline.
      "0.line.7_additional_medicare_tax_wages": (f) => {
        const line6 = f["0.line.6_excess_medicare_wages"];
        if (typeof line6 !== "number" || line6 === 0) return undefined;
        return Math.ceil(line6 * 0.009);
      },
      // MANUAL EDIT: Part II (lines 9–13) all gate on line 8 (SE income)
      // being defined. When the taxpayer has no SE income — Marcus's
      // case — Part II is left blank, matching the CPA convention. SE
      // ingest path isn't built; line 8 stays unsupported, so the gate
      // currently suppresses every Part II line.
      "0.line.9_filing_status_threshold_se": (f, info) => {
        if (f["0.line.8_self_employment_income"] === undefined) return undefined;
        return info.filingStatus
          ? ADDITIONAL_MEDICARE_THRESHOLDS[info.filingStatus]
          : undefined;
      },
      "0.line.10_medicare_wages_from_line4": (f) => {
        if (f["0.line.8_self_employment_income"] === undefined) return undefined;
        return f["0.line.4_total_medicare_wages"];
      },
      "0.line.11_threshold_reduced_by_wages": (f) => {
        if (f["0.line.8_self_employment_income"] === undefined) return undefined;
        return floor(
          0,
          sum(
            f["0.line.9_filing_status_threshold_se"],
            f["0.line.10_medicare_wages_from_line4"] === undefined
              ? 0
              : -f["0.line.10_medicare_wages_from_line4"],
          ),
        );
      },
      "0.line.12_excess_se_income": (f) => {
        if (f["0.line.8_self_employment_income"] === undefined) return undefined;
        return floor(
          0,
          sum(
            f["0.line.8_self_employment_income"],
            f["0.line.11_threshold_reduced_by_wages"] === undefined
              ? 0
              : -f["0.line.11_threshold_reduced_by_wages"],
          ),
        );
      },
      "0.line.13_additional_medicare_tax_se": (f) => {
        const line12 = f["0.line.12_excess_se_income"];
        if (typeof line12 !== "number" || line12 === 0) return undefined;
        return Math.ceil(line12 * 0.009);
      },
      // MANUAL EDIT: Part III (lines 15–17) all gate on line 14 (RRTA
      // comp) being defined. No RRTA scenario today.
      "0.line.15_filing_status_threshold_rrta": (f, info) => {
        if (f["0.line.14_rrta_compensation_tips"] === undefined) return undefined;
        return info.filingStatus
          ? ADDITIONAL_MEDICARE_THRESHOLDS[info.filingStatus]
          : undefined;
      },
      "0.line.16_excess_rrta_compensation": (f) => {
        if (f["0.line.14_rrta_compensation_tips"] === undefined) return undefined;
        return floor(
          0,
          sum(
            f["0.line.14_rrta_compensation_tips"],
            f["0.line.15_filing_status_threshold_rrta"] === undefined
              ? 0
              : -f["0.line.15_filing_status_threshold_rrta"],
          ),
        );
      },
      "0.line.17_additional_medicare_tax_rrta": (f) => {
        const line16 = f["0.line.16_excess_rrta_compensation"];
        if (typeof line16 !== "number" || line16 === 0) return undefined;
        return Math.ceil(line16 * 0.009);
      },
      // MANUAL EDIT: line 18 = sum(7, 13, 17). Gate on at least one
      // being defined — suppresses the whole form's output line when
      // no part applies.
      "0.line.18_total_additional_medicare_tax": (f) => {
        const seven = f["0.line.7_additional_medicare_tax_wages"];
        const thirteen = f["0.line.13_additional_medicare_tax_se"];
        const seventeen = f["0.line.17_additional_medicare_tax_rrta"];
        if (
          seven === undefined &&
          thirteen === undefined &&
          seventeen === undefined
        ) {
          return undefined;
        }
        return sum(seven, thirteen, seventeen);
      },
      // MANUAL EDIT: routed to FilingInfo slot (sum of W-2 box 6).
      "0.line.19_medicare_tax_withheld": (_, info) => info.w2MedicareTaxWithheld,
      // Line 20 = line 1.
      "0.line.20_medicare_wages_from_line1": (f) =>
        f["0.line.1_medicare_wages_tips"],
      // MANUAL EDIT: line 21 = line 20 × 1.45%, rounded UP per Math.ceil
      // convention.
      "0.line.21_regular_medicare_tax_on_wages": (f) => {
        const line20 = f["0.line.20_medicare_wages_from_line1"];
        if (typeof line20 !== "number" || line20 === 0) return undefined;
        return Math.ceil(line20 * 0.0145);
      },
      // Line 22 = max(0, line 19 − line 21).
      "0.line.22_additional_medicare_tax_withholding_wages": (f) =>
        floor(
          0,
          sum(
            f["0.line.19_medicare_tax_withheld"],
            f["0.line.21_regular_medicare_tax_on_wages"] === undefined
              ? 0
              : -f["0.line.21_regular_medicare_tax_on_wages"],
          ),
        ),
      // MANUAL EDIT: line 24 = sum(22, 23). Gate on at least one defined.
      "0.line.24_total_additional_medicare_tax_withholding": (f) => {
        const twentyTwo = f["0.line.22_additional_medicare_tax_withholding_wages"];
        const twentyThree = f["0.line.23_additional_medicare_tax_withholding_rrta"];
        if (twentyTwo === undefined && twentyThree === undefined) return undefined;
        return sum(twentyTwo, twentyThree);
      },
    },

    // MANUAL EDIT: SSN renders with dashes (same per-form pattern as
    // Schedule A; not all federal forms use the comb widget).
    formatters: {
      "0.header.ssn": (value) =>
        SSN.format(value as Parameters<typeof SSN.format>[0]),
    },

    unsupported: {
      "0.line.2_unreported_tips":
        "Requires Form 4137 line 6 (unreported tips subject to Medicare tax). No Form 4137 ingestion path exists yet.",
      "0.line.3_wages_form_8919":
        "Requires Form 8919 line 6 (uncollected Social Security and Medicare tax on wages). No Form 8919 ingestion path exists yet.",
      "0.line.8_self_employment_income":
        "Requires Schedule SE Part I line 6 (self-employment income for Additional Medicare Tax). Schedule SE has not been ingested as a form in this system.",
      "0.line.14_rrta_compensation_tips":
        "Railroad retirement (RRTA) compensation from W-2 box 14 — no ingestion path for RRTA-specific box 14 data, and no railroad-worker scenario exists yet.",
      "0.line.23_additional_medicare_tax_withholding_rrta":
        "RRTA Additional Medicare Tax withholding from W-2 box 14 — same blocker as line 14.",
    },

    todos: {},
  });
}

// Summary: 22 binding(s), 0 todo(s), 4 unsupported, 0 unbound.
// Confidence: hand-edited.
