// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/federal/schedule-d/catalog.json
// Form: Capital Gains and Losses (schedule-d, tax year 2025)
// Fields: 53
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface ScheduleD {
  /**  Name(s) shown on return */
  "0.header.taxpayer_name": string | undefined;
  /**  Your social security number */
  "0.header.ssn": string | undefined;
  /**  Did you dispose of any investment(s) in a qualified opportunity fund during the tax year? Yes */
  "0.header.qof_disposal_yes": boolean | undefined;
  /**  Did you dispose of any investment(s) in a qualified opportunity fund during the tax year? No */
  "0.header.qof_disposal_no": boolean | undefined;
  /**  Line 1a — Proceeds (sales price) — Totals for all short-term transactions reported on Form 1099-B or Form 1099-DA for which basis was reported to the IRS and for which you have no adjustments */
  "0.line.1a_proceeds": number | undefined;
  /**  Line 1a — Cost (or other basis) — Totals for all short-term transactions reported on Form 1099-B or Form 1099-DA for which basis was reported to the IRS and for which you have no adjustments */
  "0.line.1a_cost": number | undefined;
  /**  Line 1a — Gain or (loss) — Totals for all short-term transactions reported on Form 1099-B or Form 1099-DA for which basis was reported to the IRS and for which you have no adjustments */
  "0.line.1a_gain_loss": number | undefined;
  /**  Line 1b — Proceeds (sales price) — Totals for all transactions reported on Form(s) 8949 with Box A or Box G checked */
  "0.line.1b_proceeds": number | undefined;
  /**  Line 1b — Cost (or other basis) — Totals for all transactions reported on Form(s) 8949 with Box A or Box G checked */
  "0.line.1b_cost": number | undefined;
  /**  Line 1b — Adjustments to gain or loss from Form(s) 8949, Part I, line 2, column (g) — Totals for all transactions reported on Form(s) 8949 with Box A or Box G checked */
  "0.line.1b_adjustments": number | undefined;
  /**  Line 1b — Gain or (loss) — Totals for all transactions reported on Form(s) 8949 with Box A or Box G checked */
  "0.line.1b_gain_loss": number | undefined;
  /**  Line 2 — Proceeds (sales price) — Totals for all transactions reported on Form(s) 8949 with Box B or Box H checked */
  "0.line.2_proceeds": number | undefined;
  /**  Line 2 — Cost (or other basis) — Totals for all transactions reported on Form(s) 8949 with Box B or Box H checked */
  "0.line.2_cost": number | undefined;
  /**  Line 2 — Adjustments to gain or loss from Form(s) 8949, Part I, line 2, column (g) — Totals for all transactions reported on Form(s) 8949 with Box B or Box H checked */
  "0.line.2_adjustments": number | undefined;
  /**  Line 2 — Gain or (loss) — Totals for all transactions reported on Form(s) 8949 with Box B or Box H checked */
  "0.line.2_gain_loss": number | undefined;
  /**  Line 3 — Proceeds (sales price) — Totals for all transactions reported on Form(s) 8949 with Box C or Box I checked */
  "0.line.3_proceeds": number | undefined;
  /**  Line 3 — Cost (or other basis) — Totals for all transactions reported on Form(s) 8949 with Box C or Box I checked */
  "0.line.3_cost": number | undefined;
  /**  Line 3 — Adjustments to gain or loss from Form(s) 8949, Part I, line 2, column (g) — Totals for all transactions reported on Form(s) 8949 with Box C or Box I checked */
  "0.line.3_adjustments": number | undefined;
  /**  Line 3 — Gain or (loss) — Totals for all transactions reported on Form(s) 8949 with Box C or Box I checked */
  "0.line.3_gain_loss": number | undefined;
  /**  Line 4 — Short-term gain from Form 6252 and short-term gain or (loss) from Forms 4684, 6781, and 8824 */
  "0.line.4_short_term_gain_other_forms": number | undefined;
  /**  Line 5 — Net short-term gain or (loss) from partnerships, S corporations, estates, and trusts from Schedule(s) K-1 */
  "0.line.5_net_short_term_passthrough": number | undefined;
  /**  Line 6 — Short-term capital loss carryover */
  "0.line.6_short_term_loss_carryover": number | undefined;
  /**  Line 7 — Net short-term capital gain or (loss). Combine lines 1a through 6 in column (h) */
  "0.line.7_net_short_term_gain_loss": number | undefined;
  /**  Line 8a — Proceeds (sales price) — Totals for all long-term transactions reported on Form 1099-B or Form 1099-DA for which basis was reported to the IRS and for which you have no adjustments */
  "0.line.8a_proceeds": number | undefined;
  /**  Line 8a — Cost (or other basis) — Totals for all long-term transactions reported on Form 1099-B or Form 1099-DA for which basis was reported to the IRS and for which you have no adjustments */
  "0.line.8a_cost": number | undefined;
  /**  Line 8a — Gain or (loss) — Totals for all long-term transactions reported on Form 1099-B or Form 1099-DA for which basis was reported to the IRS and for which you have no adjustments */
  "0.line.8a_gain_loss": number | undefined;
  /**  Line 8b — Proceeds (sales price) — Totals for all transactions reported on Form(s) 8949 with Box D or Box J checked */
  "0.line.8b_proceeds": number | undefined;
  /**  Line 8b — Cost (or other basis) — Totals for all transactions reported on Form(s) 8949 with Box D or Box J checked */
  "0.line.8b_cost": number | undefined;
  /**  Line 8b — Adjustments to gain or loss from Form(s) 8949, Part II, line 2, column (g) — Totals for all transactions reported on Form(s) 8949 with Box D or Box J checked */
  "0.line.8b_adjustments": number | undefined;
  /**  Line 8b — Gain or (loss) — Totals for all transactions reported on Form(s) 8949 with Box D or Box J checked */
  "0.line.8b_gain_loss": number | undefined;
  /**  Line 9 — Proceeds (sales price) — Totals for all transactions reported on Form(s) 8949 with Box E or Box K checked */
  "0.line.9_proceeds": number | undefined;
  /**  Line 9 — Cost (or other basis) — Totals for all transactions reported on Form(s) 8949 with Box E or Box K checked */
  "0.line.9_cost": number | undefined;
  /**  Line 9 — Adjustments to gain or loss from Form(s) 8949, Part II, line 2, column (g) — Totals for all transactions reported on Form(s) 8949 with Box E or Box K checked */
  "0.line.9_adjustments": number | undefined;
  /**  Line 9 — Gain or (loss) — Totals for all transactions reported on Form(s) 8949 with Box E or Box K checked */
  "0.line.9_gain_loss": number | undefined;
  /**  Line 10 — Proceeds (sales price) — Totals for all transactions reported on Form(s) 8949 with Box F or Box L checked */
  "0.line.10_proceeds": number | undefined;
  /**  Line 10 — Cost (or other basis) — Totals for all transactions reported on Form(s) 8949 with Box F or Box L checked */
  "0.line.10_cost": number | undefined;
  /**  Line 10 — Adjustments to gain or loss from Form(s) 8949, Part II, line 2, column (g) — Totals for all transactions reported on Form(s) 8949 with Box F or Box L checked */
  "0.line.10_adjustments": number | undefined;
  /**  Line 10 — Gain or (loss) — Totals for all transactions reported on Form(s) 8949 with Box F or Box L checked */
  "0.line.10_gain_loss": number | undefined;
  /**  Line 11 — Gain from Form 4797, Part I; long-term gain from Forms 2439 and 6252; and long-term gain or (loss) from Forms 4684, 6781, and 8824 */
  "0.line.11_long_term_gain_other_forms": number | undefined;
  /**  Line 12 — Net long-term gain or (loss) from partnerships, S corporations, estates, and trusts from Schedule(s) K-1 */
  "0.line.12_net_long_term_passthrough": number | undefined;
  /**  Line 13 — Capital gain distributions */
  "0.line.13_capital_gain_distributions": number | undefined;
  /**  Line 14 — Long-term capital loss carryover */
  "0.line.14_long_term_loss_carryover": number | undefined;
  /**  Line 15 — Net long-term capital gain or (loss). Combine lines 8a through 14 in column (h) */
  "0.line.15_net_long_term_gain_loss": number | undefined;
  /**  Line 16 — Combine lines 7 and 15 and enter the result */
  "1.line.16_combined_gain_loss": number | undefined;
  /**  Line 17 Yes — Are lines 15 and 16 both gains? Yes. Go to line 18. */
  "1.line.17_both_gains_yes": boolean | undefined;
  /**  Line 17 No — Are lines 15 and 16 both gains? No. Skip lines 18 through 21, and go to line 22. */
  "1.line.17_both_gains_no": boolean | undefined;
  /**  Line 18 — If you are required to complete the 28% Rate Gain Worksheet, enter the amount, if any, from line 7 of that worksheet */
  "1.line.18_rate_gain_worksheet_amount": number | undefined;
  /**  Line 19 — If you are required to complete the Unrecaptured Section 1250 Gain Worksheet, enter the amount, if any, from line 18 of that worksheet */
  "1.line.19_unrecaptured_sec1250_gain": number | undefined;
  /**  Line 20 Yes — Are lines 18 and 19 both zero or blank and you are not filing Form 4952? Yes. Complete the Qualified Dividends and Capital Gain Tax Worksheet. */
  "1.line.20_use_qual_div_worksheet_yes": boolean | undefined;
  /**  Line 20 No — Are lines 18 and 19 both zero or blank and you are not filing Form 4952? No. Complete the Schedule D Tax Worksheet. */
  "1.line.20_use_qual_div_worksheet_no": boolean | undefined;
  /**  Line 21 — If line 16 is a loss, enter here and on Form 1040, 1040-SR, or 1040-NR, line 7a, the smaller of: the loss on line 16; or ($3,000), or if married filing separately, ($1,500) */
  "1.line.21_allowable_loss": number | undefined;
  /**  Line 22 Yes — Do you have qualified dividends on Form 1040, 1040-SR, or 1040-NR, line 3a? Yes. Complete the Qualified Dividends and Capital Gain Tax Worksheet. */
  "1.line.22_qualified_dividends_yes": boolean | undefined;
  /**  Line 22 No — Do you have qualified dividends on Form 1040, 1040-SR, or 1040-NR, line 3a? No. Complete the rest of Form 1040, 1040-SR, or 1040-NR. */
  "1.line.22_qualified_dividends_no": boolean | undefined;
}
