// Zero-config first boot: generate .env.development for both apps when
// missing, with the .data paths filled in as absolute paths for THIS clone
// (module-relative defaults resolve differently inside Mastra's bundled
// output than in tsx scripts, so pinning absolute paths here keeps every
// entry point on the same files).
//
// Runs automatically via the root predev/predev:all hooks; idempotent — an
// existing .env.development is never touched. Delete the file to regenerate.

import { existsSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const DATA = join(ROOT, "apps", "agent", ".data");

const agentEnvPath = join(ROOT, "apps", "agent", ".env.development");
const webEnvPath = join(ROOT, "apps", "web", ".env.development");

let wrote = false;

if (!existsSync(agentEnvPath)) {
  writeFileSync(
    agentEnvPath,
    `# Generated by scripts/bootstrap-env.mjs — edit freely; delete to regenerate.

# REQUIRED — the one key the app cannot run without.
ANTHROPIC_API_KEY=

# REQUIRED — which model powers each role. No in-code defaults on purpose.
# To use a local/self-hosted OpenAI-compatible server (Ollama, LM Studio,
# vLLM, …) set e.g. LUCA_MODEL=ollama/qwen3-vl:8b and
# LUCA_MODEL_URL=http://localhost:11434/v1 (same pattern for JUDGE_*).
LUCA_MODEL=anthropic/claude-sonnet-4-6
JUDGE_MODEL=anthropic/claude-haiku-4-5

# Optional: semantic retrieval + reranking (FTS-only without it).
VOYAGE_API_KEY=

# Local data files.
CORPUS_DB_PATH=${DATA}/corpus.db
APP_DB_PATH=${DATA}/app.db
MASTRA_DB_PATH=${DATA}/mastra.db
DOCUMENTS_PATH=${DATA}/documents
`,
  );
  console.log(`[bootstrap] wrote ${agentEnvPath}`);
  wrote = true;
}

if (!existsSync(webEnvPath)) {
  writeFileSync(
    webEnvPath,
    `# Generated by scripts/bootstrap-env.mjs — edit freely; delete to regenerate.
APP_DB_PATH=${DATA}/app.db
DOCUMENTS_PATH=${DATA}/documents
`,
  );
  console.log(`[bootstrap] wrote ${webEnvPath}`);
  wrote = true;
}

if (wrote) {
  console.log(
    "[bootstrap] first run: set ANTHROPIC_API_KEY in apps/agent/.env.development," +
      " then `npm run corpus:fetch` for the prebuilt reference corpus.",
  );
}
