// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/state/ca/schedule-ca/catalog.json
// Form: California Adjustments — Residents (schedule-ca, tax year 2025)
// Fields: 253
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface ScheduleCa {
  /**  Name or names as shown on tax return. */
  "0.header.name": string | undefined;
  /**  Social Security Number or Individual Taxpayer Identification Number. */
  "0.header.ssn": string | undefined;
  /**  Part One. Income Adjustment Schedule. Section A. Income from federal Form 1040 or 1040-SR. Line 1a. Total amount from federal Form or Forms W-2, box 1. See instructions. Column A. Federal Amounts. (taxable amounts from your federal tax return). */
  "0.line.1a_federal": number | undefined;
  /**  Line 1a. Column B. Subtractions. See instructions. */
  "0.line.1a_subtractions": number | undefined;
  /**  Line 1a. Column C. Additions. See instructions. */
  "0.line.1a_additions": number | undefined;
  /**  Line 1b. Household employee wages not reported on federal Form or Forms W-2. Column A. Federal Amounts. */
  "0.line.1b_federal": number | undefined;
  /**  Line 1b. Column B. Subtractions. */
  "0.line.1b_subtractions": number | undefined;
  /**  Line 1b. Column C. Additions. */
  "0.line.1b_additions": number | undefined;
  /**  Line 1c. Tip income not reported on line 1a. Column A. Federal Amounts. */
  "0.line.1c_federal": number | undefined;
  /**  Line 1c. Column B. Subtractions. */
  "0.line.1c_subtractions": number | undefined;
  /**  Line 1c. Column C. Additions. */
  "0.line.1c_additions": number | undefined;
  /**  Line 1d. Medicaid waiver payments not reported on federal Form or Forms W-2. See instructions. Column A. Federal Amounts. */
  "0.line.1d_federal": number | undefined;
  /**  Line 1d. Column B. Subtractions. */
  "0.line.1d_subtractions": number | undefined;
  /**  Line 1d. Column C. Additions. */
  "0.line.1d_additions": number | undefined;
  /**  Line 1e. Taxable dependent care benefits from federal Form 2441, line 26. Column A. Federal Amounts. */
  "0.line.1e_federal": number | undefined;
  /**  Line 1e. Column B. Subtractions. */
  "0.line.1e_subtractions": number | undefined;
  /**  Line 1e. Column C. Additions. */
  "0.line.1e_additions": number | undefined;
  /**  Line 1f. Employer-provided adoption benefits from federal Form 8839, line 31 . Column A. Federal Amounts. */
  "0.line.1f_federal": number | undefined;
  /**  Line 1f. Column B. Subtractions. */
  "0.line.1f_subtractions": number | undefined;
  /**  Line 1f. Column C. Additions. */
  "0.line.1f_additions": number | undefined;
  /**  Line 1 g. Wages from federal Form 8919, line 6 . Column A. Federal Amounts. */
  "0.line.1g_federal": number | undefined;
  /**  Line 1 g. Column B. Subtractions. */
  "0.line.1g_subtractions": number | undefined;
  /**  Line 1 g. Column C. Additions. */
  "0.line.1g_additions": number | undefined;
  /**  Line 1 h. Other earned income. See instructions. Enter type of income. */
  "0.line.1h_income_type": string | undefined;
  /**  Line 1 h. Other earned income. Enter amount. Column A. Federal Amounts. */
  "0.line.1h_federal": number | undefined;
  /**  Line 1 h. Column B. Subtractions. */
  "0.line.1h_subtractions": number | undefined;
  /**  Line 1 h. Column C. Additions. */
  "0.line.1h_additions": number | undefined;
  /**  Line 1i. Nontaxable combat pay election. See instructions. Column C. Additions. */
  "0.line.1i_additions": number | undefined;
  /**  Line 1z. Add line 1a through line 1i. Column A. Federal Amounts. */
  "0.line.1z_federal": number | undefined;
  /**  Line 1z. Column B. Subtractions. */
  "0.line.1z_subtractions": number | undefined;
  /**  Line 1z. Column C. Additions. */
  "0.line.1z_additions": number | undefined;
  /**  Line 2. Taxable interest. Line 2 a. */
  "0.line.2a_federal": number | undefined;
  /**  Line 2. Taxable interest. Line 2b. Column A. Federal Amounts. */
  "0.line.2b_federal": number | undefined;
  /**  Line 2b. Column B. Subtractions. */
  "0.line.2b_subtractions": number | undefined;
  /**  Line 2b. Column C. Additions. */
  "0.line.2b_additions": number | undefined;
  /**  Line 3. Ordinary dividends. See instructions. Line 3 a. */
  "0.line.3a_federal": number | undefined;
  /**  Line 3. Ordinary dividends. Line 3b. Column A. Federal Amounts. */
  "0.line.3b_federal": number | undefined;
  /**  Line 3b. Column B. Subtractions. */
  "0.line.3b_subtractions": number | undefined;
  /**  Line 3b. Column C. Additions. */
  "0.line.3b_additions": number | undefined;
  /**  Line 4. I R A distributions. See instructions. Line 4 a. */
  "0.line.4a_federal": number | undefined;
  /**  Line 4. I R A distributions. Line 4b. Column A. Federal Amounts. */
  "0.line.4b_federal": number | undefined;
  /**  Line 4b. Column B. Subtractions. */
  "0.line.4b_subtractions": number | undefined;
  /**  Line 4b. Column C. Additions. */
  "0.line.4b_additions": number | undefined;
  /**  Line 5. Pensions and annuities. See instructions. Line 5 a. */
  "0.line.5a_federal": number | undefined;
  /**  Line 5. Pensions and annuities. Line 5b. Column A. Federal Amounts. */
  "0.line.5b_federal": number | undefined;
  /**  Line 5b. Column B. Subtractions. */
  "0.line.5b_subtractions": number | undefined;
  /**  Line 5b. Column C. Additions. */
  "0.line.5b_additions": number | undefined;
  /**  Line 6. Social security benefits. Line 6 a. */
  "0.line.6a_federal": number | undefined;
  /**  Line 6. Social security benefits. Line 6b. Column A. Federal Amounts. */
  "0.line.6b_federal": number | undefined;
  /**  Line 6b. Column B. Subtractions. */
  "0.line.6b_subtractions": number | undefined;
  /**  Line 7a. Capital gain or (loss). See instructions. Column A. Federal Amounts. */
  "0.line.7a_federal": number | undefined;
  /**  Line 7a. Column B. Subtractions. */
  "0.line.7a_subtractions": number | undefined;
  /**  Line 7a. Column C. Additions. */
  "0.line.7a_additions": number | undefined;
  /**  Section B – Additional Income from federal Schedule 1 (Form 1040). Line 1. Taxable refunds, credits, or offsets of state and local income taxes. Column A. Federal Amounts. */
  "0.line.b1_federal": number | undefined;
  /**  Line 1. Column B. Subtractions. */
  "0.line.b1_subtractions": number | undefined;
  /**  Line 2 b. Date of original divorce or separation agreement. See instructions. Enter date as 2 digit month and 4 digit year. */
  "0.line.b2b_divorce_date": string | undefined;
  /**  Line 2a. Alimony received. Column A. Federal Amounts. */
  "0.line.b2a_federal": number | undefined;
  /**  Line 2a. Column C. Additions. */
  "0.line.b2a_additions": number | undefined;
  /**  Line 3 . Business income or (loss). See instructions. Column A. Federal Amounts. */
  "0.line.b3_federal": number | undefined;
  /**  Line 3 . Column B. Subtractions. */
  "0.line.b3_subtractions": number | undefined;
  /**  Line 3 . Column C. Additions. */
  "0.line.b3_additions": number | undefined;
  /**  Line 4. Other gains or (losses). Column A. Federal Amounts. */
  "0.line.b4_federal": number | undefined;
  /**  Line 4. Column B. Subtractions. */
  "0.line.b4_subtractions": number | undefined;
  /**  Line 4. Column C. Additions. */
  "0.line.b4_additions": number | undefined;
  /**  Line 5. Rental real estate, royalties, partnerships, S corporations, trusts, etcetera. Column A. Federal Amounts. */
  "0.line.b5_federal": number | undefined;
  /**  Line 5. Column B. Subtractions. */
  "0.line.b5_subtractions": number | undefined;
  /**  Line 5. Column C. Additions. */
  "0.line.b5_additions": number | undefined;
  /**  Line 6. Farm income or (loss). Column A. Federal Amounts. */
  "0.line.b6_federal": number | undefined;
  /**  Line 6. Column B. Subtractions. */
  "0.line.b6_subtractions": number | undefined;
  /**  Line 6. Column C. Additions. */
  "0.line.b6_additions": number | undefined;
  /**  Line 7. Unemployment compensation. Column A. Federal Amounts. */
  "0.line.b7_federal": number | undefined;
  /**  Line 7. Column B. Subtractions. */
  "0.line.b7_subtractions": number | undefined;
  /**  Line 8. Other income.  Line 8a. Federal net operating loss. Column A. Federal Amounts. */
  "1.line.b8a_federal": number | undefined;
  /**  Line 8a. Column C. Additions. */
  "1.line.b8a_additions": number | undefined;
  /**  Line 8b. Gambling. Column A. Federal Amounts. */
  "1.line.b8b_federal": number | undefined;
  /**  Line 8b. Gambling. Column B. Subtractions. */
  "1.line.b8b_subtractions": number | undefined;
  /**  Line 8c. Cancellation of debt. Column A. Federal Amounts. */
  "1.line.b8c_federal": number | undefined;
  /**  Line 8c. Cancellation of debt. Column B. Subtractions. */
  "1.line.b8c_subtractions": number | undefined;
  /**  Line 8c. Column C. Additions. */
  "1.line.b8c_additions": number | undefined;
  /**  Line 8d. Foreign earned income exclusion from federal Form 2555. Column A. Federal Amounts. */
  "1.line.b8d_federal": number | undefined;
  /**  Line 8d. Column C. Additions. */
  "1.line.b8d_additions": number | undefined;
  /**  Line 8e. Income from federal Form 8853. Column A. Federal Amounts. */
  "1.line.b8e_federal": number | undefined;
  /**  Line 8e. Column C. Additions. */
  "1.line.b8e_additions": number | undefined;
  /**  Line 8f. Income from federal Form 8889. Column A. Federal Amounts. */
  "1.line.b8f_federal": number | undefined;
  /**  Line 8f. Column B. Subtractions. */
  "1.line.b8f_subtractions": number | undefined;
  /**  Line 8 g. Alaska Permanent Fund dividends. Column A. Federal Amounts. */
  "1.line.b8g_federal": number | undefined;
  /**  Line 8h. Jury duty pay. Column A. Federal Amounts. */
  "1.line.b8h_federal": number | undefined;
  /**  Line 8i. Prizes and awards. Column A. Federal Amounts. */
  "1.line.b8i_federal": number | undefined;
  /**  Line 8j. Activity not engaged in for profit income. Column A. Federal Amounts. */
  "1.line.b8j_federal": number | undefined;
  /**  Line 8k. Stock options. Column A. Federal Amounts. */
  "1.line.b8k_federal": number | undefined;
  /**  Line 8k. Column C. Additions. */
  "1.line.b8k_additions": number | undefined;
  /**  Line 8 l. Income from the rental of personal property if you engaged in the rental for profit but were not in the business of renting such property. Column A. Federal Amounts. */
  "1.line.b8l_federal": number | undefined;
  /**  Line 8m. Olympic and Paralympic medals and USOC prize money. Column A. Federal Amounts. */
  "1.line.b8m_federal": number | undefined;
  /**  Line 8n. IRC Section 951(a) inclusion. Column A. Federal Amounts. */
  "1.line.b8n_federal": number | undefined;
  /**  Line 8n. Column B. Subtractions. */
  "1.line.b8n_subtractions": number | undefined;
  /**  Line 8o. IRC Section 951A(a) inclusion. Column A. Federal Amounts. */
  "1.line.b8o_federal": number | undefined;
  /**  Line 8o. Column B. Subtractions. */
  "1.line.b8o_subtractions": number | undefined;
  /**  Line 8p. IRC Section 461( l ) excess business loss adjustment. Column A. Federal Amounts. */
  "1.line.b8p_federal": number | undefined;
  /**  Line 8p. Column B. Subtractions. */
  "1.line.b8p_subtractions": number | undefined;
  /**  Line 8p. Column C. Additions. */
  "1.line.b8p_additions": number | undefined;
  /**  Line 8 q. Taxable distributions from an ABLE account. Column A. Federal Amounts. */
  "1.line.b8q_federal": number | undefined;
  /**  Line 8r. Scholarship and fellowship grants not reported on federal Form or Forms W-2. Column A. Federal Amounts. */
  "1.line.b8r_federal": number | undefined;
  /**  Line 8s. Nontaxable amount of Medicaid waiver payments included on federal Form 1040, line 1a or line 1d. Column A. Federal Amounts. */
  "1.line.b8s_federal": number | undefined;
  /**  Line 8 t. Pension or annuity from a nonqualified deferred compensation plan or a nongovernmental IRC Section 457 plan. Column A. Federal Amounts. */
  "1.line.b8t_federal": number | undefined;
  /**  Line 8u. Wages earned while incarcerated. Column A. Federal Amounts. */
  "1.line.b8u_federal": number | undefined;
  /**  Line 8v. Digital assets received as ordinary income not reported elsewhere. Column A. Federal Amounts. */
  "1.line.b8v_federal": number | undefined;
  /**  Line 8v. Column B. Subtractions. */
  "1.line.b8v_subtractions": number | undefined;
  /**  Line 8v. Column C. Additions. */
  "1.line.b8v_additions": number | undefined;
  /**  Line 8 z. Other income. Enter type of income. */
  "1.line.b8z_income_type": string | undefined;
  /**  Line 8 z. Other income. Enter amount. Column A. Federal Amounts. */
  "1.line.b8z_federal": number | undefined;
  /**  Line 8z. Column B. Subtractions. */
  "1.line.b8z_subtractions": number | undefined;
  /**  Line 8z. Column C. Additions. */
  "1.line.b8z_additions": number | undefined;
  /**  Line 9 a. Total other income. Add line 8a through line 8z. Column A. Federal Amounts. */
  "2.line.b9a_federal": number | undefined;
  /**  Line 9 a. Column B. Subtractions. */
  "2.line.b9a_subtractions": number | undefined;
  /**  Line 9 a. Column C. Additions. */
  "2.line.b9a_additions": number | undefined;
  /**  Line 9 b1. Disaster loss deduction from form FTB 3805V. Column B. Subtractions. */
  "2.line.b9b1_subtractions": number | undefined;
  /**  Line 9 b2. Net operating loss deduction from form FTB 3805V. Column B. Subtractions. */
  "2.line.b9b2_subtractions": number | undefined;
  /**  Line 9 b3. Net operating loss deduction from form FTB 3805Z, 3807, or 3809. Column B. Subtractions. */
  "2.line.b9b3_subtractions": number | undefined;
  /**  Line 10. Total. Add Section A, line 1z through line 7a, and Section B, line 1 through line 7, and line 9a in column A and column C. Add Section A, line 1z through line 7a, and Section B, line 1 through line 7, line 9a, and line 9b1 through line 9b3 in column B (as applicable). See instructions. Column A. Federal Amounts. */
  "2.line.b10_federal": number | undefined;
  /**  Line 10. Column B. Subtractions. */
  "2.line.b10_subtractions": number | undefined;
  /**  Line 10. Column C. Additions. */
  "2.line.b10_additions": number | undefined;
  /**  Section C . Adjustments to Income from federal Schedule 1 (Form 1040).  Line 11. Educator expenses. Column A. Federal Amounts. */
  "2.line.c11_federal": number | undefined;
  /**  Line 11. Column B. Subtractions. */
  "2.line.c11_subtractions": number | undefined;
  /**  Line 12. Certain business expenses of reservists, performing artists, and fee-basis government officials. Column A. Federal Amounts. */
  "2.line.c12_federal": number | undefined;
  /**  Line 12. Column B. Subtractions. */
  "2.line.c12_subtractions": number | undefined;
  /**  Line 12. Column C. Additions. */
  "2.line.c12_additions": number | undefined;
  /**  Line 13. Health savings account deduction. Column A. Federal Amounts. */
  "2.line.c13_federal": number | undefined;
  /**  Line 13. Column B. Subtractions. */
  "2.line.c13_subtractions": number | undefined;
  /**  Line 14. Moving expenses. Attach form FTB 3913. See instructions. Column A. Federal Amounts. */
  "2.line.c14_federal": number | undefined;
  /**  Line 14. Moving expenses. Attach form FTB 3913. See instructions. Column C. Additions. */
  "2.line.c14_additions": number | undefined;
  /**  Line 15. Deductible part of self-employment tax. See instructions. Column A. Federal Amounts. */
  "2.line.c15_federal": number | undefined;
  /**  Line 15. Column B. Subtractions. */
  "2.line.c15_subtractions": number | undefined;
  /**  Line 16. Self-employed SEP, SIMPLE, and qualified plans. Column A. Federal Amounts. */
  "2.line.c16_federal": number | undefined;
  /**  Line 17. Self-employed health insurance deduction. See instructions. Column A. Federal Amounts. */
  "2.line.c17_federal": number | undefined;
  /**  Line 17. Column B. Subtractions. */
  "2.line.c17_subtractions": number | undefined;
  /**  Line 18. Penalty on early withdrawal of savings. Column A. Federal Amounts. */
  "2.line.c18_federal": number | undefined;
  /**  Line 19a. Alimony paid. Column A. Federal Amounts. */
  "2.line.c19a_federal": number | undefined;
  /**  Line 19a. Column C. Additions. */
  "2.line.c19a_additions": number | undefined;
  /**  Line 19 b. Recipient’s Social Security Number. */
  "2.line.c19b_recipient_ssn": string | undefined;
  /**  Line 19 b. Recipient’s last name. */
  "2.line.c19b_recipient_last_name": string | undefined;
  /**  Line 19 c. Date of original divorce or separation agreement. See instruction. Enter date as 2 digit month and 4 digit year. */
  "2.line.c19c_divorce_date": string | undefined;
  /**  Line 20. IRA deduction. Column A. Federal Amounts. */
  "2.line.c20_federal": number | undefined;
  /**  Line 20. Column B. Subtractions. */
  "2.line.c20_subtractions": number | undefined;
  /**  Line 20. Column C. Additions. */
  "2.line.c20_additions": number | undefined;
  /**  Line 21. Student loan interest deduction. Column A. Federal Amounts. */
  "2.line.c21_federal": number | undefined;
  /**  Line 21. Column C. Additions. */
  "2.line.c21_additions": number | undefined;
  /**  Line 23. Archer MSA deduction. Column A. Federal Amounts. */
  "2.line.c23_federal": number | undefined;
  /**  Line 24. Other adjustments. Line 24a. Jury duty pay. Column A. Federal Amounts. */
  "3.line.c24a_federal": number | undefined;
  /**  Line 24b. Deductible expenses related to income reported on line 8 l from the rental of personal property engaged in for profit. Column A. Federal Amounts. */
  "3.line.c24b_federal": number | undefined;
  /**  Line 24b. Column B. Subtractions. */
  "3.line.c24b_subtractions": number | undefined;
  /**  Line 24b. Column C. Additions. */
  "3.line.c24b_additions": number | undefined;
  /**  Line 24c. Nontaxable amount of the value of Olympic and  Paralympic medals and USOC prize money reported on line 8 m. Column A. Federal Amounts. */
  "3.line.c24c_federal": number | undefined;
  /**  Line 24c. Column B. Subtractions. */
  "3.line.c24c_subtractions": number | undefined;
  /**  Line 24d. Reforestation amortization and expenses. Column A. Federal Amounts. */
  "3.line.c24d_federal": number | undefined;
  /**  Line 24d. Column B. Subtractions. */
  "3.line.c24d_subtractions": number | undefined;
  /**  Line 24e. Repayment of supplemental unemployment benefits under the federal Trade Act of 1974. Column A. Federal Amounts. */
  "3.line.c24e_federal": number | undefined;
  /**  Line 24f. Contributions to IRC Section 501(c)(18)(D) pension plans. Column A. Federal Amounts. */
  "3.line.c24f_federal": number | undefined;
  /**  Line 24f. Column B. Subtractions. */
  "3.line.c24f_subtractions": number | undefined;
  /**  Line 24f. Column C. Additions. */
  "3.line.c24f_additions": number | undefined;
  /**  Line 24 g. Contributions by certain chaplains to IRC Section 403(b) plans. Column A. Federal Amounts. */
  "3.line.c24g_federal": number | undefined;
  /**  Line 24 g. Column B. Subtractions. */
  "3.line.c24g_subtractions": number | undefined;
  /**  Line 24 g. Column C. Additions. */
  "3.line.c24g_additions": number | undefined;
  /**  Line 24h. Attorney fees and court costs for actions involving certain unlawful discrimination claims. Column A. Federal Amounts. */
  "3.line.c24h_federal": number | undefined;
  /**  Line 24i. Attorney fees and court costs you paid in connection with an award from the IRS for information you provided that helped the IRS detect tax law violations. Column A. Federal Amounts. */
  "3.line.c24i_federal": number | undefined;
  /**  Line 24i. Column B. Subtractions. */
  "3.line.c24i_subtractions": number | undefined;
  /**  Line 24j. Housing deduction from federal Form 2555 . Column A. Federal Amounts. */
  "3.line.c24j_federal": number | undefined;
  /**  Line 24j. Column B. Subtractions. */
  "3.line.c24j_subtractions": number | undefined;
  /**  Line 24k. Excess deductions of IRC Section 67(e) expenses from federal Schedule K-1 (Form 1041). Column A. Federal Amounts. */
  "3.line.c24k_federal": number | undefined;
  /**  Line 24z. Other adjustments. Enter type of income. */
  "3.line.c24z_income_type": string | undefined;
  /**  Line 24z. Other adjustments. Enter amount. Column A. Federal Amounts. */
  "3.line.c24z_federal": number | undefined;
  /**  Line 24z. Column B. Subtractions. */
  "3.line.c24z_subtractions": number | undefined;
  /**  Line 24z. Column C. Additions. */
  "3.line.c24z_additions": number | undefined;
  /**  Line 25. Total other adjustments. Add line 24a through line 24z. Column A. Federal Amounts. */
  "3.line.c25_federal": number | undefined;
  /**  Line 25. Column B. Subtractions. */
  "3.line.c25_subtractions": number | undefined;
  /**  Line 25. Column C. Additions. */
  "3.line.c25_additions": number | undefined;
  /**  Line 26. Add line 11 through line 23 and line 25 in columns A, B, and C. See instructions. Column A. Federal Amounts. */
  "3.line.c26_federal": number | undefined;
  /**  Line 26. Column B. Subtractions. */
  "3.line.c26_subtractions": number | undefined;
  /**  Line 26. Column C. Additions. */
  "3.line.c26_additions": number | undefined;
  /**  Line 27. Total. Subtract line 26 from line 10 in columns A, B, and C. See instructions. Column A. Federal Amounts. */
  "3.line.c27_federal": number | undefined;
  /**  Line 27. Column B. Subtractions. */
  "3.line.c27_subtractions": number | undefined;
  /**  Line 27. Column C. Additions. */
  "3.line.c27_additions": number | undefined;
  /**  Part Two. Adjustments to Federal Itemized Deductions. Check the box if you did NOT itemize for federal but will itemize for California. */
  "4.page2.itemize_ca_not_federal": boolean | undefined;
  /**  Medical and Dental Expenses. Line 1. Medical and dental expenses */
  "4.page2.medical_dental_expenses": number | undefined;
  /**  Line 2. Enter amount from federal Form 1040 or 1040-SR, line 11b. */
  "4.page2.medical_agi_line11b": number | undefined;
  /**  Line 3. Multiply line 2 by 7.5% (0.075). */
  "4.page2.medical_agi_threshold": number | undefined;
  /**  Line 4. Subtract line 3 from line 1. If line 3 is more than line 1, enter 0. Column A. Federal Amounts . */
  "4.page2.medical_line4_federal": number | undefined;
  /**  Line 4. Column C. Additions. */
  "4.page2.medical_line4_additions": number | undefined;
  /**  Taxes You Paid. Line 5a. State and local income tax or general sales taxes. Column A. Federal Amounts. */
  "4.page2.taxes_5a_federal": number | undefined;
  /**  Line 5a. Column B. Subtractions. */
  "4.page2.taxes_5a_subtractions": number | undefined;
  /**  Line 5b. State and local real estate taxes. Column A. Federal Amounts. */
  "4.page2.taxes_5b_federal": number | undefined;
  /**  Line 5c.  State and local personal property taxes. Column A. Federal Amounts. */
  "4.page2.taxes_5c_federal": number | undefined;
  /**  Line 5d. Add line 5a through line 5c. Column A. Federal Amounts. */
  "4.page2.taxes_5d_federal": number | undefined;
  /**  Line 5e. Enter the smaller of line 5d or $40,000 ($20,000 if married filing separately) in column A. Enter the amount from line 5 a, column B in line 5e, column B. Enter the difference from line 5d and line 5e, column A in line 5e, column C. Column A. Federal Amounts. */
  "4.page2.taxes_5e_federal": number | undefined;
  /**  Line 5e. Column B. Subtractions. */
  "4.page2.taxes_5e_subtractions": number | undefined;
  /**  Line 5e. Column C. Additions. */
  "4.page2.taxes_5e_additions": number | undefined;
  /**  Line 6. Other taxes. List type. */
  "4.page2.taxes_6_type": string | undefined;
  /**  Line 6. Other taxes. Enter amount. Column A. Federal Amounts. */
  "4.page2.taxes_6_federal": number | undefined;
  /**  Line 6. Column B. Subtractions. */
  "4.page2.taxes_6_subtractions": number | undefined;
  /**  Line 6. Column C. Additions. */
  "4.page2.taxes_6_additions": number | undefined;
  /**  Line 7. Add line 5e and line 6. Column A. Federal Amounts. */
  "4.page2.taxes_7_federal": number | undefined;
  /**  Line 7. Column B. Subtractions. */
  "4.page2.taxes_7_subtractions": number | undefined;
  /**  Line 7. Column C. Additions. */
  "4.page2.taxes_7_additions": number | undefined;
  /**  Interest You Paid. Line 8a. Home mortgage interest and points reported to you on federal Form 1098. Column A. Federal Amounts. */
  "4.page2.interest_8a_federal": number | undefined;
  /**  Line 8a. Column C. Additions. */
  "4.page2.interest_8a_additions": number | undefined;
  /**  Line 8b. Home mortgage interest not reported to you on federal Form 1098. Column A. Federal Amounts. */
  "4.page2.interest_8b_federal": number | undefined;
  /**  Line 8b. Column C. Additions. */
  "4.page2.interest_8b_additions": number | undefined;
  /**  Line 8c. Points not reported to you on federal Form 1098. Column A. Federal Amounts. */
  "4.page2.interest_8c_federal": number | undefined;
  /**  Line 8c. Column C. Additions. */
  "4.page2.interest_8c_additions": number | undefined;
  /**  Line 8e. Add line 8a through line 8c. Column A. Federal Amounts. */
  "4.page2.interest_8e_federal": number | undefined;
  /**  Line 8e. Column B. Subtractions. */
  "4.page2.interest_8e_subtractions": number | undefined;
  /**  Line 8e. Column C. Additions. */
  "4.page2.interest_8e_additions": number | undefined;
  /**  Line 9. Investment interest. Column A. Federal Amounts. */
  "4.page2.interest_9_federal": number | undefined;
  /**  Line 9. Column B. Subtractions. */
  "4.page2.interest_9_subtractions": number | undefined;
  /**  Line 9. Column C. Additions. */
  "4.page2.interest_9_additions": number | undefined;
  /**  Line 10. Add line 8 e and line 9. Column A. Federal Amounts. */
  "4.page2.interest_10_federal": number | undefined;
  /**  Line 10. Column B. Subtractions. */
  "4.page2.interest_10_subtractions": number | undefined;
  /**  Line 10. Column C. Additions. */
  "4.page2.interest_10_additions": number | undefined;
  /**  Gifts to Charity. Line 11. Gifts by cash or check. Column A. Federal Amounts. */
  "5.page2.charity_11_federal": number | undefined;
  /**  Line 11. Column B. Subtractions. */
  "5.page2.charity_11_subtractions": number | undefined;
  /**  Line 11. Column C. Additions. */
  "5.page2.charity_11_additions": number | undefined;
  /**  Line 12. Other than by cash or check. Column A. Federal Amounts. */
  "5.page2.charity_12_federal": number | undefined;
  /**  Line 12. Column B. Subtractions. */
  "5.page2.charity_12_subtractions": number | undefined;
  /**  Line 12. Column C. Additions. */
  "5.page2.charity_12_additions": number | undefined;
  /**  Line 13. Carryover from prior year. Column A. Federal Amounts. */
  "5.page2.charity_13_federal": number | undefined;
  /**  Line 13. Column B. Subtractions. */
  "5.page2.charity_13_subtractions": number | undefined;
  /**  Line 13. Column C. Additions. */
  "5.page2.charity_13_additions": number | undefined;
  /**  Line 14. Add line 11 through line 13. Column A. Federal Amounts. */
  "5.page2.charity_14_federal": number | undefined;
  /**  Line 14. Column B. Subtractions. */
  "5.page2.charity_14_subtractions": number | undefined;
  /**  Line 14. Column C. Additions. */
  "5.page2.charity_14_additions": number | undefined;
  /**  Casualty and Theft Losses. Line 15. Casualty or theft loss or losses (other than net qualified disaster losses). Attach federal Form 4684. See instructions. Column A. Federal Amounts. */
  "5.page2.casualty_15_federal": number | undefined;
  /**  Line 15. Column B. Subtractions. */
  "5.page2.casualty_15_subtractions": number | undefined;
  /**  Line 15. Column C. Additions. */
  "5.page2.casualty_15_additions": number | undefined;
  /**  Other Itemized Deductions. Line 16. Other—from list in federal instructions. Column A. Federal Amounts. */
  "5.page2.other_deductions_16_federal": number | undefined;
  /**  Line 16. Column B. Subtractions. */
  "5.page2.other_deductions_16_subtractions": number | undefined;
  /**  Line 16. Column C. Additions. */
  "5.page2.other_deductions_16_additions": number | undefined;
  /**  Line 17. Add lines 4, 7, 10, 14, 15, and 16 in columns A, B, and C. Column A. Federal Amounts. */
  "5.page2.total_itemized_17_federal": number | undefined;
  /**  Line 17. Column B. Subtractions. */
  "5.page2.total_itemized_17_subtractions": number | undefined;
  /**  Line 17. Column C. Additions. */
  "5.page2.total_itemized_17_additions": number | undefined;
  /**  Line 18. Total. Combine line 17 column A less column B plus column C. */
  "5.page2.total_itemized_18_combined": number | undefined;
  /**  Job Expenses and Certain Miscellaneous Deductions. Line 19. Unreimbursed employee expenses: job travel, union dues, job education, etcetera. Attach federal Form 2106 if required. See instructions. */
  "5.page2.job_expenses_19": number | undefined;
  /**  Line 20. Tax preparation fees. */
  "5.page2.job_expenses_20": number | undefined;
  /**  Line 21. Other expenses: investment, safe deposit box, etcetera. List type. */
  "5.page2.job_expenses_21_type": string | undefined;
  /**  Line 21. Other expenses: investment, safe deposit box, etcetera. Enter amount. */
  "5.page2.job_expenses_21_amount": number | undefined;
  /**  Line 22. Add line 19 through line 21. */
  "5.page2.job_expenses_22_total": number | undefined;
  /**  Line 23. Enter amount from federal Form 1040 or 1040-SR, line 11b . */
  "5.page2.job_expenses_23_agi": number | undefined;
  /**  Line 24. Multiply line 23 by 2% (0.02). If less than zero, enter 0. */
  "5.page2.job_expenses_24_threshold": number | undefined;
  /**  Line 25. Subtract line 24 from line 22. If line 24 is more than line 22, enter 0. */
  "5.page2.job_expenses_25_net": number | undefined;
  /**  Line 26. Total Itemized Deductions. Add line 18 and line 25. */
  "5.page2.total_itemized_26": number | undefined;
  /**  Line 27. Other adjustments. See instructions. Specify. */
  "5.page2.other_adjustments_27_type": string | undefined;
  /**  Line 27. Other adjustments. See instructions. Enter amount. */
  "5.page2.other_adjustments_27_amount": number | undefined;
  /**  Line 28. Combine line 26 and line 27. */
  "5.page2.total_itemized_28": number | undefined;
  /**  Line 29. Is your federal adjusted gross income (Form 540, line 13) more than the amount shown below for your filing status? Single, married, or registered domestic partner filing separately: $252,203 . Head of household: $378,310 . Married or registered domestic partner filing jointly or qualifying surviving spouse or registered domestic partner: $504,411 . No. Transfer the amount on line 28 to line 29. Yes. Complete the Itemized Deductions Worksheet in the instructions for Schedule CA (540), line 29. */
  "5.page2.total_itemized_29": number | undefined;
  /**  Line 30. Enter the larger of the amount on line 29 or your standard deduction shown below: Single, married or registered domestic partner filing separately. See instructions: $5,706 . Married or registered domestic partner filing jointly, head of household, or qualifying surviving spouse or registered domestic partner: $11,412 . Transfer the amount on line 30 to Form 540, line 18. */
  "5.page2.total_itemized_30_standard_or_itemized": number | undefined;
}
