import type { SupabaseClient } from "@supabase/supabase-js";

// All helpers take a user-scoped Supabase client (built per request from the
// caller's JWT). RLS policies on public.tax_facts / public.open_questions
// scope every read and write to auth.uid() — we don't write WHERE user_id
// clauses ourselves, the database does. We still pass user_id explicitly on
// inserts because RLS WITH CHECK validates it, and explicit beats implicit.

export interface TaxFact {
  id: string;
  userId: string;
  filingId: string;
  taxYear: number;
  category: string;
  key: string;
  value: unknown;
  sourceNote?: string;
}

export interface TaxFactRow {
  id: string;
  userId: string;
  taxYear: number;
  category: string;
  key: string;
  value: unknown;
  sourceNote: string | null;
  createdAt: string;
}

interface TaxFactDbRow {
  id: string;
  user_id: string;
  tax_year: number;
  category: string;
  fact_key: string;
  fact_value: unknown;
  source_note: string | null;
  created_at: string;
}

function rowToFact(r: TaxFactDbRow): TaxFactRow {
  return {
    id: r.id,
    userId: r.user_id,
    taxYear: r.tax_year,
    category: r.category,
    key: r.fact_key,
    value: r.fact_value,
    sourceNote: r.source_note,
    createdAt: r.created_at,
  };
}

export async function recordFact(
  supabase: SupabaseClient,
  fact: TaxFact,
): Promise<void> {
  const { error } = await supabase.from("tax_facts").insert({
    id: fact.id,
    user_id: fact.userId,
    filing_id: fact.filingId,
    tax_year: fact.taxYear,
    category: fact.category,
    fact_key: fact.key,
    fact_value: fact.value,
    source_note: fact.sourceNote ?? null,
  });
  if (error) throw new Error(`recordFact failed: ${error.message}`);
}

export interface ListFactsOpts {
  filingId?: string;
  taxYear?: number;
  category?: string;
  limit?: number;
}

export async function listFacts(
  supabase: SupabaseClient,
  opts: ListFactsOpts = {},
): Promise<TaxFactRow[]> {
  let q = supabase
    .from("tax_facts")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(Math.min(opts.limit ?? 100, 500));
  if (opts.filingId) q = q.eq("filing_id", opts.filingId);
  if (opts.taxYear !== undefined) q = q.eq("tax_year", opts.taxYear);
  if (opts.category) q = q.eq("category", opts.category);
  const { data, error } = await q;
  if (error) throw new Error(`listFacts failed: ${error.message}`);
  return (data ?? []).map(rowToFact);
}

export async function listFactsByKeys(
  supabase: SupabaseClient,
  taxYear: number,
  keys: string[],
): Promise<TaxFactRow[]> {
  if (keys.length === 0) return [];
  const { data, error } = await supabase
    .from("tax_facts")
    .select("*")
    .eq("tax_year", taxYear)
    .in("fact_key", keys)
    .order("created_at", { ascending: false });
  if (error) throw new Error(`listFactsByKeys failed: ${error.message}`);
  // tax_facts is append-only; collapse to the latest row per fact_key.
  const latest = new Map<string, TaxFactRow>();
  for (const r of (data ?? []) as TaxFactDbRow[]) {
    if (latest.has(r.fact_key)) continue;
    latest.set(r.fact_key, rowToFact(r));
  }
  return Array.from(latest.values());
}

// ---------------------------------------------------------------------------
// Open questions (small surface area, lives alongside tax_facts)
// ---------------------------------------------------------------------------

export interface OpenQuestion {
  id: string;
  userId: string;
  filingId: string;
  question: string;
  context?: string;
  // Set when the question was generated by the review-decision workflow on a
  // `needs_more_facts` exit. Null for questions Thom raises directly. Lets us
  // re-trigger review on the parent decision once the user answers.
  decisionId?: string;
}

export interface OpenQuestionRow {
  id: string;
  userId: string;
  status: string;
  question: string;
  context: string | null;
  createdAt: string;
  resolvedAt: string | null;
}

interface OpenQuestionDbRow {
  id: string;
  user_id: string;
  status: string;
  question: string;
  context: string | null;
  created_at: string;
  resolved_at: string | null;
}

function rowToQuestion(r: OpenQuestionDbRow): OpenQuestionRow {
  return {
    id: r.id,
    userId: r.user_id,
    status: r.status,
    question: r.question,
    context: r.context,
    createdAt: r.created_at,
    resolvedAt: r.resolved_at,
  };
}

export async function noteQuestion(
  supabase: SupabaseClient,
  q: OpenQuestion,
): Promise<void> {
  const { error } = await supabase.from("open_questions").insert({
    id: q.id,
    user_id: q.userId,
    filing_id: q.filingId,
    status: "open",
    question: q.question,
    context: q.context ?? null,
    decision_id: q.decisionId ?? null,
  });
  if (error) throw new Error(`noteQuestion failed: ${error.message}`);
}

export async function listOpenQuestions(
  supabase: SupabaseClient,
  status: "open" | "resolved" | "all" = "open",
): Promise<OpenQuestionRow[]> {
  let q = supabase
    .from("open_questions")
    .select("*")
    .order("created_at", { ascending: false })
    .limit(200);
  if (status !== "all") q = q.eq("status", status);
  const { data, error } = await q;
  if (error) throw new Error(`listOpenQuestions failed: ${error.message}`);
  return ((data ?? []) as OpenQuestionDbRow[]).map(rowToQuestion);
}

export async function resolveQuestion(
  supabase: SupabaseClient,
  id: string,
): Promise<void> {
  const { error } = await supabase
    .from("open_questions")
    .update({ status: "resolved", resolved_at: new Date().toISOString() })
    .eq("id", id);
  if (error) throw new Error(`resolveQuestion failed: ${error.message}`);
}
