import type { InValue, Row } from "@libsql/client";
import {
  getAppDb,
  ensureAppSchema,
  type Scope,
  asStr,
  asStrOrNull,
  asNum,
  asJson,
  nowIso,
} from "./appDb";

// All helpers take an explicit Scope { userId, filingId } — the replacement
// for the RLS policies that used to scope these queries in Postgres. Reads
// filter on filing_id (matching the old member-read policy, so the CPA
// review path keeps working); writes stamp both user_id and filing_id.

// The row shape is engine vocabulary — the engine defines it, this module
// persists it. Re-exported so db-side callers keep importing from here.
import type { TaxFactRow } from "../../engine/facts/rows";
export type { TaxFactRow };

export interface TaxFact {
  id: string;
  userId: string;
  filingId: string;
  taxYear: number;
  category: string;
  key: string;
  value: unknown;
  sourceNote?: string;
}

function rowToFact(r: Row): TaxFactRow {
  return {
    id: asStr(r.id),
    userId: asStr(r.user_id),
    taxYear: asNum(r.tax_year),
    category: asStr(r.category),
    key: asStr(r.fact_key),
    value: asJson(r.fact_value),
    sourceNote: asStrOrNull(r.source_note),
    createdAt: asStr(r.created_at),
  };
}

export async function recordFact(scope: Scope, fact: TaxFact): Promise<void> {
  await ensureAppSchema();
  await getAppDb().execute({
    sql: `INSERT INTO tax_facts
            (id, user_id, filing_id, tax_year, category, fact_key, fact_value, source_note, created_at)
          VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      fact.id,
      fact.userId,
      fact.filingId,
      fact.taxYear,
      fact.category,
      fact.key,
      JSON.stringify(fact.value ?? null),
      fact.sourceNote ?? null,
      nowIso(),
    ],
  });
  void scope; // scoping is explicit via fact.userId/filingId on insert
}

export interface ListFactsOpts {
  filingId?: string;
  taxYear?: number;
  category?: string;
  limit?: number;
}

export async function listFacts(
  scope: Scope,
  opts: ListFactsOpts = {},
): Promise<TaxFactRow[]> {
  await ensureAppSchema();
  const conds: string[] = ["filing_id = ?"];
  const args: InValue[] = [opts.filingId ?? scope.filingId];
  if (opts.taxYear !== undefined) {
    conds.push("tax_year = ?");
    args.push(opts.taxYear);
  }
  if (opts.category) {
    conds.push("category = ?");
    args.push(opts.category);
  }
  args.push(Math.min(opts.limit ?? 100, 500));
  const res = await getAppDb().execute({
    sql: `SELECT * FROM tax_facts WHERE ${conds.join(" AND ")}
          ORDER BY created_at DESC LIMIT ?`,
    args,
  });
  return res.rows.map(rowToFact);
}

export async function listFactsByKeys(
  scope: Scope,
  taxYear: number,
  keys: string[],
): Promise<TaxFactRow[]> {
  if (keys.length === 0) return [];
  await ensureAppSchema();
  const placeholders = keys.map(() => "?").join(",");
  const res = await getAppDb().execute({
    sql: `SELECT * FROM tax_facts
          WHERE filing_id = ? AND tax_year = ? AND fact_key IN (${placeholders})
          ORDER BY created_at DESC`,
    args: [scope.filingId, taxYear, ...keys],
  });
  // tax_facts is append-only; collapse to the latest row per fact_key.
  const latest = new Map<string, TaxFactRow>();
  for (const r of res.rows) {
    const key = asStr(r.fact_key);
    if (latest.has(key)) continue;
    latest.set(key, rowToFact(r));
  }
  return Array.from(latest.values());
}

// ---------------------------------------------------------------------------
// Open questions (small surface area, lives alongside tax_facts)
// ---------------------------------------------------------------------------

export interface OpenQuestion {
  id: string;
  userId: string;
  filingId: string;
  question: string;
  context?: string;
  // Set when the question was generated by the review-decision workflow on a
  // `needs_more_facts` exit. Null for questions Luca raises directly. Lets us
  // re-trigger review on the parent decision once the user answers.
  decisionId?: string;
}

export interface OpenQuestionRow {
  id: string;
  userId: string;
  status: string;
  question: string;
  context: string | null;
  createdAt: string;
  resolvedAt: string | null;
}

function rowToQuestion(r: Row): OpenQuestionRow {
  return {
    id: asStr(r.id),
    userId: asStr(r.user_id),
    status: asStr(r.status),
    question: asStr(r.question),
    context: asStrOrNull(r.context),
    createdAt: asStr(r.created_at),
    resolvedAt: asStrOrNull(r.resolved_at),
  };
}

export async function noteQuestion(
  scope: Scope,
  q: OpenQuestion,
): Promise<void> {
  await ensureAppSchema();
  await getAppDb().execute({
    sql: `INSERT INTO open_questions
            (id, user_id, filing_id, status, question, context, decision_id, created_at)
          VALUES (?, ?, ?, 'open', ?, ?, ?, ?)`,
    args: [
      q.id,
      q.userId,
      q.filingId,
      q.question,
      q.context ?? null,
      q.decisionId ?? null,
      nowIso(),
    ],
  });
  void scope;
}

export async function listOpenQuestions(
  scope: Scope,
  status: "open" | "resolved" | "all" = "open",
): Promise<OpenQuestionRow[]> {
  await ensureAppSchema();
  const conds = ["filing_id = ?"];
  const args: InValue[] = [scope.filingId];
  if (status !== "all") {
    conds.push("status = ?");
    args.push(status);
  }
  const res = await getAppDb().execute({
    sql: `SELECT * FROM open_questions WHERE ${conds.join(" AND ")}
          ORDER BY created_at DESC LIMIT 200`,
    args,
  });
  return res.rows.map(rowToQuestion);
}

export async function resolveQuestion(scope: Scope, id: string): Promise<void> {
  await ensureAppSchema();
  await getAppDb().execute({
    sql: `UPDATE open_questions SET status = 'resolved', resolved_at = ?
          WHERE id = ? AND filing_id = ?`,
    args: [nowIso(), id, scope.filingId],
  });
}
