// Runtime loader for IRS tax tables (Form 1040 line 16, taxable income
// under $100,000). Generated by scripts/ingestTaxTable.ts; consumed by the
// form engine's `taxTable` rule and by any operator script that needs to
// resolve a row.
//
// Per-year tables live in tax-table-<year>.json next to this file. Adding a
// new year = ingest the JSON + add an import line below. The loader keeps
// the table-per-year shape so future ingests for 2026, 2027, etc. drop in
// with zero refactoring.

import taxTable2025 from "./tax-table-2025.json" with { type: "json" };

export type FilingStatus = "single" | "mfj" | "mfs" | "hoh";

export interface TaxTableRow {
  low: number;
  high: number;
  single: number;
  mfj: number;
  mfs: number;
  hoh: number;
}

interface LoadedTaxTable {
  taxYear: number;
  source: {
    url: string;
    fetchedAt: string;
    sha256: string;
    cacheFile: string;
  };
  coverage: { minIncome: number; maxIncome: number; rowCount: number };
  rows: TaxTableRow[];
}

const TABLES_BY_YEAR: Record<number, LoadedTaxTable> = {
  2025: taxTable2025 as LoadedTaxTable,
};

export interface TaxTableLookupOk {
  ok: true;
  tax: number;
  bracket: { low: number; high: number };
  /** Provenance info, useful for AI rationale / Nynaeve grounding. */
  source: { taxYear: number; url: string };
}

export interface TaxTableLookupErr {
  ok: false;
  reason: "year_not_supported" | "out_of_range" | "invalid_input";
  message: string;
}

export type TaxTableLookupResult = TaxTableLookupOk | TaxTableLookupErr;

/**
 * Look up tax for (taxableIncome, filingStatus) in the IRS tax table for
 * the given year. Returns a discriminated result — callers handle each
 * failure mode explicitly rather than getting `null` and having to guess.
 *
 * Returns "out_of_range" for income ≥ $100k (caller should use the Tax
 * Computation Worksheet instead) and for negative income.
 */
export function lookupTax(
  taxYear: number,
  taxableIncome: number,
  filingStatus: FilingStatus,
): TaxTableLookupResult {
  const table = TABLES_BY_YEAR[taxYear];
  if (!table) {
    return {
      ok: false,
      reason: "year_not_supported",
      message: `No tax table loaded for tax year ${taxYear}. Available: ${Object.keys(TABLES_BY_YEAR).join(", ")}.`,
    };
  }
  if (!Number.isFinite(taxableIncome)) {
    return {
      ok: false,
      reason: "invalid_input",
      message: `Taxable income must be finite; got ${taxableIncome}.`,
    };
  }
  if (taxableIncome < 0) {
    return {
      ok: false,
      reason: "out_of_range",
      message: `Taxable income ${taxableIncome} is negative.`,
    };
  }
  if (taxableIncome >= table.coverage.maxIncome) {
    return {
      ok: false,
      reason: "out_of_range",
      message: `Taxable income ${taxableIncome} is at/above the tax-table ceiling of $${table.coverage.maxIncome}. Use the Tax Computation Worksheet instead.`,
    };
  }
  const row = findRow(table.rows, taxableIncome);
  if (!row) {
    // Coverage is validated at ingest, so this would be a bug rather than
    // expected user-facing case. Still, fail loud.
    return {
      ok: false,
      reason: "out_of_range",
      message: `No tax-table row matched income ${taxableIncome} — coverage gap in tax-table-${taxYear}.json.`,
    };
  }
  return {
    ok: true,
    tax: row[filingStatus],
    bracket: { low: row.low, high: row.high },
    source: { taxYear: table.taxYear, url: table.source.url },
  };
}

// Linear scan with early exit. 2062 rows × O(n) is ~10µs in practice; we'd
// only need binary search if this became a hot path for batch lookups.
function findRow(rows: TaxTableRow[], income: number): TaxTableRow | undefined {
  for (const r of rows) {
    if (income >= r.low && income < r.high) return r;
    if (r.low > income) return undefined; // rows are sorted; can stop early
  }
  return undefined;
}

/** Available tax years, useful for diagnostic output. */
export function supportedTaxYears(): number[] {
  return Object.keys(TABLES_BY_YEAR).map(Number).sort((a, b) => a - b);
}
