// AUTO-GENERATED by scripts/emitFormTypes.ts.
// Source: forms/federal/1040/catalog.json
// Form: U.S. Individual Income Tax Return (form-1040, tax year 2025)
// Fields: 199
//
// Hand edits are overwritten on the next regeneration. To change a
// field shape, edit the catalog and re-run forms:emit-types.

export interface Form1040 {
  /**  Tax year beginning (month/day) */
  "header.tax_year_beginning": string | undefined;
  /**  Tax year ending (month/day) */
  "header.tax_year_ending_md": string | undefined;
  /**  Tax year ending (year) */
  "header.tax_year_ending_year": string | undefined;
  /**  Filed pursuant to section 301.9100-2 */
  "header.filed_pursuant_9100_2": boolean | undefined;
  /**  Combat zone */
  "header.combat_zone_checkbox": boolean | undefined;
  /**  Combat zone (text) */
  "header.combat_zone_text": string | undefined;
  /**  Deceased */
  "header.taxpayer_deceased_checkbox": boolean | undefined;
  /**  Deceased month */
  "header.taxpayer_deceased_month": string | undefined;
  /**  Deceased day */
  "header.taxpayer_deceased_day": string | undefined;
  /**  Deceased year */
  "header.taxpayer_deceased_year": string | undefined;
  /**  Spouse month */
  "header.spouse_deceased_month": string | undefined;
  /**  Spouse day */
  "header.spouse_deceased_day": string | undefined;
  /**  Spouse year */
  "header.spouse_deceased_year": string | undefined;
  /**  Other */
  "header.other_checkbox": boolean | undefined;
  /**  Other (description) */
  "header.other_description": string | undefined;
  /**  Other (amount) */
  "header.other_amount": number | undefined;
  /**  Other (additional field) */
  "header.other_additional": string | undefined;
  /**  Your first name and middle initial */
  "header.first_name_mi": string | undefined;
  /**  Last name */
  "header.last_name": string | undefined;
  /**  Your social security number */
  "header.ssn": string | undefined;
  /**  If joint return, spouse's first name and middle initial */
  "header.spouse_first_name_mi": string | undefined;
  /**  Spouse's last name */
  "header.spouse_last_name": string | undefined;
  /**  Spouse's social security number */
  "header.spouse_ssn": string | undefined;
  /**  Home address (number and street). If you have a P.O. box, see instructions. */
  "header.home_address": string | undefined;
  /**  Apt. no. */
  "header.apartment": string | undefined;
  /**  Check here if your main home, and your spouse's if filing a joint return, was in the U.S. for more than half of 2025 */
  "header.main_home_us_over_half_year": boolean | undefined;
  /**  City, town, or post office */
  "header.city": string | undefined;
  /**  State */
  "header.state": string | undefined;
  /**  ZIP code */
  "header.zip": string | undefined;
  /**  Foreign country name */
  "header.foreign_country_name": string | undefined;
  /**  Foreign province/state/county */
  "header.foreign_province_state_county": string | undefined;
  /**  Foreign postal code */
  "header.foreign_postal_code": string | undefined;
  /**  Presidential Election Campaign — You */
  "header.presidential_campaign_you": boolean | undefined;
  /**  Presidential Election Campaign — Spouse */
  "header.presidential_campaign_spouse": boolean | undefined;
  /**  Single */
  "header.filing_status_single": boolean | undefined;
  /**  Head of household (HOH) */
  "header.filing_status_hoh": boolean | undefined;
  /**  Married filing jointly (even if only one had income) */
  "header.filing_status_mfj": boolean | undefined;
  /**  Qualifying surviving spouse (QSS) */
  "header.filing_status_qss": boolean | undefined;
  /**  Married filing separately (MFS). Enter spouse's SSN above and full name here: */
  "header.filing_status_mfs": boolean | undefined;
  /**  Spouse's full name (if MFS) */
  "header.mfs_spouse_full_name": string | undefined;
  /**  If you checked the HOH or QSS box, enter the child's name if the qualifying person is a child but not your dependent */
  "header.hoh_qss_qualifying_child_name": string | undefined;
  /**  If treating a nonresident alien or dual-status alien spouse as a U.S. resident for the entire tax year, check the box and enter their name */
  "header.nonresident_alien_spouse_checkbox": boolean | undefined;
  /**  Nonresident alien or dual-status alien spouse name */
  "header.nonresident_alien_spouse_name": string | undefined;
  /**  Digital Assets — Yes */
  "header.digital_assets_yes": boolean | undefined;
  /**  Digital Assets — No */
  "header.digital_assets_no": boolean | undefined;
  /**  Dependent 1 — First name */
  "dependents.dep1_first_name": string | undefined;
  /**  Dependent 2 — First name */
  "dependents.dep2_first_name": string | undefined;
  /**  Dependent 3 — First name */
  "dependents.dep3_first_name": string | undefined;
  /**  Dependent 4 — First name */
  "dependents.dep4_first_name": string | undefined;
  /**  Dependent 1 — Last name */
  "dependents.dep1_last_name": string | undefined;
  /**  Dependent 2 — Last name */
  "dependents.dep2_last_name": string | undefined;
  /**  Dependent 3 — Last name */
  "dependents.dep3_last_name": string | undefined;
  /**  Dependent 4 — Last name */
  "dependents.dep4_last_name": string | undefined;
  /**  Dependent 1 — SSN */
  "dependents.dep1_ssn": string | undefined;
  /**  Dependent 2 — SSN */
  "dependents.dep2_ssn": string | undefined;
  /**  Dependent 3 — SSN */
  "dependents.dep3_ssn": string | undefined;
  /**  Dependent 4 — SSN */
  "dependents.dep4_ssn": string | undefined;
  /**  Dependent 1 — Relationship */
  "dependents.dep1_relationship": string | undefined;
  /**  Dependent 2 — Relationship */
  "dependents.dep2_relationship": string | undefined;
  /**  Dependent 3 — Relationship */
  "dependents.dep3_relationship": string | undefined;
  /**  Dependent 4 — Relationship */
  "dependents.dep4_relationship": string | undefined;
  /**  Dependent 1 — (5) Check if lived with you more than half of 2025 (a) Yes */
  "dependents.dep1_lived_with_you": boolean | undefined;
  /**  Dependent 2 — (5) Check if lived with you more than half of 2025 (a) Yes */
  "dependents.dep2_lived_with_you": boolean | undefined;
  /**  Dependent 3 — (5) Check if lived with you more than half of 2025 (a) Yes */
  "dependents.dep3_lived_with_you": boolean | undefined;
  /**  Dependent 4 — (5) Check if lived with you more than half of 2025 (a) Yes */
  "dependents.dep4_lived_with_you": boolean | undefined;
  /**  Check if more than four dependents */
  "dependents.more_than_four_dependents": boolean | undefined;
  /**  Dependent 1 — (5)(b) And in the U.S. */
  "dependents.dep1_lived_in_us": boolean | undefined;
  /**  Dependent 2 — (5)(b) And in the U.S. */
  "dependents.dep2_lived_in_us": boolean | undefined;
  /**  Dependent 3 — (5)(b) And in the U.S. */
  "dependents.dep3_lived_in_us": boolean | undefined;
  /**  Dependent 4 — (5)(b) And in the U.S. */
  "dependents.dep4_lived_in_us": boolean | undefined;
  /**  Dependent 1 — (6) Check if Full-time student */
  "dependents.dep1_full_time_student": boolean | undefined;
  /**  Dependent 1 — (6) Check if Permanently and totally disabled */
  "dependents.dep1_permanently_disabled": boolean | undefined;
  /**  Dependent 2 — (6) Check if Full-time student */
  "dependents.dep2_full_time_student": boolean | undefined;
  /**  Dependent 2 — (6) Check if Permanently and totally disabled */
  "dependents.dep2_permanently_disabled": boolean | undefined;
  /**  Dependent 3 — (6) Check if Full-time student */
  "dependents.dep3_full_time_student": boolean | undefined;
  /**  Dependent 3 — (6) Check if Permanently and totally disabled */
  "dependents.dep3_permanently_disabled": boolean | undefined;
  /**  Dependent 4 — (6) Check if Full-time student */
  "dependents.dep4_full_time_student": boolean | undefined;
  /**  Dependent 4 — (6) Check if Permanently and totally disabled */
  "dependents.dep4_permanently_disabled": boolean | undefined;
  /**  Dependent 1 — (7) Credits: Child tax credit */
  "dependents.dep1_child_tax_credit": boolean | undefined;
  /**  Dependent 1 — (7) Credits: Credit for other dependents */
  "dependents.dep1_other_dependent_credit": boolean | undefined;
  /**  Dependent 2 — (7) Credits: Child tax credit */
  "dependents.dep2_child_tax_credit": boolean | undefined;
  /**  Dependent 2 — (7) Credits: Credit for other dependents */
  "dependents.dep2_other_dependent_credit": boolean | undefined;
  /**  Dependent 3 — (7) Credits: Child tax credit */
  "dependents.dep3_child_tax_credit": boolean | undefined;
  /**  Dependent 3 — (7) Credits: Credit for other dependents */
  "dependents.dep3_other_dependent_credit": boolean | undefined;
  /**  Dependent 4 — (7) Credits: Child tax credit */
  "dependents.dep4_child_tax_credit": boolean | undefined;
  /**  Dependent 4 — (7) Credits: Credit for other dependents */
  "dependents.dep4_other_dependent_credit": boolean | undefined;
  /**  Check if your filing status is MFS or HOH and you lived apart from your spouse for the last 6 months of 2025 */
  "header.lived_apart_mfs_hoh": boolean | undefined;
  /**  Line 1a — Total amount from Form(s) W-2, box 1 */
  "line.1a": number | undefined;
  /**  Line 1b — Household employee wages not reported on Form(s) W-2 */
  "line.1b": number | undefined;
  /**  Line 1c — Tip income not reported on line 1a */
  "line.1c": number | undefined;
  /**  Line 1d — Medicaid waiver payments not reported on Form(s) W-2 */
  "line.1d": number | undefined;
  /**  Line 1e — Taxable dependent care benefits from Form 2441, line 26 */
  "line.1e": number | undefined;
  /**  Line 1f — Employer-provided adoption benefits from Form 8839, line 31 */
  "line.1f": number | undefined;
  /**  Line 1g — Wages from Form 8919, line 6 */
  "line.1g": number | undefined;
  /**  Line 1h — Other earned income type */
  "line.1h_type": string | undefined;
  /**  Line 1h — Other earned income amount */
  "line.1h_amount": number | undefined;
  /**  Line 1i — Nontaxable combat pay election */
  "line.1i": number | undefined;
  /**  Line 1z — Add lines 1a through 1h */
  "line.1z": number | undefined;
  /**  Line 2a — Tax-exempt interest */
  "line.2a": number | undefined;
  /**  Line 2b — Taxable interest */
  "line.2b": number | undefined;
  /**  Line 3a — Qualified dividends */
  "line.3a": number | undefined;
  /**  Line 3b — Ordinary dividends */
  "line.3b": number | undefined;
  /**  Line 3c — Check if your child's dividends are included in Line 3a (box 1) */
  "line.3c_box1": boolean | undefined;
  /**  Line 3c — Check if your child's dividends are included in Line 3b (box 2) */
  "line.3c_box2": boolean | undefined;
  /**  Line 4a — IRA distributions */
  "line.4a": number | undefined;
  /**  Line 4b — Taxable amount */
  "line.4b": number | undefined;
  /**  Line 4c — Check if (see instructions): Rollover (box 1) */
  "line.4c_rollover": boolean | undefined;
  /**  Line 4c — Check if QCD (box 2) */
  "line.4c_qcd": boolean | undefined;
  /**  Line 4c — Check if (box 3) */
  "line.4c_box3": boolean | undefined;
  /**  Line 4c — Amount (box 3) */
  "line.4c_box3_amount": number | undefined;
  /**  Line 5a — Pensions and annuities */
  "line.5a": number | undefined;
  /**  Line 5b — Taxable amount */
  "line.5b": number | undefined;
  /**  Line 5c — Check if (see instructions): Rollover (box 1) */
  "line.5c_rollover": boolean | undefined;
  /**  Line 5c — Check if PSO (box 2) */
  "line.5c_pso": boolean | undefined;
  /**  Line 5c — Check if (box 3) */
  "line.5c_box3": boolean | undefined;
  /**  Line 5c — Amount (box 3) */
  "line.5c_box3_amount": number | undefined;
  /**  Line 6a — Social security benefits */
  "line.6a": number | undefined;
  /**  Line 6b — Taxable amount */
  "line.6b": number | undefined;
  /**  Line 6c — Check if you elect to use the lump-sum election method */
  "line.6c_lump_sum_election": boolean | undefined;
  /**  Line 6d — Check if you are married filing separately and lived apart from your spouse the entire year */
  "line.6d_mfs_lived_apart": boolean | undefined;
  /**  Line 7a — Capital gain or (loss). Attach Schedule D if required */
  "line.7a": number | undefined;
  /**  Line 7b — Check if: Schedule D not required */
  "line.7b_schedule_d_not_required": boolean | undefined;
  /**  Line 7b — Check if: Includes child's capital gain or (loss) */
  "line.7b_includes_childs_capital_gain": boolean | undefined;
  /**  Line 7b — Includes child's capital gain or (loss) amount */
  "line.7b_childs_capital_gain_amount": number | undefined;
  /**  Line 8 — Additional income from Schedule 1, line 10 */
  "line.8": number | undefined;
  /**  Line 9 — Add lines 1z, 2b, 3b, 4b, 5b, 6b, 7a, and 8. This is your total income */
  "line.9": number | undefined;
  /**  Line 10 — Adjustments to income from Schedule 1, line 26 */
  "line.10": number | undefined;
  /**  Line 11a — Subtract line 10 from line 9. This is your adjusted gross income */
  "line.11a": number | undefined;
  /**  Line 11b — Amount from line 11a (adjusted gross income) */
  "line.11b": number | undefined;
  /**  Line 12a — You as a dependent (Someone can claim) */
  "line.12a_you_as_dependent": boolean | undefined;
  /**  Line 12a — Your spouse as a dependent (Someone can claim) */
  "line.12a_spouse_as_dependent": boolean | undefined;
  /**  Line 12b — Spouse itemizes on a separate return */
  "line.12b_spouse_itemizes_separate": boolean | undefined;
  /**  Line 12b — You were a dual-status alien */
  "line.12b_dual_status_alien": boolean | undefined;
  /**  Line 12d — You: Were born before January 2, 1961 */
  "line.12d_you_born_before_jan2_1961": boolean | undefined;
  /**  Line 12d — You: Are blind */
  "line.12d_you_blind": boolean | undefined;
  /**  Line 12d — Spouse: Was born before January 2, 1961 */
  "line.12d_spouse_born_before_jan2_1961": boolean | undefined;
  /**  Line 12d — Spouse: Is blind */
  "line.12d_spouse_blind": boolean | undefined;
  /**  Line 12e — Standard deduction or itemized deductions (from Schedule A) */
  "line.12e": number | undefined;
  /**  Line 13a — Qualified business income deduction from Form 8995 or Form 8995-A */
  "line.13a": number | undefined;
  /**  Line 13b — Additional deductions from Schedule 1-A, line 38 */
  "line.13b": number | undefined;
  /**  Line 14 — Add lines 12e, 13a, and 13b */
  "line.14": number | undefined;
  /**  Line 15 — Subtract line 14 from line 11b. Taxable income */
  "line.15": number | undefined;
  /**  Line 16 — Tax: Check if from Form(s) 8814 */
  "line.16_from_form_8814": boolean | undefined;
  /**  Line 16 — Tax: Check if from Form 4972 */
  "line.16_from_form_4972": boolean | undefined;
  /**  Line 16 — Tax: Check if from other form (3rd checkbox) */
  "line.16_from_other_form": boolean | undefined;
  /**  Line 16 — Tax (third form number, if any) */
  "line.16_other_form_number": string | undefined;
  /**  Line 16 — Tax (see instructions) */
  "line.16": number | undefined;
  /**  Line 17 — Amount from Schedule 2, line 3 */
  "line.17": number | undefined;
  /**  Line 18 — Add lines 16 and 17 */
  "line.18": number | undefined;
  /**  Line 19 — Child tax credit or credit for other dependents from Schedule 8812 */
  "line.19": number | undefined;
  /**  Line 20 — Amount from Schedule 3, line 8 */
  "line.20": number | undefined;
  /**  Line 21 — Add lines 19 and 20 */
  "line.21": number | undefined;
  /**  Line 22 — Subtract line 21 from line 18. If zero or less, enter -0- */
  "line.22": number | undefined;
  /**  Line 23 — Other taxes, including self-employment tax, from Schedule 2, line 21 */
  "line.23": number | undefined;
  /**  Line 24 — Add lines 22 and 23. Total tax */
  "line.24": number | undefined;
  /**  Line 25a — Federal income tax withheld from Form(s) W-2 */
  "line.25a": number | undefined;
  /**  Line 25b — Federal income tax withheld from Form(s) 1099 */
  "line.25b": number | undefined;
  /**  Line 25c — Federal income tax withheld from other forms (see instructions) */
  "line.25c": number | undefined;
  /**  Line 25d — Add lines 25a through 25c */
  "line.25d": number | undefined;
  /**  Line 26 — 2025 estimated tax payments and amount applied from 2024 return */
  "line.26": number | undefined;
  /**  Former spouse's SSN (if you made estimated tax payments with your former spouse in 2025) */
  "line.former_spouse_ssn": string | undefined;
  /**  Line 27a — Earned income credit (EIC) */
  "line.27a": number | undefined;
  /**  Line 27b — Clergy filing Schedule SE (see instructions) */
  "line.27b_clergy_schedule_se": boolean | undefined;
  /**  Line 27c — If you do not want to claim the EIC, check here */
  "line.27c_no_eic_claim": boolean | undefined;
  /**  Line 28 — Additional child tax credit (ACTC): If you do not want to claim the ACTC, check here */
  "line.28_no_actc_claim": boolean | undefined;
  /**  Line 28 — Additional child tax credit (ACTC) from Schedule 8812 */
  "line.28": number | undefined;
  /**  Line 29 — American opportunity credit from Form 8863, line 8 */
  "line.29": number | undefined;
  /**  Line 30 — Refundable adoption credit from Form 8839, line 13 */
  "line.30": number | undefined;
  /**  Line 31 — Amount from Schedule 3, line 15 */
  "line.31": number | undefined;
  /**  Line 32 — Add lines 27a, 28, 29, 30, and 31. Total other payments and refundable credits */
  "line.32": number | undefined;
  /**  Line 33 — Add lines 25d, 26, and 32. Total payments */
  "line.33": number | undefined;
  /**  Line 34 — If line 33 is more than line 24, the amount you overpaid */
  "line.34": number | undefined;
  /**  Line 35a — If Form 8888 is attached, check here */
  "line.35a_form_8888_attached": boolean | undefined;
  /**  Line 35a — Amount of line 34 you want refunded to you */
  "line.35a": number | undefined;
  /**  Line 35b — Routing number */
  "line.35b_routing_number": string | undefined;
  /**  Line 35c — Type: Checking */
  "line.35c_checking": boolean | undefined;
  /**  Line 35c — Type: Savings */
  "line.35c_savings": boolean | undefined;
  /**  Line 35d — Account number */
  "line.35d_account_number": string | undefined;
  /**  Line 36 — Amount of line 34 you want applied to your 2026 estimated tax */
  "line.36": number | undefined;
  /**  Line 37 — Amount you owe */
  "line.37": number | undefined;
  /**  Line 38 — Estimated tax penalty (see instructions) */
  "line.38": number | undefined;
  /**  Third Party Designee — Yes. Complete below. */
  "page2.third_party_designee_yes": boolean | undefined;
  /**  Third Party Designee — No */
  "page2.third_party_designee_no": boolean | undefined;
  /**  Designee's name */
  "page2.designee_name": string | undefined;
  /**  Phone no. */
  "page2.designee_phone": string | undefined;
  /**  Personal identification number (PIN) */
  "page2.designee_pin": string | undefined;
  /**  Your occupation */
  "signing.taxpayer_occupation": string | undefined;
  /**  If the IRS sent you an Identity Protection PIN, enter it here (see inst.) */
  "signing.taxpayer_ip_pin": string | undefined;
  /**  Spouse's occupation */
  "signing.spouse_occupation": string | undefined;
  /**  If the IRS sent your spouse an Identity Protection PIN, enter it here (see inst.) */
  "signing.spouse_ip_pin": string | undefined;
  /**  Phone no. */
  "signing.taxpayer_phone": string | undefined;
  /**  Email address */
  "signing.taxpayer_email": string | undefined;
  /**  Check if: Self-employed */
  "signing.preparer_self_employed": boolean | undefined;
  /**  Paid Preparer — Preparer's name */
  "signing.preparer_name": string | undefined;
  /**  Paid Preparer — PTIN */
  "signing.preparer_ptin": string | undefined;
  /**  Firm's name */
  "signing.preparer_firm_name": string | undefined;
  /**  Phone no. */
  "signing.preparer_phone": string | undefined;
  /**  Firm's address */
  "signing.preparer_firm_address": string | undefined;
  /**  Firm's EIN */
  "signing.preparer_firm_ein": string | undefined;
}
